In [2]:
import streamlit as st
import numpy as np 
import pandas as pd
import plotly.express as px

# first make the sidebar title

In [ ]:
st.sidebar.title('India ka Data Viz')

In [ ]:
# so first we make the sidebox
st.sidebar.selectbox(label='Select a parameter')

In [ ]:
final_df = pd.read_csv('india.csv')
final_df

,State,District,Latitude,Longitude,Population,Male,Female,Literate,Male_Literate,Female_Literate,Housholds_with_Electric_Lighting,Households_with_Internet,Rural_Households,Urban_Households,Total_Power_Parity,sex_ratio,literacy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,2741239,1369597,1371642,1483347,856350,626997,566108,5512,597466,220248,4181,100.0,54.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,4081148,2064495,2016653,2310960,1338474,972486,897970,8606,902997,341431,5799,98.0,57.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,4174064,2090204,2083860,2667878,1484794,1183084,944555,13763,907970,395900,5926,100.0,64.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,5154296,2569688,2584608,3288577,1716933,1571644,1297273,22411,1199479,406362,7211,101.0,64.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,4887813,2440521,2447292,2960441,1634726,1325715,1186028,19383,1069877,513113,6981,100.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,3988845,2051541,1937304,2086432,1152019,934413,297716,5357,830318,128678,4191,94.0,52.0
513,West Bengal,Murshidabad,24.259507,88.168169,7103807,3627564,3476243,4055834,2177187,1878647,541169,7951,1501066,350899,8088,96.0,57.0
514,West Bengal,Nadia,23.564110,88.582930,5167600,2653768,2513832,3480555,1878866,1601689,623729,12787,1081381,468390,7048,95.0,67.0
515,West Bengal,Puruliya,23.254192,86.396853,2930115,1496996,1433119,1624905,1002058,622847,189889,3551,653219,99433,3309,96.0,55.0
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,3007134,1551066,1456068,1489667,853495,636172,199307,2883,683981,94269,3214,94.0,50.0

In [ ]:
# tho state hona chaya selection
# lakin state repeat ho raha ha isliya 
final_df['State'].unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chandigarh', 'Chhattisgarh', 'Daman and Diu', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Orissa', 'Puducherry',
       'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura',
       'Uttar Pradesh', 'Uttaranchal', 'West Bengal'], dtype=object)

In [6]:
# convert into list because list ma convert karna sa overal india aa jaya ga
# ek option 

list_of_states = list(final_df['State'].unique())
list_of_states

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Daman and Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Orissa',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttaranchal',
 'West Bengal']

In [7]:
list_of_states.insert(0,'Overall india')
list_of_states

['Overall india',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Daman and Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Orissa',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttaranchal',
 'West Bengal']

# select a state sidebar

In [ ]:
df = pd.read_csv(filepath_or_buffer=r'C:\Users\sumit\My_code_files\Week 9 -Data Visulziation\plotly project\india.csv')
list_of_states = list(df['State'].unique())
list_of_states.insert(0,'Overall india')

st.sidebar.title('India ka Data Viz')

st.sidebar.selectbox(label='Select a State',options=list_of_states)

In [8]:
df = pd.read_csv('india.csv')
df

,State,District,Latitude,Longitude,Population,Male,Female,Literate,Male_Literate,Female_Literate,Housholds_with_Electric_Lighting,Households_with_Internet,Rural_Households,Urban_Households,Total_Power_Parity,sex_ratio,literacy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,2741239,1369597,1371642,1483347,856350,626997,566108,5512,597466,220248,4181,100.0,54.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,4081148,2064495,2016653,2310960,1338474,972486,897970,8606,902997,341431,5799,98.0,57.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,4174064,2090204,2083860,2667878,1484794,1183084,944555,13763,907970,395900,5926,100.0,64.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,5154296,2569688,2584608,3288577,1716933,1571644,1297273,22411,1199479,406362,7211,101.0,64.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,4887813,2440521,2447292,2960441,1634726,1325715,1186028,19383,1069877,513113,6981,100.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,3988845,2051541,1937304,2086432,1152019,934413,297716,5357,830318,128678,4191,94.0,52.0
513,West Bengal,Murshidabad,24.259507,88.168169,7103807,3627564,3476243,4055834,2177187,1878647,541169,7951,1501066,350899,8088,96.0,57.0
514,West Bengal,Nadia,23.564110,88.582930,5167600,2653768,2513832,3480555,1878866,1601689,623729,12787,1081381,468390,7048,95.0,67.0
515,West Bengal,Puruliya,23.254192,86.396853,2930115,1496996,1433119,1624905,1002058,622847,189889,3551,653219,99433,3309,96.0,55.0
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,3007134,1551066,1456068,1489667,853495,636172,199307,2883,683981,94269,3214,94.0,50.0

In [9]:
df.columns

Index(['State', 'District', 'Latitude', 'Longitude', 'Population', 'Male',
       'Female', 'Literate', 'Male_Literate', 'Female_Literate',
       'Housholds_with_Electric_Lighting', 'Households_with_Internet',
       'Rural_Households', 'Urban_Households', 'Total_Power_Parity',
       'sex_ratio', 'literacy_rate'],
      dtype='object')

In [15]:
df.columns.nunique() - 4

13

In [26]:
df.columns[4:].to_list()

['Population',
 'Male',
 'Female',
 'Literate',
 'Male_Literate',
 'Female_Literate',
 'Housholds_with_Electric_Lighting',
 'Households_with_Internet',
 'Rural_Households',
 'Urban_Households',
 'Total_Power_Parity',
 'sex_ratio',
 'literacy_rate']

In [16]:
# tho humna 4 (0,1,2,3)onwards sab kuch chay 
# counting start at 0
df.columns[4:10].to_list()

['Population',
 'Male',
 'Female',
 'Literate',
 'Male_Literate',
 'Female_Literate']

In [17]:
df.columns[11:].to_list()

['Households_with_Internet',
 'Rural_Households',
 'Urban_Households',
 'Total_Power_Parity',
 'sex_ratio',
 'literacy_rate']

# primary and secondary parameter

In [ ]:
df = pd.read_csv(filepath_or_buffer=r'C:\Users\sumit\My_code_files\Week 9 -Data Visulziation\plotly project\india.csv')

# selection of state 
list_of_states = list(df['State'].unique())
list_of_states.insert(0,'Overall india')

# selection of primary parameter 
primary_list = df.columns[4:10].to_list()
secondary_list = df.columns[11:].to_list()

st.sidebar.title('India ka Data Viz')

selected_state = st.sidebar.selectbox(label='Select a State',options=list_of_states)

primary = st.sidebar.selectbox(label='Select Primary Parameter ',options=primary_list)
secondary = st.sidebar.selectbox(label='Select secondary Parameter ',options=secondary_list)

# make a plot button

In [ ]:
df = pd.read_csv(filepath_or_buffer=r'C:\Users\sumit\My_code_files\Week 9 -Data Visulziation\plotly project\india.csv')

# selection of state 
list_of_states = list(df['State'].unique())
list_of_states.insert(0,'Overall india')

# selection of primary and secondary parameter 
primary_list = df.columns[4:10].to_list()
secondary_list = df.columns[11:].to_list()

st.sidebar.title('India ka Data Viz')

# sidebar selectbox
selected_state = st.sidebar.selectbox(label='Select a State',options=list_of_states)

primary = st.sidebar.selectbox(label='Select Primary Parameter ',options=primary_list)
secondary = st.sidebar.selectbox(label='Select secondary Parameter ',options=secondary_list)

# user press a button and we plot the graph
plot = st.sidebar.button('Plot Graph')

if plot:
    pass

In [ ]:
# plan we make first india ka plot then we make state ka plot

In [ ]:
import streamlit as st
import numpy as np 
import pandas as pd
import plotly.express as px

df = pd.read_csv(filepath_or_buffer=r'C:\Users\sumit\My_code_files\Week 9 -Data Visulziation\plotly project\india.csv')

# selection of state 
list_of_states = list(df['State'].unique())
list_of_states.insert(0,'Overall india')

# selection of primary and secondary parameter 
primary_list = df.columns[4:10].to_list()
secondary_list = df.columns[11:].to_list()

st.sidebar.title('India ka Data Viz')

# sidebar selectbox
selected_state = st.sidebar.selectbox(label='Select a State',options=list_of_states)

primary = st.sidebar.selectbox(label='Select Primary Parameter ',options=primary_list)
secondary = st.sidebar.selectbox(label='Select secondary Parameter ',options=secondary_list)

# user press a button and we plot the graph
plot = st.sidebar.button('Plot Graph')

# make two cases for overall india and state
if plot:
    if selected_state == 'Overall india':
        pass # plot for india
    else:
        pass # plot for state

In [ ]:
# now I make the plot

In [25]:
px.scatter_map(
    data_frame=df,
    lat= df['Latitude'],
    lon= df['Longitude'],
    size= df['Population'],
    color=df['literacy_rate'],
    color_continuous_scale=px.colors.cyclical.IceFire, size_max=15,
    hover_name= df['District']
)

In [ ]:
fig = px.scatter_mapbox(df, lat="Latitude", lon="Longitude", size=primary, color=secondary, zoom=4,size_max=35,
                                mapbox_style="carto-positron",width=1200,height=700,hover_name='District')

In [ ]:
fig = px.scatter_map(data_frame=df lat=)

In [21]:
px.scatter_geo(
    data_frame=df,
    lat= df['Latitude'],
    lon= df['Longitude'],
    #color=df['Population']
)

In [ ]:
import streamlit as st
import numpy as np 
import pandas as pd
import plotly.express as px

df = pd.read_csv(filepath_or_buffer=r'C:\Users\sumit\My_code_files\Week 9 -Data Visulziation\plotly project\india.csv')

# selection of state 
list_of_states = list(df['State'].unique())
list_of_states.insert(0,'Overall india')

# selection of primary and secondary parameter 
primary_list = df.columns[4:].to_list()
secondary_list = df.columns[4:].to_list()

st.sidebar.title('India ka Data Viz')

# sidebar selectbox
selected_state = st.sidebar.selectbox(label='Select a State',options=list_of_states)

primary = st.sidebar.selectbox(label='Select Primary Parameter ',options=primary_list)
secondary = st.sidebar.selectbox(label='Select secondary Parameter ',options=secondary_list)

# user press a button and we plot the graph
plot = st.sidebar.button('Plot Graph')

# make two cases for overall india and state
if plot:
    if selected_state == 'Overall india':
        fig = px.scatter_map(
                    data_frame=df,
                    lat= df['Latitude'],
                    lon= df['Longitude'],
                    size= primary,
                    color=secondary,
                    color_continuous_scale=px.colors.cyclical.IceFire, size_max=15,
                    hover_name= df['District'],
                    width= 1200,height= 700
                    )
        
        st.plotly_chart(figure_or_data=fig,use_container_width=True)
    else:
        pass # plot for state