In [8]:
# today we work on text data nlp analysis
# agar apka dataset ma coloumns text ha tho aap kasa basic nlp analysis kar sakta ho
# text based data ma kasa navigate karna using pandas

In [9]:
# this class on intersection of pandas and nlp 
# love it and very excited sapana par pahala kadam

In [10]:
# so tho jab aap nlp ma start karta ho 
# so you work on basic dataset like imbd movies review
# amozon review # whatsup chat analysis # twitter tweets

In [11]:
# so imbd dataset have two coloumns
# review
# sentiment of the movie 
# 50,000 movies ka review

In [12]:
# ek machine learning ya deep learning enginer ka kam hota ha ki vo future
# koi naya review diya jayaga tho vo automatically predict kar paya ga ki sentiment kiya ha
# nlp bhut jaga ha apka keyborad ma recommend karta ha words ko 
# email ma who email ko read karta ha aor spam ha ki nahi ha 
# wo bhi sentiment analysis kar raha ha

In [13]:
# deko amozon ,flipkart na ek product launch kiya
# aor us par 20,000 reviews aya ab koi bhi un reviews ko baad kar nahi padega amazon company ma
# wo ek sentiment model baneya
# aor bolega 70% are postive 30% are negative something like this

In [14]:
import pandas as pd
df = pd.read_csv('IMDB Dataset.csv')

In [15]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [16]:
df.shape
# 2 col
# 50 thousand rows

(50000, 2)

In [17]:
# kisi ek movie ka review kasa dikta ha 
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [18]:
# huma kiya karna ha 
# imagine yourself you are working in a company
# company na apki team ko bola apko ek sentiment analysis system banana ha 
# wo revies pad ka bata paya reviews positive ha ki negative ha
# or apko apna model is data par train karna ha
# now you are the part of the team
# apko kam diya gaya ha
# data ko clean karna ,uska upar eda karna ,aor features create karna

In [19]:
# review  |sentiment
#   ---       +ve 
#   ---       -ve 
# .... 

#---------------------------
# you have to make a ml or dl model
# that you give a new review it can inference
# it is postive or negative
#---------------------------

# a_new_review | +ve/-ve
# ...

# model building steps
1. Data Gathering
2. Data Cleaning

## Data gathering 
step is already done of 50 k movies

In [20]:
# so famous line in ml
# garbage in garabage out
# so your data is super clean for models

## Data Cleaning
1. lowering 
2. removing leading and trailing spaces
3. removing html tags
4. removing url
5. expanding abbreviations 
6. spelling correction
7. punctuations
8. remove special characters

1. lowering = sabhi words ko lowercase karna kahi capital kahi small hota ha
2. removing leading and trailing spaces = extra spaces ko remove karna
3. removing html tags= data gathering wala na web scraping kiya tha usma kuch html tags ha huma vo remove karna hoga
4. removing url = kyuki vo meaning ma contribute nahi karaga isliya remove url 
5. expanding abbreviations => kahi does n't -> isko does not couldn't -> could not 
6. spelling correction -> kahi par night ha aor user na nigh lika ml model isa alag treat karaga isliya
7. punctuations = ?,! ya meaning ma kuch contribute nahi karta so we remove 
8. remove special characters = @, #,$

In [21]:
# ek given sentence ya word ha --sentiment-> uska meaning

## Data Preprocessing
aap data ko is format ma lata ho jissa us par machine learning model kam kar paya
- tokenization 
- stopward removal 
- stemming

- tokonization -> breaks sentences into words or words into letters I am Energetic ->[I,am,Energetic]
- stopward removal -> jasa(and,I have,could) ya meaning ma contribute nahi kar raha ha 
- stemming -> words ko root form ma la kar aa jata ho (dance,danced ,danced) ko dance ma convert karna

## Eda
`Explorarity Data analysis`

## make features
feature matlab coloumns you can create new coloumns for ml models 
one example is number of words.

In [22]:

# revies     number of words
# - r1              12
# - r2              3
# - r3              7
# ...

In [23]:
# may be this new col(feature) help our machine learning model
# aap esa kuch logic bana sakta ho ki postive reviews are short and negative are long.

## vectorization
machine learning models works only numbers. lakin hamra string english alphaets ma ha hama kuch jugaad lagana hoga aor usa numbers ma convert karna hoga. 50 thousand review ko numbers ma convert karna ha

various techniques are 
- bag of words
- tf idf
- word2vector

## modeiling
modeling ka matlab aap apna data ka upar alag alag machine learning  model or deep learning models try karta ho aor dekta ho konsa better perfrom kar raha ha .

## evaluate 
aap best model ko select karta ho .

## Deploy
website ya app ma convert karka server par dal deta ho.

## Monitar 
kuch gadbad hua usa dekna new data add karna

# What we do today
1. Data Gathering
2. Data cleaning 
3. Data preprocessing
4. Eda
5. Make features
6. vectorization
7. modeling
8. evaluation
9. deploy
10. monitar

aap team ma ek data analyst ho tho aap step 6 tak kara ga.

we also use other libararies in today session because sara kam pandas nahi kar sakta scikit learn,nltk,textblob

hum pandas sa thoda aga aor nlp ka thoda picha ha

# check missing and duplicated data

### check missing values

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [25]:
# no missing values

### check duplicated values

In [26]:
df.duplicated().sum()

np.int64(418)

In [27]:
# there are 418 duplicate values 
# now drop them 
df.drop_duplicates(inplace=True)

In [28]:
# after permanent drop values 
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [29]:
df['review'].count()

np.int64(49582)

In [30]:
# we filter the data

# cleaning data

### lowercase 
kuch capital letters ha kuch small letters ha who apko nahi chaya --> apko uniformaity chaya

In [31]:
# so pandas support vectorization
# one operation on multiple string 
df['review'].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

In [32]:
# make it permant by assign  it 
df['review'] = df['review'].str.lower()

### remove trailing space 
apka data ma aga ya picha spaces aa sakta ha .

In [33]:
df['review'].str.strip()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

In [34]:
# make it permanent by assigning it 
df['review'] = df['review'].str.strip()

### remove html tags
because user na webscrapping kiya usma kuch aa gaya hoga.

In [35]:
import re 
def remove_html(data):
    data = re.sub(pattern=r'<.*?>',repl='',string=data )
    return data

remove_html('<p>I am in focus and flow </p>,<br><img>')

'I am in focus and flow ,'

In [36]:
df['review'].apply(remove_html)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

In [37]:
# also use the replace function 
df['review'].str.replace(r'<.*?>','' )

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

In [38]:
# make in permant by reassign it 
df['review'] = df['review'].str.replace(r'<.*?>','',regex=True )

In [39]:
# ya pandas ka default function so it is fast and optimised

### remove url

In [40]:
# it's something like 
# http://campusx.in www.campusx.in www.campusx.co.in

def remove_url(data):
    data=re.sub(r"https?://\S+|www\.\S+",'',data)
    return data

remove_url('to register and login in www.campusx.in')

'to register and login in '

In [41]:
remove_html('this is testing https://campusx..in')

'this is testing https://campusx..in'

In [42]:
df['review'].replace(r"https?://\S+|www\.\S+",'',regex=True)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

In [43]:
## find the urls
df['review'].str.contains(r"https?://\S+|www\.\S+").sum()

np.int64(194)

In [44]:
# see the 195 urls
df[df['review'].str.contains(r"https?://\S+|www\.\S+")].values[0]

array(['mario lewis of the competitive enterprise institute has written a definitive 120-page point-by-point, line-by-line refutation of this mendacious film, which should be titled a convenient lie. the website address where his debunking report, which is titled "a skeptic\'s guide to an inconvenient truth" can be found at is :www.cei.org. a shorter 10-page version can be found at: www.cei.org/pdf/5539.pdf once you read those demolitions, you\'ll realize that alleged "global warming" is no more real or dangerous than the y2k scare of 1999, which gore also endorsed, as he did the pseudo-scientific film the day after tomorrow, which was based on a book written by alleged ufo abductee whitley strieber. as james "the amazing" randi does to psychics, and philip klass does to ufos, and gerald posner does to jfk conspir-idiocy theories, so does mario lewis does to al gore\'s movie and the whole "global warming" scam.',
       'negative'], dtype=object)

In [45]:
# see the 195 urls
df[df['review'].str.contains(r"https?://\S+|www\.\S+")]

                                                  review sentiment
742    mario lewis of the competitive enterprise inst...  negative
907    following directly from where the story left o...  positive
1088   this quasi j-horror film followed a young woma...  negative
1137   i really think i should make my case and have ...  positive
1141   this show has to be my favorite out of all the...  positive
...                                                  ...       ...
48887  trite and unoriginal. it's like someone watche...  negative
49063  trick or treat, quickie review this zany romp ...  positive
49596  this is absolutely the best 80s cartoon ever, ...  positive
49637  if you liked the richard chamberlain version o...  positive
49951  "scientists at a remote lab experiment on (ins...  negative

[194 rows x 2 columns]

In [46]:
# now permantely remove it 
df['review'] = df['review'].replace(r"https?://\S+|www\.\S+", '', regex=True)

In [47]:
# count thr urls 
df['review'].str.contains(r"https?://\S+|www\.\S+").sum()

np.int64(0)

### expanding abbreviations 
- doesn't ha tho --> does not
- couldn't ha tho --> could not 
- you need a lot of big dictionary for it

In [48]:
def remove_abb(data):
    data = re.sub(r"he's", "he is", data)
    data = re.sub(r"there's", "there is", data)
    data = re.sub(r"We're", "We are", data)
    data = re.sub(r"That's", "That is", data)
    data = re.sub(r"won't", "will not", data)
    data = re.sub(r"they're", "they are", data)
    data = re.sub(r"Can't", "Cannot", data)
    data = re.sub(r"wasn't", "was not", data)
    data = re.sub(r"don\x89Ûªt", "do not", data)
    data= re.sub(r"aren't", "are not", data)
    data = re.sub(r"isn't", "is not", data)
    data = re.sub(r"What's", "What is", data)
    data = re.sub(r"haven't", "have not", data)
    data = re.sub(r"hasn't", "has not", data)
    data = re.sub(r"There's", "There is", data)
    data = re.sub(r"He's", "He is", data)
    data = re.sub(r"It's", "It is", data)
    data = re.sub(r"You're", "You are", data)
    data = re.sub(r"I'M", "I am", data)
    data = re.sub(r"shouldn't", "should not", data)
    data = re.sub(r"wouldn't", "would not", data)
    data = re.sub(r"i'm", "I am", data)
    data = re.sub(r"I\x89Ûªm", "I am", data)
    data = re.sub(r"I'm", "I am", data)
    data = re.sub(r"Isn't", "is not", data)
    data = re.sub(r"Here's", "Here is", data)
    data = re.sub(r"you've", "you have", data)
    data = re.sub(r"you\x89Ûªve", "you have", data)
    data = re.sub(r"we're", "we are", data)
    data = re.sub(r"what's", "what is", data)
    data = re.sub(r"couldn't", "could not", data)
    data = re.sub(r"we've", "we have", data)
    data = re.sub(r"it\x89Ûªs", "it is", data)
    data = re.sub(r"doesn\x89Ûªt", "does not", data)
    data = re.sub(r"It\x89Ûªs", "It is", data)
    data = re.sub(r"Here\x89Ûªs", "Here is", data)
    data = re.sub(r"who's", "who is", data)
    data = re.sub(r"I\x89Ûªve", "I have", data)
    data = re.sub(r"y'all", "you all", data)
    data = re.sub(r"can\x89Ûªt", "cannot", data)
    data = re.sub(r"would've", "would have", data)
    data = re.sub(r"it'll", "it will", data)
    data = re.sub(r"we'll", "we will", data)
    data = re.sub(r"wouldn\x89Ûªt", "would not", data)
    data = re.sub(r"We've", "We have", data)
    data = re.sub(r"he'll", "he will", data)
    data = re.sub(r"Y'all", "You all", data)
    data = re.sub(r"Weren't", "Were not", data)
    data = re.sub(r"Didn't", "Did not", data)
    data = re.sub(r"they'll", "they will", data)
    data = re.sub(r"they'd", "they would", data)
    data = re.sub(r"DON'T", "DO NOT", data)
    data = re.sub(r"That\x89Ûªs", "That is", data)
    data = re.sub(r"they've", "they have", data)
    data = re.sub(r"i'd", "I would", data)
    data = re.sub(r"should've", "should have", data)
    data = re.sub(r"You\x89Ûªre", "You are", data)
    data = re.sub(r"where's", "where is", data)
    data = re.sub(r"Don\x89Ûªt", "Do not", data)
    data = re.sub(r"we'd", "we would", data)
    data = re.sub(r"i'll", "I will", data)
    data = re.sub(r"weren't", "were not", data)
    data = re.sub(r"They're", "They are", data)
    data = re.sub(r"Can\x89Ûªt", "Cannot", data)
    data = re.sub(r"you\x89Ûªll", "you will", data)
    data = re.sub(r"I\x89Ûªd", "I would", data)
    data = re.sub(r"let's", "let us", data)
    data = re.sub(r"it's", "it is", data)
    data = re.sub(r"can't", "cannot", data)
    data = re.sub(r"don't", "do not", data)
    data = re.sub(r"you're", "you are", data)
    data = re.sub(r"i've", "I have", data)
    data = re.sub(r"that's", "that is", data)
    data = re.sub(r"i'll", "I will", data)
    data = re.sub(r"doesn't", "does not",data)
    data = re.sub(r"i'd", "I would", data)
    data = re.sub(r"didn't", "did not", data)
    data = re.sub(r"ain't", "am not", data)
    data = re.sub(r"you'll", "you will", data)
    data = re.sub(r"I've", "I have", data)
    data = re.sub(r"Don't", "do not", data)
    data = re.sub(r"I'll", "I will", data)
    data = re.sub(r"I'd", "I would", data)
    data = re.sub(r"Let's", "Let us", data)
    data = re.sub(r"you'd", "You would", data)
    data = re.sub(r"It's", "It is", data)
    data = re.sub(r"Ain't", "am not", data)
    data = re.sub(r"Haven't", "Have not", data)
    data = re.sub(r"Could've", "Could have", data)
    data = re.sub(r"youve", "you have", data)  
    data = re.sub(r"donå«t", "do not", data)
    
    return data

In [49]:
# testing of it . 
remove_abb(" I don't know and I couldn't tell you")

' I do not know and I could not tell you'

In [50]:
df['review'] = df['review'].apply(remove_abb)

In [51]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there is a family where a little boy...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    I am going to have to disagree with the previo...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

### spelling correction 
- input -> incorrect spelling 
- output -> correct speeling
- ya khud ma ek model bana ha bhut bada task ha so we use the library usma ya feature ha

In [52]:
from textblob import TextBlob

our_text = 'hi I can drie at nigt'
TextBlob(our_text).correct().string

ModuleNotFoundError: No module named 'textblob'

In [ ]:
def spelling_correction(inp_text):
    return TextBlob(inp_text).correct().string
    
# df['review'] = df['review'].apply(spelling_correction)

In [ ]:
# from textblob import TextBlob
# from functools import lru_cache

# @lru_cache(maxsize=50000)
# def correct_text_cached(text):
#     return str(TextBlob(text).correct())

# df['review'] = df['review'].apply(correct_text_cached)

### puncatation

In [ ]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def remove_puctuation(text):
    
    for i in string.punctuation:
        if i in text:
            text = text.replace(i,'')
            
    return text

remove_puctuation('hi ! how are you ?')

'hi  how are you '

In [ ]:
# optimised code using vectorisatuib u

In [ ]:
import pandas as pd
import string

# Create translation table
translator = str.maketrans('', '', string.punctuation)

# Apply it using vectorized str method
df['review'] = df['review'].str.translate(translator)

In [ ]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically there is a family where a little boy...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    I am going to have to disagree with the previo...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

In [ ]:
# social media slangs like gn = good night
# inka koi file apko mil gaya google ya github ka
# aap ek project bano aor usa open source kar do 
# kuch bhi loophole mila usa use karo
# hamesa download nahi kabhi upload bhi karo.

### remove special characters
koi emoji wagara hota ,usko remove karna ya koi aor bhasa ko hota

In [ ]:
# 90 percent nlp projects ma apko yahi cleaning karni padti ha

# Preprocessing

## tokenization 
string ko list of string ma convert karaga

two types of tokization
- word level
- sentence level

In [ ]:
import nltk
print(nltk.__version__)

3.9.1

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sumit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
import nltk
print(nltk.data.path)

['C:\\Users\\sumit/nltk_data', 'c:\\Users\\sumit\\miniconda3\\envs\\my_env\\nltk_data', 'c:\\Users\\sumit\\miniconda3\\envs\\my_env\\share\\nltk_data', 'c:\\Users\\sumit\\miniconda3\\envs\\my_env\\lib\\nltk_data', 'C:\\Users\\sumit\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data', 'C:\\Users\\sumit/AppData/Roaming/nltk_data']

In [ ]:
text = "NLP is transforming the way we interact with computers!"
tokens = word_tokenize(text= text)
print(tokens)

In [ ]:
import nltk
import os
nltk.data.path.append(os.path.expanduser('~/AppData/Roaming/nltk_data'))
nltk.download('punkt')

from nltk.tokenize import word_tokenize

text = "NLP is transforming the way we interact with computers!"
tokens = word_tokenize(text)
print(tokens)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sumit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\sumit/nltk_data'
    - 'c:\\Users\\sumit\\miniconda3\\envs\\my_env\\nltk_data'
    - 'c:\\Users\\sumit\\miniconda3\\envs\\my_env\\share\\nltk_data'
    - 'c:\\Users\\sumit\\miniconda3\\envs\\my_env\\lib\\nltk_data'
    - 'C:\\Users\\sumit\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Users\\sumit/AppData/Roaming/nltk_data'
**********************************************************************

In [ ]:
import nltk
nltk.download('punkt')  # Step to avoid LookupError

# from nltk.tokenize import word_tokenize
# df['tokens'] = df['review'].apply(word_tokenize)

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

False

In [ ]:
from nltk.tokenize import word_tokenize
#df['review'].apply(word_tokenize)

ModuleNotFoundError: No module named 'nltk'

In [ ]:
import nltk
nltk.download('punkt')  # Download it cleanly

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sumit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
import os
import nltk

# Set correct data path manually
nltk.data.path.append(os.path.expanduser('~/AppData/Roaming/nltk_data'))

from nltk.tokenize import word_tokenize

# Now use it
df['tokens'] = df['review'].apply(word_tokenize)

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\sumit/nltk_data'
    - 'c:\\Users\\sumit\\miniconda3\\envs\\my_env\\nltk_data'
    - 'c:\\Users\\sumit\\miniconda3\\envs\\my_env\\share\\nltk_data'
    - 'c:\\Users\\sumit\\miniconda3\\envs\\my_env\\lib\\nltk_data'
    - 'C:\\Users\\sumit\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Users\\sumit/AppData/Roaming/nltk_data'
**********************************************************************

## remove stopwords