In [1]:
# today session is very important because today you learn you can apply in every dataset whenever you have textual data. 
# example movie ka description ya customers ka review par kam kar raha ho 
# aap logo ka whatsup chat ko analysis kar raha ho 

# if you know string in python this season is very helful on it

In [2]:
# topic name is vectorized string operation 
# basic funda is pandas use karka vector operation use kar sakta strings par 
#

# what is vectorized operation

In [3]:
import numpy as np 
import pandas as pd 
an_array = np.array([1,2,3,4])
an_array + 10

array([11, 12, 13, 14])

In [4]:
# apka pass ek vector tha apna us par ek operation chalya
# aor vo vector ka har ek element par ho gaya
# yahi hota ha vectorisation

In [5]:
# apka paas ek dataset hoga 
# uska andr ek string coloumn hoga .
# apko ek operation chalan ha jo har ek row par apply ho jaya.

In [6]:
# normal python 
a_string = ['cat','rat','mat']
ls = []
for i in a_string:
    ls.append(i.startswith('c'))
ls

[True, False, False]

In [7]:
# list comprehension code 
[i.startswith('c') for i in a_string]

[True, False, False]

In [8]:
# what happen if their is some none value in it
a_string = ['cat','rat',None,'mat']
#[i.startswith('c') for i in a_string]

promblems 
1. yahi problem ha ki agar apka python list ma none ya missing value ha tho vo python handle nahi kar pata 
2. list compreshension are slow

In [9]:
# so pandas decided we created our on string functions for if you want to handle string(text) in large dataset.
# pandas is built on numpy
# and numpy built on c
# tho speed c sa aa raha ha

In [10]:
# how pandas solves the issue 
a_string = pd.Series(['cat','rat',None,'mat'])
# string operation 
a_string.str.startswith('c')
# str --> ek accessor jissa aap sara string operation ko extract kar sakta ho

0     True
1    False
2     None
3    False
dtype: object

In [11]:
# it is fast and optimized

In [12]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

# common function

### lower/upper/capitalisze/title

In [14]:
# aap apna passenger ka name ko capital ma karna chata ho 
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [15]:
df['Name'].str.upper()
# upper each letter in the word

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: object

In [16]:
df['Name'].str.lower()
# lower each letter in the word

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [17]:
df['Name'].str.title()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

### len

In [18]:
# muja vo passeneger nikalan ha jiska name sabasa bada ha 
df['Name'].str.len()
# 1st passenger name maa 23 charcters.
df['Name'].str.len().max()

82

In [19]:
df[df['Name'].str.len() == 82]['Name'].values[0]

'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'

In [20]:
#ho sakta ha gali sa spaces jo ha wo name ma add ho gaya
# usna type kar diya aor wo add ho gaya database ma
# before 
'       focus      '

'       focus      '

### strip

In [21]:
# after 
'       focus      '.strip()
# trailing spaces hatana ka liya

'focus'

In [22]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

### split-get

In [23]:
# so now we have to make three coloumns 
# first name 
# surname
# title(Mr. Mrs.)

df['Name'].str.split(',')
# comma ka baad firstname and surname ha 
# hamana split kar diya uska name surname alg ho gaya
# promblem vo list ban gaya tho how we fetch the first item in it
df['Name'].str.split(',').str.get(0) # first name 
df['Name'].str.split(',').str.get(1) # sur name

0                                  Mr. Owen Harris
1       Mrs. John Bradley (Florence Briggs Thayer)
2                                      Miss. Laina
3               Mrs. Jacques Heath (Lily May Peel)
4                                Mr. William Henry
                          ...
886                                    Rev. Juozas
887                           Miss. Margaret Edith
888                 Miss. Catherine Helen "Carrie"
889                                Mr. Karl Howell
890                                    Mr. Patrick
Name: Name, Length: 891, dtype: object

In [24]:
df['lastname']= df['Name'].str.split(',').str.get(0)

In [25]:
# always remember yadi apko sabhi rows par string operation lagan ha than use str accesssor

In [26]:
df['Name'].str.split(',').str.get(1).str.split(' ')
# promblem their is spaces in between

0                                  [, Mr., Owen, Harris]
1      [, Mrs., John, Bradley, (Florence, Briggs, Tha...
2                                       [, Miss., Laina]
3            [, Mrs., Jacques, Heath, (Lily, May, Peel)]
4                                [, Mr., William, Henry]
                             ...
886                                     [, Rev., Juozas]
887                           [, Miss., Margaret, Edith]
888                [, Miss., Catherine, Helen, "Carrie"]
889                                [, Mr., Karl, Howell]
890                                     [, Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [27]:
df['Name'].str.split(',').str.get(1).str.strip().str.split(' ')
# now kisika name Mr. Owen Harris ha tho split ho raha 
#[Mr., Owen, Harris]
# yani combined word hona tha lakin wo two words ma split ho gaya

0                                    [Mr., Owen, Harris]
1      [Mrs., John, Bradley, (Florence, Briggs, Thayer)]
2                                         [Miss., Laina]
3              [Mrs., Jacques, Heath, (Lily, May, Peel)]
4                                  [Mr., William, Henry]
                             ...
886                                       [Rev., Juozas]
887                             [Miss., Margaret, Edith]
888                  [Miss., Catherine, Helen, "Carrie"]
889                                  [Mr., Karl, Howell]
890                                       [Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [28]:
# again split on the basis of space 
# very good use of brain split on the basis of dot 
df['Name'].str.split(',').str.get(1).str.strip().str.split('.')
# n yani kitni baar split karna 
# n= 1 phala space par split hoga
# n= 2 dursa space par split hoga 
df['Name'].str.split(',').str.get(1).str.strip().str.split(' ',n=1)

0                                 [Mr., Owen Harris]
1      [Mrs., John Bradley (Florence Briggs Thayer)]
2                                     [Miss., Laina]
3              [Mrs., Jacques Heath (Lily May Peel)]
4                               [Mr., William Henry]
                           ...
886                                   [Rev., Juozas]
887                          [Miss., Margaret Edith]
888                [Miss., Catherine Helen "Carrie"]
889                               [Mr., Karl Howell]
890                                   [Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [29]:
df['Name'].str.split(',').str.get(1).str.strip().str.split(' ',n=1,expand=True)
# it created the dataframe by expand_true parameter

         0                                      1
0      Mr.                            Owen Harris
1     Mrs.  John Bradley (Florence Briggs Thayer)
2    Miss.                                  Laina
3     Mrs.          Jacques Heath (Lily May Peel)
4      Mr.                          William Henry
..     ...                                    ...
886   Rev.                                 Juozas
887  Miss.                         Margaret Edith
888  Miss.               Catherine Helen "Carrie"
889    Mr.                            Karl Howell
890    Mr.                                Patrick

[891 rows x 2 columns]

In [30]:
# now create a dataframe 
df[['title','firstname']]= df['Name'].str.split(',').str.get(1).str.strip().str.split(' ',n=1,expand=True)

In [31]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,title,firstname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry

In [32]:
# kitna mr and kitna miss ha 
df['title'].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Mlle.          2
Major.         2
Col.           2
the            1
Capt.          1
Ms.            1
Sir.           1
Lady.          1
Mme.           1
Don.           1
Jonkheer.      1
Name: count, dtype: int64

### replace
ya replace karta ha ek string ko dursa string ma

In [33]:
# so Miss. and Ms. are same
# also Mile. jo ha french ma bola ha uskma matalab Miss. hi ha
df['title'] = df['title'].str.replace('Ms.',"Miss.")
df['title'] = df['title'].str.replace('Mlle.',"Miss.")

In [34]:
df['title'].value_counts()

title
Mr.          517
Miss.        185
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Col.           2
Don.           1
Mme.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

# filtering

### startwith/endwith

In [37]:
# aap filter kar sakta ho string ma
# returns --> boolean series 
df['firstname'].str.startswith('A') 
df[df['firstname'].str.startswith('A') ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,title,firstname
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,Andersson,Mr.,Anders Johan
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q,McGowan,Miss.,"Anna ""Annie"""
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S,Holverson,Mr.,Alexander Oskar
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S,Vander Planke,Miss.,Augusta Maria
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN,Icard,Miss.,Amelie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842,843,1,1,"Serepeca, Miss. Augusta",female,30.0,0,0,113798,31.0000,NaN,C,Serepeca,Miss.,Augusta
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,NaN,S,Abbing,Mr.,Anthony
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C,Duran y More,Miss.,Asuncion
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,Najib,Miss.,"Adele Kiamie ""Jane"""
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S,Gustafsson,Mr.,Alfred Ossian

In [40]:
df['firstname'].str.endswith('b')
df[df['firstname'].str.endswith('b')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,title,firstname
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,Emir,Mr.,Farred Chehab
668,669,0,3,"Cook, Mr. Jacob",male,43.0,0,0,A/5 3536,8.0500,NaN,S,Cook,Mr.,Jacob
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S,Pasic,Mr.,Jakob

### isdigit/isalpha...

In [ ]:
# kiya string ma digit ha 
df['lastname'].str.isdigit()
df[df['lastname'].str.isdigit()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, lastname, title, firstname]
Index: []

In [ ]:
# ya ho gaya basic level filtering 
# aap advance level filtering bhi kar sakta ho .
# regex are complex pattern jis sa aap string ma searching kar sakta ho .

# apply regex

ya bhi filtering karna ha tarika ha string ma by pattern of string

In [ ]:
# huma vo passenger chaya jinka name ma 'john' ata ha 
# john capital or small letter bhi chalaga
df['firstname'].str.contains('john')
df[df['firstname'].str.contains('john',case=False)]
# capital small dono chalega

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,title,firstname
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S,Turpin,Mrs.,William John Robert (Dorothy Ann Wonnacott)
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S,Rogers,Mr.,William John
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S,Doling,Mrs.,John T (Ada Julia Bone)
112,113,0,3,"Barton, Mr. David John",male,22.0,0,0,324669,8.0500,NaN,S,Barton,Mr.,David John
117,118,0,2,"Turpin, Mr. William John Robert",male,29.0,1,0,11668,21.0000,NaN,S,Turpin,Mr.,William John Robert
160,161,0,3,"Cribb, Mr. John Hatfield",male,44.0,0,1,371362,16.1000,NaN,S,Cribb,Mr.,John Hatfield
162,163,0,3,"Bengtsson, Mr. John Viktor",male,26.0,0,0,347068,7.7750,NaN,S,Bengtsson,Mr.,John Viktor
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.5250,NaN,S,Goldsmith,Master.,"Frank John William ""Frankie"""
168,169,0,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,Baumann,Mr.,John D
188,189,0,3,"Bourke, Mr. John",male,40.0,1,1,364849,15.5000,NaN,Q,Bourke,Mr.,John
212,213,0,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.2500,NaN,S,Perkin,Mr.,John Henry
226,227,1,2,"Mellors, Mr. William John",male,19.0,0,0,SW/PP 751,10.5000,NaN,S,Mellors,Mr.,William John
227,228,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.2500,NaN,S,Lovell,Mr.,"John Hall (""Henry"")"
324,325,0,3,"Sage, Mr. George John Jr",male,NaN,8,2,CA. 2343,69.5500,NaN,S,Sage,Mr.,George John Jr
328,329,1,3,"Goldsmith, Mrs. Frank John (Emily Alice Brown)",female,31.0,1,1,363291,20.5250,NaN,S,Goldsmith,Mrs.,Frank John (Emily Alice Brown)
401,402,0,3,"Adams, Mr. John",male,26.0,0,0,341826,8.0500,NaN,S,Adams,Mr.,John
418,419,0,2,"Matthews, Mr. William John",male,30.0,0,0,28228,13.0000,NaN,S,Matthews,Mr.,William John
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S,Smart,Mr.,John Montgomery
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,Farthing,Mr.,John
548,549,0,3,"Goldsmith, Mr. Frank John",male,33.0,1,1,363291,20.5250,NaN,S,Goldsmith,Mr.,Frank John
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.0,1,1,C.A. 33112,36.7500,NaN,S,Davies,Master.,John Morgan Jr
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.0,0,2,17421,110.8833,C70,C,Thayer,Mr.,John Borland Jr
563,564,0,3,"Simmons, Mr. John",male,NaN,0,0,SOTON/OQ 392082,8.0500,NaN,S,Simmons,Mr.,John
572,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.0,0,0,PC 17474,26.3875,E25,S,Flynn,Mr.,"John Irwin (""Irving"")"
574,575,0,3,"Rush, Mr. Alfred George John",male,16.0,0,0,A/4. 20589,8.0500,NaN,S,Rush,Mr.,Alfred George John
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.0,1,1,17421,110.8833,C68,C,Thayer,Mrs.,John Borland (Marian Longstreth Morris)
583,584,0,1,"Ross, Mr. John Hugo",male,36.0,0,0,13049,40.1250,A10,C,Ross,Mr.,John Hugo
586,587,0,2,"Jarvis, Mr. John Denzil",male,47.0,0,0,237565,15.0000,NaN,S,Jarvis,Mr.,John Denzil
594,595,0,2,"Chapman, Mr. John Henry",male,37.0,1,0,SC/AH 29037,26.0000,NaN,S,Chapman,Mr.,John Henry
613,614,0,3,"Horgan, Mr. John",male,NaN,0,0,370377,7.7500,NaN,Q,Horgan,Mr.,John
624,625,0,3,"Bowen, Mr. David John ""Dai""",male,21.0,0,0,54636,16.1000,NaN,S,Bowen,Mr.,"David John ""Dai"""
657,658,0,3,"Bourke, Mrs. John (Catherine)",female,32.0,1,1,364849,15.5000,NaN,Q,Bourke,Mrs.,John (Catherine)
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S,Weir,Col.,John
698,699,0,1,"Thayer, Mr. John Borland",male,49.0,1,1,17421,110.8833,C68,C,Thayer,Mr.,John Borland
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,Astor,Mrs.,John Jacob (Madeleine Talmadge Force)
733,734,0,2,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,NaN,S,Berriman,Mr.,William John
760,761,0,3,"Garfirth, Mr. John",male,NaN,0,0,358585,14.5000,NaN,S,Garfirth,Mr.,John
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S,Hogeboom,Mrs.,John C (Anna Andrews)
818,819,0,3,"Holm, Mr. John Fredrik Alexander",male,43.0,0,0,C 7075,6.4500,NaN,S,Holm,Mr.,John Fredrik Alexander
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S,Reuchlin,Jonkheer.,John George
825,826,0,3,"Flynn, Mr. John",male,NaN,0,0,368323,6.9500,NaN,Q,Flynn,Mr.,John
848,849,0,2,"Harper, Rev. John",male,28.0,0,1,248727,33.0000,NaN,S,Harper,Rev.,John
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S,Gill,Mr.,John William

### find last names with start and end char vowel

In [50]:
# aapko vo person chaya jinka first name and last name vowel sa start or end hota ha
df['lastname'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$')
df[df['lastname'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,title,firstname
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C,Uruchurtu,Don.,Manuel E
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mrs.,Josef (Josefine Franchi)
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,NaN,C,Albimona,Mr.,Nassef Cassem
210,211,0,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S,Ali,Mr.,Ahmed
353,354,0,3,"Arnold-Franchi, Mr. Josef",male,25.0,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mr.,Josef
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,Artagaveytia,Mr.,Ramon
518,519,1,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.0,1,0,226875,26.0000,NaN,S,Angle,Mrs.,"William A (Florence ""Mary"" Agnes Hughes)"
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S,Ali,Mr.,William
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,Alhomaki,Mr.,Ilmari Rudolf

In [ ]:
# ek bar aap regular expression sik gaya 
# tho aap apna program ma kitna bhi complex Query search kar sakta ho .
# muja vo sara rows nikal kar batao jaha phone number ha
# vo rows nikalo jinma url ho 
#

# slicing

In [51]:
# har name ka 4 character chaya 
df['Name'].str[:4]

0      Brau
1      Cumi
2      Heik
3      Futr
4      Alle
       ...
886    Mont
887    Grah
888    John
889    Behr
890    Dool
Name: Name, Length: 891, dtype: object

In [53]:
# last character of every name
df['Name'].str[-1]

0      s
1      )
2      a
3      )
4      y
      ..
886    s
887    h
888    "
889    l
890    k
Name: Name, Length: 891, dtype: object

In [ ]:
# you can do reverse a string 
# and you check the symmetry of the string .
df['Name'].str[::-1]

0                                sirraH newO .rM ,dnuarB
1      )reyahT sggirB ecnerolF( yeldarB nhoJ .srM ,sg...
2                                 aniaL .ssiM ,nenikkieH
3           )leeP yaM yliL( htaeH seuqcaJ .srM ,ellertuF
4                               yrneH mailliW .rM ,nellA
                             ...
886                                sazouJ .veR ,alivtnoM
887                         htidE teragraM .ssiM ,maharG
888             "eirraC" neleH enirehtaC .ssiM ,notsnhoJ
889                                llewoH lraK .rM ,rheB
890                                  kcirtaP .rM ,yelooD
Name: Name, Length: 891, dtype: object