# What is Dash 
Dash isa python framework for building web application .

## how dash is built 
- it is built on top of flask , plotly.js,react

aap ek dashborad bana sakta ho jo sidha database sa connect ho and interactive way sa us sa interact kar sakta ho

making apps in dash like Data analysis + web devlopment

## two important fundamental parts in dash
- dash html components -> using which we can create and design web page . agar apko dashn html copmoents ata ha then no need to learn the html and css 
- dash core components -> inki helps sa aap interactive dashborad banta ha . example dropdown ,sidebar ,buttons etc.

## write hello world

In [ ]:
from dash import Dash, html

app = Dash()

# Requires Dash 2.17.0 or later
app.layout = [html.Div(children='Hello World')]

if __name__ == '__main__':
    app.run(debug=True)

In [ ]:
# logic behind code and breakdown of it 

# Import packages
from dash import Dash, html

# Initialize the app
app = Dash()
# we create a variable name app ans store the dash class in it.
# issa dash constructore vo responsible ha intinialsing the app ka liya

# App layout
app.layout = [html.Div(children='Hello World')]

# fir app ka andr sa ek methods proprtly ko call kara 
# The app layout represents the app components that will be displayed in the web browser 
# and here is provided as a list, though it could also be a Dash component.
# In this example, a single component was added to the list: an html.Div. The Div has a few properties, such as children, which we use to add text content to the page: "Hello World".
# Run the app
if __name__ == '__main__':
    app.run(debug=True)
    
# python file ka name of internally __main__ bhulta ha .

In [ ]:
# import all library 

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from dash import Dash, html, dash_table

# import the gapminder dataset . 
data = px.data.gapminder()

# intialse the app
app = Dash()

# make layout of the app
app.layout = html.H1(
    children='My first Dashborad',
    style= {'color': 'red'}
    )

# Run the app 
if __name__ == '__main__':
    app.run(debug=True)

In [2]:
import dash
print(dash.__version__)

3.1.1

## import the dataset

In [ ]:
# import all library 

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

from dash import Dash, html, dash_table


# Incorporate data
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv')

# Initialize the app
app = Dash()

# App layout
app.layout = [
    html.Div(children='My First App with Data'),
    dash_table.DataTable(data=df.to_dict('records'), page_size=10)
]

# Run the app
if __name__ == '__main__':
    app.run(debug=True)

In [ ]:
# import all library 

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

from dash import Dash, html, dash_table


# Incorporate data
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv')

# Initialize the app
app = Dash()

# App layout
app.layout = html.Div([
    html.Div(), # heading 
    html.Div(), # first graph 
    html.Div(),  # seconda graph 
])

# Run the app
if __name__ == '__main__':
    app.run(debug=True)

In [ ]:
# import all library 

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

from dash import Dash, html, dash_table


# Incorporate data
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv')

# Initialize the app
app = Dash()

# App layout
app.layout = html.Div([
    html.Div(style={'border': '1px black solid','float': 'left','width': '100%','height': '50px'}), # heading 
    html.Div(style={'border': '1px black solid','float': 'left','width': '49%','height': '350px'}), # first graph 
    html.Div(style={'border': '1px black solid','float': 'left','width': '49%','height': '350px'}),  # seconda graph 
])

# Run the app
if __name__ == '__main__':
    app.run(debug=True)

In [1]:
import pandas as pd
df = df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv')
df

                country         pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923.0      Asia   43.828    974.580338
1               Albania   3600523.0    Europe   76.423   5937.029526
2               Algeria  33333216.0    Africa   72.301   6223.367465
3                Angola  12420476.0    Africa   42.731   4797.231267
4             Argentina  40301927.0  Americas   75.320  12779.379640
..                  ...         ...       ...      ...           ...
137             Vietnam  85262356.0      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332.0      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743.0      Asia   62.698   2280.769906
140              Zambia  11746035.0    Africa   42.384   1271.211593
141            Zimbabwe  12311143.0    Africa   43.487    469.709298

[142 rows x 5 columns]

In [2]:
df.columns

Index(['country', 'pop', 'continent', 'lifeExp', 'gdpPercap'], dtype='object')

## draw chart

In [ ]:
import pandas as pd
import plotly.express as px
from dash import Dash, html, dcc

# Load data
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv')

# Initialize the app
app = Dash(__name__)

# Create figures
scatter_fig = px.scatter(
    df, 
    x='gdpPercap', 
    y='lifeExp',
    color='continent',
    hover_name='country',
    title='GDP Per Capita vs Life Expectancy'
)

box_fig = px.box(
    df,
    y='lifeExp',
    x='continent',
    color='continent',
    title='Life Expectancy by Continent'
)

# App layout
app.layout = html.Div([
    html.Div(
        children=[
            html.H1('My First Dashboard', style={'color': 'red', 'textAlign': 'center'})
        ],
        style={
            'border': '1px black solid',
            'width': '100%',
            'height': '50px'
        }
    ),
    html.Div([
        html.Div(
            children=[dcc.Graph(figure=scatter_fig)],
            style={'border': '1px black solid', 'float': 'left', 'width': '49%', 'height': '400px'}
        ),
        html.Div(
            children=[dcc.Graph(figure=box_fig)],
            style={'border': '1px black solid', 'float': 'left', 'width': '49%', 'height': '400px'}
        )
    ])
])

# Run the app
if __name__ == '__main__':
    app.run(debug=True)

# covid 19 Dashborad

In [3]:
covid_df = pd.read_csv('covid_19_india.csv')
covid_df.head()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,30/01/20,6:00 PM,Kerala,1,0,0,0,1
1,2,31/01/20,6:00 PM,Kerala,1,0,0,0,1
2,3,01/02/20,6:00 PM,Kerala,2,0,0,0,2
3,4,02/02/20,6:00 PM,Kerala,3,0,0,0,3
4,5,03/02/20,6:00 PM,Kerala,3,0,0,0,3

In [ ]:
import numpy as np 
import pandas as pd
import plotly.graph_objects as go

from dash import dash,html,dcc ,Input,Output


# external csss style sheets 
external_stylesheets = [
    {
        'href': 'https://stackpath.bootstraphcdn.com/4.1.3/css/bootstrap.min.css',
        'rel' : 'stylesheet',
        'integrity': 'sha384-uCw98/SfnGE*ft3GXwEOngsV77t27NXFoao4pmYm81iuXoPkF)jBERdknLPMO',
        'crossorigin': 'anonymous'
    }
]

app = dash.Dash__name_external_stylesheets = external_stylesheets


if __name__ == '__main__':
    app.run(debug = True)

## Layout planning 
dash have two main compoent 
- html = for writing content 
- dcc = dash core componet for design and function = it is combination of css ,javascript

In [ ]:
# so example in website and web page
# example in a web page
# left side photo and right side some text
# so basically you add two div 
# har div ka andr uska information dala ga

In [ ]:
# lakin core css ma webiste bana mushkil hota ha tho we use
# bootstrap 
# which divide your website into 12 equal parts .
# so we make a outer div jiska name hoga container. 

# so we have 3 rows
# first row 4 elements means 4 div  
# 4 important metrices 
# seocnd row 2 elements 3 charts pie and 
# 2 plots left line right pie chart
# third row 
# bar chart

## dashborad architrue 
- container = div 
    - first row have 4 div
        1. div = col md 3 
        2. div = col md 3 
        3. div = col md 3 
        4. div = col md 3 
    - second row have 2 div 
        1. div = col md 6
        2. div = col md 6 
    - third row have 1 div 
        1. div = col md 12

## dashborad design
- wireframing protoypeing of it
- heading = CoronaVirus - india persective
- container = div 
    - first row has 4 important metrices 
        1. total cases 
        2. active cases 
        3. Recovered  
        4. deathes 
    - second row has two important plots 
        1. line chart 
        2. pie chart 
    - third row  main graph 
        1.  bar graph

## 3 rows

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from dash import Dash, html, dcc, Input, Output

# External CSS stylesheet
external_stylesheets = [
    {
        'href': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',
        'rel': 'stylesheet',
        'integrity': 'sha384-uCw98/SfnGE*ft3GXwEOngsV77t27NXFoao4pmYm81iuXoPkF)jBERdknLPMO',
        'crossorigin': 'anonymous'
    }
]

app = Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    html.Div([],className='row'),
    html.Div([],className='row'),
    html.Div([],className='row'),
    html.Div([],className='row')
    
], className='container')

if __name__ == '__main__':
    app.run(debug=True)

## make first div

### write structure of 4 div

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from dash import Dash, html, dcc, Input, Output

# External CSS stylesheet
external_stylesheets = [
    {
        'href': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',
        'rel': 'stylesheet',
        'integrity': 'sha384-uCw98/SfnGE*ft3GXwEOngsV77t27NXFoao4pmYm81iuXoPkF)jBERdknLPMO',
        'crossorigin': 'anonymous'
    }
]

app = Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    html.H1("Covid-19 Virus Dashboard",style={'color': 'white', 'text-align': 'center'}),
    
    html.Div([
        html.Div([
            html.Div([],className='card')
        ],className='col-md-3'),
        html.Div([],className='col-md-3'),
        html.Div([],className='col-md-3'),
        html.Div([],className='col-md-3'),
        
        ],className='row'),
    html.Div([],className='row'),
    html.Div([],className='row'),
    
    
], className='container')

if __name__ == '__main__':
    app.run(debug=True)

### first card metric 
make the red color

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from dash import Dash, html, dcc, Input, Output

# External CSS stylesheet
external_stylesheets = [
    {
        'href': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',
        'rel': 'stylesheet',
        'integrity': 'sha384-uCw98/SfnGE*ft3GXwEOngsV77t27NXFoao4pmYm81iuXoPkF)jBERdknLPMO',
        'crossorigin': 'anonymous'
    }
]

app = Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    html.H1("Covid-19 Virus Dashboard",style={'color': 'white', 'text-align': 'center'}),
    
    html.Div([
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Total Cases'),
                    html.H4('600')
                    ],className='card-body')
                ], className='card bg-danger')
        ],className='col-md-3'),
        html.Div([],className='col-md-3'),
        html.Div([],className='col-md-3'),
        html.Div([],className='col-md-3'),
        
        ],className='row'),
    html.Div([],className='row'),
    html.Div([],className='row'),
    
    
], className='container')

if __name__ == '__main__':
    app.run(debug=True)

### all four

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from dash import Dash, html, dcc, Input, Output

# External CSS stylesheet
external_stylesheets = [
    {
        'href': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',
        'rel': 'stylesheet',
        'integrity': 'sha384-uCw98/SfnGE*ft3GXwEOngsV77t27NXFoao4pmYm81iuXoPkF)jBERdknLPMO',
        'crossorigin': 'anonymous'
    }
]

app = Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    html.H1("Covid-19 Virus Dashboard",style={'color': 'white', 'text-align': 'center'}),
    
    html.Div([
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Total Cases',className='text-light'),
                    html.H4('600',className='text-light')
                    ],className='card-body')
                ], className='card bg-danger')
        ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Total Cases',className='text-light'),
                    html.H4('600',className='text-light')
                    ],className='card-body')
                ], className='card bg-info')
            ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Total Cases',className='text-light'),
                    html.H4('600',className='text-light')
                    ],className='card-body')
                ], className='card bg-warning')
            ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Total Cases',className='text-light'),
                    html.H4('600',className='text-light')
                    ],className='card-body')
                ], className='card bg-success')
            ],className='col-md-3'),
        
        ],className='row'),
    html.Div([],className='row'),
    html.Div([],className='row'),
    
    
], className='container')

if __name__ == '__main__':
    app.run(debug=True)

## Data Analysis

In [1]:
import pandas as pd
patients_df = pd.read_csv('covid_19_india.csv')
patients_df

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,30/01/20,6:00 PM,Kerala,1,0,0,0,1
1,2,31/01/20,6:00 PM,Kerala,1,0,0,0,1
2,3,01/02/20,6:00 PM,Kerala,2,0,0,0,2
3,4,02/02/20,6:00 PM,Kerala,3,0,0,0,3
4,5,03/02/20,6:00 PM,Kerala,3,0,0,0,3
...,...,...,...,...,...,...,...,...,...
921,922,13/04/20,5:00 PM,Telengana,-,-,100,16,562
922,923,13/04/20,5:00 PM,Tripura,-,-,0,0,2
923,924,13/04/20,5:00 PM,Uttarakhand,-,-,5,0,35
924,925,13/04/20,5:00 PM,Uttar Pradesh,-,-,47,5,483
925,926,13/04/20,5:00 PM,West Bengal,-,-,29,7,152

In [2]:
patients_df.columns

Index(['Sno', 'Date', 'Time', 'State/UnionTerritory',
       'ConfirmedIndianNational', 'ConfirmedForeignNational', 'Cured',
       'Deaths', 'Confirmed'],
      dtype='object')

In [ ]:
# total cases = confirm nation 
# confiremd = 
# recovered 
# death .

In [ ]:
# hospitalised = active cases 
# recovered =  cured 
# diased  = death 
# confirmed = confiremd

In [17]:
import plotly.express as px
state_df = patients_df.groupby('State/UnionTerritory')['Confirmed'].sum().sort_values(ascending=False).reset_index()
state_df

           State/UnionTerritory  Confirmed
0                   Maharashtra      14152
1                         Delhi       8502
2                    Tamil Nadu       8436
3                        Kerala       5964
4                     Rajasthan       5188
5                     Telengana       4945
6                 Uttar Pradesh       4678
7                Madhya Pradesh       3519
8                Andhra Pradesh       3517
9                       Gujarat       3125
10                    Karnataka       2820
11            Jammu and Kashmir       1967
12                      Haryana       1935
13                       Punjab       1539
14                  West Bengal       1340
15                        Bihar        598
16                       Odisha        417
17                  Uttarakhand        386
18                       Ladakh        385
19                   Chandigarh        313
20                        Assam        297
21             Himachal Pradesh        236
22                 Chhattisgarh        216
23  Andaman and Nicobar Islands        171
24                   Unassigned        161
25                          Goa        110
26                    Jharkhand        100
27                   Puducherry         81
28                      Manipur         32
29                      Mizoram         20
30            Arunachal Pradesh         11
31                      Tripura         10
32                     Nagaland          1

In [13]:
type(state_df)

pandas.core.frame.DataFrame

In [18]:
px.histogram(data_frame=state_df,x=state_df['State/UnionTerritory'],y=state_df['Confirmed'])

In [ ]:
patients_df.value_counts()

Confirmed
1      140
3       81
2       52
7       40
4       27
      ...
411      1
295      1
105      1
445      1
483      1
Name: count, Length: 220, dtype: int64

In [38]:
patients_df.columns

Index(['Sno', 'Date', 'Time', 'State/UnionTerritory',
       'ConfirmedIndianNational', 'ConfirmedForeignNational', 'Cured',
       'Deaths', 'Confirmed'],
      dtype='object')

In [35]:
state_df = patients_df.groupby('State/UnionTerritory')['Deaths'].sum().sort_values(ascending=False).reset_index()
state_df

           State/UnionTerritory  Deaths
0                   Maharashtra     847
1                Madhya Pradesh     221
2                       Gujarat     210
3                         Delhi     146
4                        Punjab     109
5                     Telengana      99
6                     Karnataka      85
7                    Tamil Nadu      76
8                   West Bengal      62
9             Jammu and Kashmir      44
10               Andhra Pradesh      43
11                Uttar Pradesh      41
12                       Kerala      30
13                        Bihar      23
14                    Rajasthan      21
15             Himachal Pradesh      21
16                      Haryana      21
17                       Odisha       7
18                    Jharkhand       5
19                        Assam       3
20                      Tripura       0
21                   Unassigned       0
22                  Uttarakhand       0
23  Andaman and Nicobar Islands       0
24                   Puducherry       0
25                     Nagaland       0
26                      Mizoram       0
27                      Manipur       0
28                          Goa       0
29                 Chhattisgarh       0
30                   Chandigarh       0
31            Arunachal Pradesh       0
32                       Ladakh       0

In [37]:
px.histogram(data_frame=state_df,x=state_df['State/UnionTerritory'],y=state_df['Deaths'])

In [ ]:
# total = total 
# recovered =  cured 
# diased  = death 
# confirmed = confiremd  = active cases

In [ ]:
# total patients 
total = patients_df.shape[0]
total

In [ ]:
# active cases 
active_cases = patients_df['Confirmed'].sum()
active_cases

75172

In [ ]:
# Recovered cases 
recovered_cases = patients_df['Cured'].sum()
recovered_cases

6234

In [28]:
# death cases 
death_cases = patients_df['Deaths'].sum()
death_cases

2114

In [ ]:
total = patients_df.shape[0]
active_cases = patients_df['Confirmed'].sum()
recovered_cases = patients_df['Cured'].sum()
death_cases = patients_df['Deaths'].sum()

In [ ]:
patients_df['Sno']

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,30/01/20,6:00 PM,Kerala,1,0,0,0,1
1,2,31/01/20,6:00 PM,Kerala,1,0,0,0,1
2,3,01/02/20,6:00 PM,Kerala,2,0,0,0,2
3,4,02/02/20,6:00 PM,Kerala,3,0,0,0,3
4,5,03/02/20,6:00 PM,Kerala,3,0,0,0,3
...,...,...,...,...,...,...,...,...,...
921,922,13/04/20,5:00 PM,Telengana,-,-,100,16,562
922,923,13/04/20,5:00 PM,Tripura,-,-,0,0,2
923,924,13/04/20,5:00 PM,Uttarakhand,-,-,5,0,35
924,925,13/04/20,5:00 PM,Uttar Pradesh,-,-,47,5,483
925,926,13/04/20,5:00 PM,West Bengal,-,-,29,7,152

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from dash import Dash, html, dcc, Input, Output

# External CSS stylesheet
external_stylesheets = [
    {
        'href': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',
        'rel': 'stylesheet',
        'integrity': 'sha384-uCw98/SfnGE*ft3GXwEOngsV77t27NXFoao4pmYm81iuXoPkF)jBERdknLPMO',
        'crossorigin': 'anonymous'
    }
]

patients_df = pd.read_csv('covid_19_india.csv')
active_cases = patients_df['Confirmed'].sum()
recovered_cases = patients_df['Cured'].sum()
death_cases = patients_df['Deaths'].sum()
total = active_cases + death_cases + recovered_cases


app = Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    html.H1("Covid-19 Virus Dashboard",style={'color': 'white', 'text-align': 'center'}),
    
    html.Div([
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Total Cases',className='text-light'),
                    html.H4(total,className='text-light')
                    ],className='card-body')
                ], className='card bg-danger')
        ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Active Cases',className='text-light'),
                    html.H4(active_cases,className='text-light')
                    ],className='card-body')
                ], className='card bg-info')
            ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Recovered',className='text-light'),
                    html.H4(recovered_cases,className='text-light')
                    ],className='card-body')
                ], className='card bg-warning')
            ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Deaths',className='text-light'),
                    html.H4(death_cases,className='text-light')
                    ],className='card-body')
                ], className='card bg-success')
            ],className='col-md-3'),
        
        ],className='row'),
    html.Div([],className='row'),
    html.Div([],className='row'),
    
    
], className='container')

if __name__ == '__main__':
    app.run(debug=True)

### create third row

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from dash import Dash, html, dcc, Input, Output

# External CSS stylesheet
external_stylesheets = [
    {
        'href': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',
        'rel': 'stylesheet',
        'integrity': 'sha384-uCw98/SfnGE*ft3GXwEOngsV77t27NXFoao4pmYm81iuXoPkF)jBERdknLPMO',
        'crossorigin': 'anonymous'
    }
]

patients_df = pd.read_csv('covid_19_india.csv')
active_cases = patients_df['Confirmed'].sum()
recovered_cases = patients_df['Cured'].sum()
death_cases = patients_df['Deaths'].sum()
total = active_cases + death_cases + recovered_cases


app = Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    html.H1("Covid-19 Virus Dashboard",style={'color': 'white', 'text-align': 'center'}),
    
    html.Div([
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Total Cases',className='text-light'),
                    html.H4(total,className='text-light')
                    ],className='card-body')
                ], className='card bg-danger')
        ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Active Cases',className='text-light'),
                    html.H4(active_cases,className='text-light')
                    ],className='card-body')
                ], className='card bg-info')
            ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Recovered',className='text-light'),
                    html.H4(recovered_cases,className='text-light')
                    ],className='card-body')
                ], className='card bg-warning')
            ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Deaths',className='text-light'),
                    html.H4(death_cases,className='text-light')
                    ],className='card-body')
                ], className='card bg-success')
            ],className='col-md-3'),
        
        ],className='row'),
    html.Div([],className='row'),
    html.Div([
        html.Div([
            html.Div([
                html.Div([
                    dcc.Dropdown(id='Picker',options='',value='all')
                ],className='card-body')
            ],className='card')
        ],className='col-md12')
    ],className='row'),
    
    
], className='container')

if __name__ == '__main__':
    app.run(debug=True)

## callback decorator

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from dash import Dash, html, dcc, Input, Output

# External CSS stylesheet
external_stylesheets = [
    {
        'href': 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css',
        'rel': 'stylesheet',
        'integrity': 'sha384-uCw98/SfnGE*ft3GXwEOngsV77t27NXFoao4pmYm81iuXoPkF)jBERdknLPMO',
        'crossorigin': 'anonymous'
    }
]

patients_df = pd.read_csv('covid_19_india.csv')
active_cases = patients_df['Confirmed'].sum()
recovered_cases = patients_df['Cured'].sum()
death_cases = patients_df['Deaths'].sum()
total = active_cases + death_cases + recovered_cases


our_options = [
    {'label': 'All','value': 'All'},
    {'label': 'Confirmed','value': 'Confirmed'},
    {'label': 'Cured','value': 'Cured'},
    {'label': 'Deaths','value': 'Deaths'},
    
]

app = Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    html.H1("Covid-19 Virus Dashboard",style={'color': 'white', 'text-align': 'center'}),
    
    html.Div([
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Total Cases',className='text-light'),
                    html.H4(total,className='text-light')
                    ],className='card-body')
                ], className='card bg-danger')
        ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Active Cases',className='text-light'),
                    html.H4(active_cases,className='text-light')
                    ],className='card-body')
                ], className='card bg-info')
            ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Recovered',className='text-light'),
                    html.H4(recovered_cases,className='text-light')
                    ],className='card-body')
                ], className='card bg-warning')
            ],className='col-md-3'),
        html.Div([
            html.Div([
                html.Div([
                    html.H3('Deaths',className='text-light'),
                    html.H4(death_cases,className='text-light')
                    ],className='card-body')
                ], className='card bg-success')
            ],className='col-md-3'),
        
        ],className='row'),
    html.Div([],className='row'),
    html.Div([
        html.Div([
            html.Div([
                html.Div([
                    dcc.Dropdown(id = 'picker',options=our_options,value='All'),
                    dcc.Graph(id='bar',figure=None)
                ],className='card-body')
            ],className='card')
        ],className='col-md-12')
    ],className='row'),
    
    
], className='container')

# first connect to dropdown second to grpah

@app.callback(Output(('bar','figure')),[Input('picker','value')])
def update_graph(type):
    return # plot graph


if __name__ == '__main__':
    app.run(debug=True)