Resources = [text](https://pythondatabook.com/p_data_on_display_data_viz_types.html)

# Data Visualization  Steps 
1. Data wrangling and cleaning your data
2. pick  the Right type visulization for your Question
3. writing code for visulization

today we focus on the second step choose the right  data viz for your data .

# How to get ideas for plots 
- I google search similar plots  example if I wanted a plot between revenue and cost per quarter. to go images . see the charts and I reproduce the chart with code.
- ask an LLM (chatgpt)
    - give them data and ask what kinds of plots I make on data .
- look through a taxonomy chart

taxonomy chart is the focus of the course and it have pros and cons .

cons are it is hard to describe a balance between a taxonomy chart that is not too confusing and  or that is not too limiting . 
It is very difficult to fit all visulation charts in a single flow chart or a single decision tree.

but for a beginner the taxonomy  charts are very  useful .

today we create  a simple(and limited ) data viz taxonomy chart with the tips dataset .

# classfication of data

For Deciding the which type of visulisation I make 
you ask two ask ? or you do the two fundamental classification
How many variable I analysis ? 
- Uni Varaite = Uni means one vairate menas variable (one variable)
- Bi Varaite = Bi means two vairate menas variable (two variable)
- multi Varaite = many (more than two, example three,four  ,n ) means two vairate menas variable (many  variable)

which type of data/variable it is 
- Numerical 
- Categorical

- Univariate numeric data
- Univariate  categorical data
- Bivariate numeric vs numeric
- Bivariate numeric vs categorical
- Bivariate categorical vs categorical
- Time series

so tips dataset have 240 rows each represet a customer
- total_bill = How much the customer pay.
- tip = how much money each customer pay for tip .
- sex = what is the gender of the customer.
- day = on which day the customer is coming

now think what kinds of Question can be answered with data . and then we think kind of visulization you made.

- now lets start with one variable(univarite) 
- then the variable will be numerical or cateogroical

(univarite) Numeric 
- What is the distriution of the plots?         
            what is the avg ,middle, min and max, and range tip

(univarite) Categorical 
- Are there more males or females dinner

Two Variable (Bivarite) numeric and numeric 
- Does tip amount go up with bill amount    
Does higher tip correlate with higher bill  is their any relanship

(Bivarite) categorical numeric vs 
- Which gender(male or female) pay higher bill/tips more

Bivarite categorical vs categorical 
- how can the sex(gender) ratio differ by day mon,tues,wed .. sunday

In [1]:
import plotly.express as px
import pandas as pd
import numpy as np
import plotly.io as pio

tips = px.data.tips()

In [3]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [4]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [11]:
tips['size'].unique()

array([2, 3, 4, 1, 6, 5], dtype=int64)

so classficatio of data 
- total_bill = numeric 
- tip  = numeric
- sex = categorical (male or female )
- smoker cateogrical ( yes or no)
- day =  categorical 7 days (mon tos sunday )
- time = cateforical (dinner lunch)
- size = how many people with it from 1 people to 6 people 
you can consider it categorical

so 7 coloumns 2 is numerica and 5 is categorical

# Univariate Numeric 
Possible visualizations include:

- Histogram – good for seeing the overall distribution of values.
- Box Plot – highlights the median, quartiles, and outliers.
- Violin Plot – combines a box plot with a “smoothed” histogram (density) shape.
- Strip/Jitter Plot – shows each individual point, slightly “jittered” so they’re not on top of each other.

## Histogram 
- x - axis we have bin size class interval 
- y - axis frequency count of the bin size

In [13]:
fig_hist = px.histogram(tips, x='tip')
fig_hist.show()

## Box plot 
- 5 number summary tell me about the distribution (spread of the data)

In [14]:
fig_box = px.box(tips, x='tip')
fig_box.show()

## violin plot 
- violin plot = box plot  + density curve 
- apka histogram ya yadi hum discreate sa continuous kar da tho(smooth it ) vo ban jya ga continous histogram ek cureve us curve ko upar aor nicha draw karna par huma milaga violin plot

In [ ]:
px.violin(tips, x='tip')

In [ ]:
# observe ya muja 5 number summary hi show kar raha ha 
# chalo usko dekta ha

In [17]:
px.violin(tips ,x = 'tip',box=True)

In [ ]:
# ab mera sawal ha ki muja un points ko bhi dekna ha wa ha kaha par 
# we use the point parameter to all 
# Violin Plot (with Box + Points)
px.violin(tips ,x = 'tip',box=True,points='all')

## strip plot

In [19]:
px.strip(tips,x='tip')

# Univariate Categorical
Questions of the form: > How many observations fall into each category? > In the case of the tips dataset, how many observations are there for each sex?

Possible visualizations include:

- Bar Chart – typically counts how many rows fall into each category.
- Pie Chart – can be used if you have only a few categories and want to highlight proportions.

## Bar Chart

In [ ]:
px.bar(tips,x=tips['sex'],)

In [ ]:
# change color by  giving the coloumn in colour parameter
px.bar(tips,x=tips['sex'],color='sex')
# apna colour chuna ha tho colour_discreate_sequence ma sent karo hex code ma

In [25]:
# you can also do that 
px.histogram(tips, x='sex', color='sex', color_discrete_sequence=['#deb221', '#2f828a'])

In [ ]:
# bar ma hover karna par frequency count not show 
# lakin histogram ma frequency hover karna par show

In [37]:
# konsa day ko sabsa jada people ata ha 
px.bar(tips,x=tips['day'])

In [39]:
# how many smoker and non smoker
px.bar(tips,x=tips['smoker'],color='smoker')

## pie chart 
used when small number of categories used for relative compariosn .

In [ ]:
# kitna percent males and females
# what is the gender proportion

In [30]:
px.pie(
    data_frame= tips,
    names='sex'
)

In [ ]:
# how many people came in groups maxiumum 
# sabsa jada people kasa aya tha 
px.pie(tips, names=tips['size'])

In [ ]:
# konsa day ko sabsa jada people ata ha

In [33]:
px.pie(tips ,names=tips['day'])

# Bivariate

When comparing two variables, consider whether they’re numeric or categorical. We’ll look at:

- Numeric vs Numeric
- Numeric vs Categorical
- Categorical vs Categorical

# Numeric vs Numeric
Typical question: > Do two numeric variables correlate? > In the case of the tips dataset, does the total bill correlate with the tip?

A scatter plot is usually the first choice.

In [ ]:
px.scatter(
    data_frame=tips,
    x=tips['total_bill'],
    y =tips['tip'],
)
# humm their is a postive linear correlaton

# Numeric vs Categorical
Typical questions: > Which group has higher values on average?
> In the case of the tips dataset, do men or women tip more?

Visual options:

- Grouped Histograms – separate histograms for each category (often overlaid).
- Grouped Box/Violin/Strip – one distribution plot per category.
- Summary Bar Chart – show mean (or median) for each category, optionally with error bars.

## grouped histogram

In [ ]:
# grouped Histogram 
px.histogram(
    data_frame=tips,
    x='tip',
    color='sex', # color used for sex coloum
    barmode='overlay',
    color_discrete_sequence=['#deb221', '#2f828a'] # our custom colour 
)

# grouped box/violin/strip

In [ ]:
fig_grouped_violin = px.violin(tips, x='tip', y='sex' ,color='sex',
                            box=True, points='all',
                            color_discrete_sequence=['#deb221', '#2f828a'])
fig_grouped_violin.update_layout(showlegend=False) # hum jo customisationc hata ha ya par 
fig_grouped_violin.show()

## Summary Bar (Mean + Std)

In [49]:
summary_df = tips.groupby('sex').agg({'tip': ['mean', 'std']}).reset_index()
summary_df

      sex       tip
               mean       std
0  Female  2.833448  1.159495
1    Male  3.089618  1.489102

In [ ]:
summary_df.columns = ['sex', 'mean_tip', 'std_tip'] # change the names

In [51]:
summary_df

      sex  mean_tip   std_tip
0  Female  2.833448  1.159495
1    Male  3.089618  1.489102

In [ ]:
summary_df = tips.groupby('sex').agg({'tip': ['mean', 'std']}).reset_index()
summary_df.columns = ['sex', 'mean_tip', 'std_tip']

fig_mean_bar = px.bar(
    summary_df,
    x='mean_tip',
    y='sex',
    error_x='std_tip',
    color='sex',
    color_discrete_sequence=['#deb221', '#2f828a'],
)
fig_mean_bar.update_layout(showlegend=False)
fig_mean_bar.show()

Categorical vs Categorical
Typical question: > How do two categorical variables overlap?
> In the case of the tips dataset, how does the sex ratio differ by day of the week?

Visual options:

- Stacked Bar Chart – total counts, stacked by category.
- Grouped/Clustered Bar Chart – side-by-side bars per category.
- Percent Stacked Bar Chart – each bar scaled to 100% so you see proportions

## Grouped Bar chart

In [55]:
# we draw the bar chart 
px.histogram(tips,x='day',color='sex',barmode='group')

In [ ]:
# conclude sat and sunday ko bhut jada males ata ha

## Stacked Bar Char

In [ ]:
px.histogram(tips,x='day',color='sex') # default barmode = stack chart hota ha

In [60]:
# you can also draw the percent stack 
px.histogram(tips,x='day',color='sex',
            barmode='stack',barnorm='percent'
            )

In [ ]:
# I did a some mistake I did not sort the days  
# i did not sort the bar graph .

In [ ]:
# so saturday ko 68 percent males and 32 females  ati ha

# Time Series
Although you can treat time as a numeric variable, time series are unique because they show how values change over continuous time. Common plots:

Line Charts – ideal for continuous trends.
Bar Charts – can work, but typically suggest discrete steps rather than a smooth progression.

Example with india  population from Plotly’s gapminder dataset:

In [62]:
gap_df= px.data.gapminder()

india_pop = gap_df.query('country == "India"' )

px.line(india_pop,x='year',y='pop',markers=True)

In [63]:
px.bar(india_pop,x='year',y='pop')