In [ ]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [5]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results
import pandas as pd 
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
fifa = pd.read_csv(url)
fifa.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [ ]:
(fifa['On Target'] /fifa['Total Attempts'])*100

0        0.000000
1      100.000000
2       53.846154
3       37.500000
4       26.666667
          ...
123      7.692308
124     28.571429
125     28.571429
126     42.857143
127     50.000000
Length: 128, dtype: float64

In [ ]:
fifa['Team'].unique()

array(['Qatar', 'Ecuador', 'England', 'Iran', 'Senegal', 'Netherlands',
       'United States', 'Wales', 'Argentina', 'Saudi Arabia', 'Denmark',
       'Tunisia', 'Mexico', 'Poland', 'France', 'Australia', 'Morocco',
       'Croatia', 'Germany', 'Japan', 'Spain', 'Costa Rica', 'Belgium',
       'Canada', 'Switzerland', 'Cameroon', 'Uruguay', 'Korea Republic',
       'Portugal', 'Ghana', 'Brazil', 'Serbia'], dtype=object)

In [ ]:
fifa['Team'].nunique()

32

In [ ]:
fifa[['Team','On Target','Total Attempts']]

          Team  On Target  Total Attempts
0        Qatar          0               5
1      Ecuador          5               5
2      England          7              13
3         Iran          3               8
4      Senegal          4              15
..         ...        ...             ...
123    Morocco          1              13
124    Croatia          4              14
125    Morocco          2               7
126  Argentina          9              21
127     France          5              10

[128 rows x 3 columns]

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [18]:
fifa['Team'].value_counts().rank(method='first')

Team
Morocco           29.0
Croatia           30.0
Argentina         31.0
France            32.0
England           25.0
Brazil            26.0
Netherlands       27.0
Portugal          28.0
Poland            17.0
Japan             18.0
Switzerland       19.0
Australia         20.0
Korea Republic    21.0
United States     22.0
Senegal           23.0
Spain             24.0
Cameroon           1.0
Uruguay            2.0
Belgium            3.0
Ghana              4.0
Canada             5.0
Qatar              6.0
Costa Rica         7.0
Germany            8.0
Ecuador            9.0
Mexico            10.0
Tunisia           11.0
Denmark           12.0
Saudi Arabia      13.0
Wales             14.0
Iran              15.0
Serbia            16.0
Name: count, dtype: float64

In [ ]:
(fifa['Team'].value_counts() + fifa['Against'].value_counts()).sort_values(ascending=False)

Argentina         14.0
Croatia           14.0
Morocco           14.0
France            13.0
Brazil            10.0
Portugal          10.0
England           10.0
Netherlands       10.0
Japan              8.0
United States      8.0
Switzerland        8.0
Spain              8.0
Senegal            8.0
Poland             8.0
Australia          8.0
Korea Republic     8.0
Iran               6.0
Mexico             6.0
Ghana              6.0
Germany            6.0
Ecuador            6.0
Denmark            6.0
Qatar              6.0
Saudi Arabia       6.0
Costa Rica         6.0
Serbia             6.0
Canada             6.0
Cameroon           6.0
Tunisia            6.0
Belgium            6.0
Uruguay            6.0
Wales              6.0
Fram               NaN
Name: count, dtype: float64

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [ ]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

In [ ]:
fifa.describe()

,Sl. No,Match No.,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,32.500000,1.343750,43.476562,1.203125,0.117188,0.914062,11.257812,4.007812,4.835938,6.914062,4.343750,13.562500,4.671875,4.906250,4.648438,12.234375,92.703125,12.453125,169.281250,109.476562,14.812500,8.265625,1.726562,0.023438,12.320312,1.976562,502.859375,430.929688,19.523438,4.898438,4.468750,14.250000,0.335938,1.429688
std,37.094474,18.545539,1.342448,11.442403,1.324270,0.322907,1.150333,5.406683,2.588576,2.610630,3.998085,2.733397,6.901729,2.886595,3.080131,2.936573,6.176517,29.440547,18.152399,34.120661,30.776298,7.230458,5.101311,1.514834,0.151883,4.691983,1.731891,160.160487,160.893724,8.596799,3.520111,2.774852,4.712189,0.941412,1.389973
min,1.000000,1.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,32.000000,0.000000,56.000000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,225.000000,156.000000,4.000000,0.000000,0.000000,5.000000,0.000000,0.000000
25%,32.750000,16.750000,0.000000,35.000000,0.000000,0.000000,0.000000,7.750000,2.000000,3.000000,4.000000,3.000000,8.000000,2.000000,3.000000,3.000000,8.000000,72.750000,7.000000,149.500000,87.750000,10.000000,5.000000,1.000000,0.000000,9.000000,1.000000,398.250000,323.250000,13.000000,3.000000,2.000000,11.000000,0.000000,0.000000
50%,64.500000,32.500000,1.000000,45.000000,1.000000,0.000000,1.000000,10.000000,4.000000,4.000000,6.000000,4.000000,12.000000,4.500000,4.000000,4.000000,11.000000,93.000000,9.000000,170.500000,106.000000,15.000000,8.000000,2.000000,0.000000,12.000000,2.000000,495.500000,419.000000,19.000000,4.000000,4.000000,14.000000,0.000000,1.000000
75%,96.250000,48.250000,2.000000,51.000000,2.000000,0.000000,1.000000,14.000000,6.000000,6.000000,9.000000,5.000000,18.000000,7.000000,6.250000,6.000000,16.250000,111.250000,14.000000,188.000000,129.000000,20.000000,11.000000,2.000000,0.000000,15.000000,3.000000,589.500000,519.750000,24.000000,6.000000,6.000000,17.000000,0.000000,3.000000
max,128.000000,64.000000,7.000000,78.000000,7.000000,1.000000,6.000000,32.000000,13.000000,17.000000,24.000000,15.000000,36.000000,13.000000,16.000000,19.000000,29.000000,186.000000,192.000000,259.000000,192.000000,40.000000,27.000000,8.000000,1.000000,30.000000,10.000000,1070.000000,994.000000,53.000000,25.000000,14.000000,30.000000,5.000000,3.000000

In [ ]:
fifa.isnull()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
124,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
125,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
126,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
127,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#fifa.fillna(fifa.mean())

In [13]:
fifa.isnull().sum()

Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
dtype: int64

In [21]:
fifa.drop_duplicates(inplace=True)
fifa

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

In [9]:

fifa.drop(columns=['Sl. No', 'Match No.', "Red Cards" , "Pts"])

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,...,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
0,Qatar,Ecuador,A,0,40,0,0,0,5,0,...,4,15,3,453,387,10,5,1,19,0
1,Ecuador,Qatar,A,2,46,2,0,1,5,5,...,2,15,4,484,419,26,10,3,17,1
2,England,Iran,B,6,69,6,0,6,13,7,...,0,9,2,810,733,29,9,8,16,0
3,Iran,England,B,2,20,2,0,1,8,3,...,2,14,2,232,156,11,3,0,10,1
4,Senegal,Netherlands,A,0,39,0,0,0,15,4,...,2,13,2,391,326,22,8,6,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Morocco,Fram,F,0,55,0,0,0,13,1,...,1,11,3,583,518,22,1,3,15,0
124,Croatia,Morocco,F,2,45,2,0,2,14,4,...,0,13,2,491,430,21,3,6,13,0
125,Morocco,Croatia,F,1,45,1,0,0,7,2,...,2,11,2,494,428,20,5,3,15,0
126,Argentina,France,C,3,46,3,0,1,21,9,...,4,26,4,648,544,20,4,6,22,5
127,France,Argentina,D,3,40,3,0,1,10,5,...,3,19,4,516,419,24,3,5,28,4

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [41]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_train = pd.read_csv(url)
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [42]:
titanic_train.drop(columns='Age')

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500,NaN,Q

In [ ]:
url_1= "https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv"
titanic_test = pd.read_csv(url_1)
titanic_test['Age'].fillna(titanic_test['Age'].mean())

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [1]:
import pandas as pd 
ipl = pd.read_csv('ipl-matches.csv')
changed_name = {'Delhi Daredevils':'Delhi Capitals', 
                'Kings XI Punjab':'Punjab Kings',
                'Rising Pune Supergiants':'Rising Pune Supergiant'}
ipl.replace(changed_name.keys(), changed_name.values(),  inplace = True ) # it have permanent changes 
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [26]:
Ques_df = pd.DataFrame()
Ques_df

Empty DataFrame
Columns: []
Index: []

In [27]:
# Ques matches played complete 
oringal_ipl_data = pd.read_csv('ipl-matches.csv')
ipl = oringal_ipl_data.copy()
Ques_df['Match_played'] = ipl['Team1'].value_counts() + ipl['Team2'].value_counts()
Ques_df

                             Match_played
Chennai Super Kings                   208
Deccan Chargers                        75
Delhi Capitals                         63
Delhi Daredevils                      161
Gujarat Lions                          30
Gujarat Titans                         16
Kings XI Punjab                       190
Kochi Tuskers Kerala                   14
Kolkata Knight Riders                 223
Lucknow Super Giants                   15
Mumbai Indians                        231
Pune Warriors                          46
Punjab Kings                           28
Rajasthan Royals                      192
Rising Pune Supergiant                 16
Rising Pune Supergiants                14
Royal Challengers Bangalore           226
Sunrisers Hyderabad                   152

In [28]:
# Win%,  
# ipl team ka wining match ka value count nikalo divide by totoal mathces played by team 
Ques_df['Win%'] = round( (ipl['WinningTeam'].value_counts()) / (ipl['Team1'].value_counts() + ipl['Team2'].value_counts())*100)
Ques_df

                             Match_played  Win%
Chennai Super Kings                   208  58.0
Deccan Chargers                        75  39.0
Delhi Capitals                         63  57.0
Delhi Daredevils                      161  42.0
Gujarat Lions                          30  43.0
Gujarat Titans                         16  75.0
Kings XI Punjab                       190  46.0
Kochi Tuskers Kerala                   14  43.0
Kolkata Knight Riders                 223  51.0
Lucknow Super Giants                   15  60.0
Mumbai Indians                        231  57.0
Pune Warriors                          46  26.0
Punjab Kings                           28  46.0
Rajasthan Royals                      192  50.0
Rising Pune Supergiant                 16  62.0
Rising Pune Supergiants                14  36.0
Royal Challengers Bangalore           226  48.0
Sunrisers Hyderabad                   152  49.0

In [29]:
# Home Win%, Away Win%.
#Show sorted dataframe on Win%
# total mathces played how much win
total_matches = ipl['Team1'].value_counts() + ipl['Team2'].value_counts()
# Team1 home win 
ipl[['Team1','Team2','WinningTeam']]
# so wining team and Team 1 are same 
Ques_df['Home_Win%'] = round(((ipl['WinningTeam'].value_counts()) /(ipl['Team1'].value_counts())) *100)
Ques_df['Away_Win%'] = round(((ipl['WinningTeam'].value_counts()) /(ipl['Team2'].value_counts())) *100)
Ques_df.sort_values(by='Win%',ascending=False )

                             Match_played  Win%  Home_Win%  Away_Win%
Gujarat Titans                         16  75.0      171.0      133.0
Rising Pune Supergiant                 16  62.0      143.0      111.0
Lucknow Super Giants                   15  60.0      112.0      129.0
Chennai Super Kings                   208  58.0      109.0      125.0
Mumbai Indians                        231  57.0      117.0      110.0
Delhi Capitals                         63  57.0      124.0      106.0
Kolkata Knight Riders                 223  51.0      109.0       97.0
Rajasthan Royals                      192  50.0      108.0       93.0
Sunrisers Hyderabad                   152  49.0      109.0       90.0
Royal Challengers Bangalore           226  48.0       87.0      109.0
Kings XI Punjab                       190  46.0       96.0       90.0
Punjab Kings                           28  46.0       72.0      130.0
Gujarat Lions                          30  43.0       81.0       93.0
Kochi Tuskers Kerala                   14  43.0       86.0       86.0
Delhi Daredevils                      161  42.0       79.0       88.0
Deccan Chargers                        75  39.0       74.0       81.0
Rising Pune Supergiants                14  36.0       71.0       71.0
Pune Warriors                          46  26.0       52.0       52.0

###`Q-7:` Venues with most "no result" matches.

In [3]:
#ipl['WonBy']
ipl.WonBy.value_counts()

WonBy
Wickets      509
Runs         423
SuperOver     14
NoResults      4
Name: count, dtype: int64

In [7]:
ipl['WonBy'] == 'NoResults'
ipl[ipl['WonBy'] == 'NoResults']['Venue'].value_counts().head(1)

Venue
M Chinnaswamy Stadium    2
Name: count, dtype: int64

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [ ]:
# find the final match
# than combine the team1 and team 2 players

ipl['MatchNumber'] == 'Final'
ipl['all_players'] = ipl['Team1Players'] + ipl['Team2Players']
ipl['all_players']
ipl[ipl['MatchNumber'] == 'Final']['all_players']

0      ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
74     ['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...
134    ['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...
194    ['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...
254    ['SP Goswami', 'S Dhawan', 'KS Williamson', 'S...
314    ['LMP Simmons', 'PA Patel', 'AT Rayudu', 'RG S...
373    ['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL ...
433    ['LMP Simmons', 'PA Patel', 'RG Sharma', 'KA P...
492    ['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...
552    ['MEK Hussey', 'M Vijay', 'SK Raina', 'S Badri...
628    ['MS Bisla', 'G Gambhir', 'JH Kallis', 'LR Shu...
702    ['MEK Hussey', 'M Vijay', 'MS Dhoni', 'SK Rain...
775    ['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...
835    ['JH Kallis', 'MK Pandey', 'RE van der Merwe',...
892    ['PA Patel', 'S Vidyut', 'SK Raina', 'JA Morke...
Name: all_players, dtype: object

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

In [ ]:
# custom points  func
# compare the total match 
# win matches 
# loss mathces 

def point_table(input_season):

    df = pd.DataFrame()
    season_df = ipl[ipl['Season'] == input_season]
    df['Match_played'] = season_df['Team1'].value_counts() + season_df['Team2'].value_counts()
    df['Match_won']    = season_df['WinningTeam'].value_counts()
    #df['Match_loss']   = df['Match_played'] - df['Match_won']
    df['Points']       = df['Match_won'] * 2
    
    return df.sort_values(by='Points',ascending=False)
    
point_table(input_season='2017')

                             Match_played  Match_won  Points
Mumbai Indians                         17         12      24
Rising Pune Supergiant                 16         10      20
Kolkata Knight Riders                  16          9      18
Sunrisers Hyderabad                    14          8      16
Punjab Kings                           14          7      14
Delhi Capitals                         14          6      12
Gujarat Lions                          14          4       8
Royal Challengers Bangalore            13          3       6

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [26]:
# custom points  func
# compare the total match 
# win matches 
# loss mathces 

def point_table(input_season):

    df = pd.DataFrame()
    season_df = ipl[ipl['Season'] == input_season]
    df['Match_played'] = season_df['Team1'].value_counts() + season_df['Team2'].value_counts()
    df['Match_won']    = season_df['WinningTeam'].value_counts()
    #df['Match_loss']   = df['Match_played'] - df['Match_won']
    df['Points']       = df['Match_won'] * 2
    df['Season_rank']  = ipl[ipl['MatchNumber'] == 'Final']['WinningTeam'].value_counts().rank(ascending=False)
    return df.sort_values(by='Points',ascending=False)
    
point_table(input_season='2017')

                             Match_played  Match_won  Points  Season_rank
Mumbai Indians                         17         12      24          1.0
Rising Pune Supergiant                 16         10      20          NaN
Kolkata Knight Riders                  16          9      18          3.0
Sunrisers Hyderabad                    14          8      16          5.5
Punjab Kings                           14          7      14          NaN
Delhi Capitals                         14          6      12          NaN
Gujarat Lions                          14          4       8          NaN
Royal Challengers Bangalore            13          3       6          NaN

In [17]:
# konsi team na sabsa jada season jita ha 
ipl['MatchNumber'] == 'Final'
ipl[ipl['MatchNumber'] == 'Final']['WinningTeam'].value_counts()

WinningTeam
Mumbai Indians           5
Chennai Super Kings      4
Kolkata Knight Riders    2
Gujarat Titans           1
Sunrisers Hyderabad      1
Deccan Chargers          1
Rajasthan Royals         1
Name: count, dtype: int64

In [20]:
# now Question ya team kon kon sa season ma jiti ha vo batho
# match number final ho 
# wining team ho 
# season ho 
ipl[ipl['MatchNumber'] == 'Final'][['WinningTeam','Season']]

               WinningTeam   Season
0           Gujarat Titans     2022
74     Chennai Super Kings     2021
134         Mumbai Indians  2020/21
194         Mumbai Indians     2019
254    Chennai Super Kings     2018
314         Mumbai Indians     2017
373    Sunrisers Hyderabad     2016
433         Mumbai Indians     2015
492  Kolkata Knight Riders     2014
552         Mumbai Indians     2013
628  Kolkata Knight Riders     2012
702    Chennai Super Kings     2011
775    Chennai Super Kings  2009/10
835        Deccan Chargers     2009
892       Rajasthan Royals  2007/08