Today We learn about 
- Data Analysis Process
- import the data
- export the data

- Data Gathering (collect data from various source )
    - csv 
    - api
    - database
    - Webscrabing

# csv files
- So What is csv file
comma separarted file 
- every line is row and values are separated by comma
- it is a famous file format which is use in data science and machine learning 
- tsv stands for tab seprated instead comma symbol values are separted by tabs symbol

## 1.importing pandas

In [ ]:
# so their are various parameters in read_csv function we learn all of them 
# but we learn most parmeter that solves your problem most of them
# today we go in depth about

In [1]:
import pandas as pd

## 2.opening a local csv file 
- you have to provide the name of the file
- you have to provide the relative path = is folder ma is jaga ha

In [2]:
df = pd.read_csv('aug_train.csv')
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

## 3. opening a csv file from url
website

In [ ]:
# example ya file hamrai github sa server par ha 
# waha sa hum apni machine par laya ga 
# kabhi bhi apko server sa csv file lani ho 
# aap ya code snippet copy kar lena

In [ ]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [ ]:
requests.get(url)  # fetch data from the url
# store in the variable req
# fir usma sa text ko fetch nikal aor 
# data varible ma store karna
# fir pd.read_csv ma paas karna 
# ya header ek client ki tara kam kar raha

## 4. Sep parameter

In [ ]:
# example 
# "movie_titles_metadata.tsv" ya tab separted data ha not comma seprated 
# deko function ma default setting ma sep parameter comma ha 
pd.read_csv('movie_titles_metadata.tsv')
# deko comma usko mila nahi isliya sab ek line ma ha

    m0\t10 things i hate about you\t1999\t6.90\t62847\t['comedy' 'romance']
0    m1\t1492: conquest of paradise\t1992\t6.20\t10...
1    m2\t15 minutes\t2001\t6.10\t25854\t['action' '...
2    m3\t2001: a space odyssey\t1968\t8.40\t163227\...
3    m4\t48 hrs.\t1982\t6.90\t22289\t['action' 'com...
4    m5\tthe fifth element\t1997\t7.50\t133756\t['a...
..                                                 ...
611  m612\twatchmen\t2009\t7.80\t135229\t['action' ...
612  m613\txxx\t2002\t5.60\t53505\t['action' 'adven...
613  m614\tx-men\t2000\t7.40\t122149\t['action' 'sc...
614  m615\tyoung frankenstein\t1974\t8.00\t57618\t[...
615  m616\tzulu dawn\t1979\t6.40\t1911\t['action' '...

[616 rows x 1 columns]

In [ ]:
# now it separated by tab 
pd.read_csv('movie_titles_metadata.tsv',sep='\t')
# observe their is a mistake happen
# apka paas column ka name nahi ha 
# instead jo 1st row tha vo column ban gaya

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

##  5. names parameter

In [7]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names = ['S.No','name','release year','imbd rating','votes','genres'])

,S.No,name,release year,imbd rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

## 6. index_col parameter

In [ ]:
pd.read_csv('aug_train.csv')
# observe you pandas ya index bhi ha aor enroolee_id index bhi ha

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
pd.read_csv('aug_train.csv',index_col='enrollee_id')
# default pandas index replace by column

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

## 7 header parameter

In [ ]:
pd.read_csv('test.csv')
# jo apka first row ha actually wo column ka name observe it 
# kisi na column name ka aaga 0 laga diya tho pandas samaj nahi pa raha

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [ ]:
# so solution is first row is our header  
pd.read_csv('test.csv',header=1)

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

## 8 usecols parameter 
sometimes in machine learning you know that I need this columns and I dont need this columns

In [14]:
pd.read_csv('aug_train.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
# we want only the 3 columns
pd.read_csv('aug_train.csv',usecols=['enrollee_id','gender','education_level'])
# now you can not get full dataframe you not get 3 columns dataframe
# you filter it

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

## 9 skiprows/nrows parameter
jo bhi rows aap doga vo rows skip ho jaya gi

In [17]:
pd.read_csv('aug_train.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
pd.read_csv('aug_train.csv',skiprows=[0,1])
# aap koi bhi

,29725,city_40,0.7759999999999999,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19151,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19152,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19153,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19154,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19155,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
# you can use skiprow intersetely you use a function in it
# aap jo bhi logic function ma implement karoga ab vo skip unha asa karega
# logic would bhi muja 5 ka multiple ma jo row aya gi vo hatana ha
# odd rows rakna ha even hatana ha

In [ ]:
# nrows ma aap jitni value doga utana hi rows ayaga

In [18]:
pd.read_csv('aug_train.csv',nrows=8)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
5,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
6,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
7,402,city_46,0.762,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,<10,Pvt Ltd,>4,18,1.0

In [ ]:
# benefit is jab aap larage dataset ka sath kam kar raha ho example 50 lakh 1 crore row ha
# tho utana aap ek sath memory ma load nahi kar paa raha ho apka ram kam ha
# aap nrows ko use karega data ko manuplate kar sakta ho

## 10 Encoding parameter

In [ ]:
# kaggle par kuch dataset hoga jinka encoding utf 8 nahi hoga 
# ho sakta ho kuch emoji ka dataset ho 
# ho sakta koi alag lanuage ka encoding ho 
# tho unka bhi character encoding alag ho sakta ha

In [19]:
pd.read_csv('zomato.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 7044: invalid continuation byte

In [ ]:
# solution aap kisi text editor ma jakar iska encoding change kar do
# ya aap usko encoding pata karo aor wahi dal do 
# tho zomato.csv use karta ha latin-1 encoing use karta ha

In [20]:
pd.read_csv('zomato.csv',encoding='latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

## 11 skip bad lines 
whenever you get parser error you use the method
skip the bad rows lines

In [ ]:
# example kuch rows ma 5 values ha kuch ma 6 values ha

In [ ]:
pd.read_csv('BX-Books-csv',encoding='latin-1')
# isma paresor erro aya ga kisi ma 5 rows kisi ma 8 row s

In [ ]:
pd.read_csv('BX-Books-csv',encoding='latin-1',skip_blank_lines=True)

## 12 dtype parameter
dtype yani data type jab apka read_csv function kisi file ka data ko dekta ha tho vo column wise analyise kar leta ha ki usma konsa datatype ki values store ha ya sab default hota ha lakin aap chaho tho is behaviour ko over ride kar sakta ho

In [2]:
import pandas as pd

In [3]:
pd.read_csv('aug_train.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [4]:
pd.read_csv('aug_train.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [ ]:
# deko traget ma jo values ha vo 1 and 0 hi jo ki float data type ha
# aap chaho tho una

In [5]:
pd.read_csv('aug_train.csv',dtype={'target':int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int32
dtypes: float64(1), int32(1), int64(2), object(10)
memory usage: 2.0+ MB

In [ ]:
# now you save a lot of memory by using the method

## 13 Handling dates
deko default date to string data type object ma load kiya jata ha 
agar vo string ban jayega tho aap aap uska upar datetime ka functions use hi nahi kar paho ga

In [8]:
pd.read_csv("IPL Matches 2008-2020.csv").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [ ]:
# deko ya date column ko object ma convert kara ha
# object ma matlab pandas ma string hota ha 
# solution apko ek parameter milta ha parse_date 
# us list ma aap columns ka name add kar do

In [9]:
pd.read_csv("IPL Matches 2008-2020.csv",parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

In [ ]:
# wow now it converted into datetime object directly . 
# aap chaho tho index of columns bhi paas kar sakta ho

## 14 Convertors

In [10]:
pd.read_csv("IPL Matches 2008-2020.csv",)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [ ]:
# deko ya ipl ka dataset hum chata ha ki hum
# royal challenger bangular ki jaga rcb kara
# chennai super kings ki jaga csk
# mumbai indians = mi 
# is ki thara sara ipl teams ko convert karna chata ha  
# lets make a function

In [11]:
pd.read_csv("IPL Matches 2008-2020.csv",)['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [12]:
def ipl_team_rename(name):
    if name == 'Royal Challengers Bangalore':
        return 'RCB'
    else:
        return name
    
ipl_team_rename('Royal Challengers Bangalore')

'RCB'

In [ ]:
# convertor parameter ka andr dict ma column name and jo function aap apply
# karna chata ho

In [13]:
pd.read_csv("IPL Matches 2008-2020.csv",converters={'team1': ipl_team_rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [ ]:
## wow ya ho gaya change

## 15 na_values parameter

In [ ]:
# example aug trian csv ma gender ma nan values ha lakin kahi baaar hot ha ki
# missing values nan na hogar - ya unknown likha hota 
# ab ya values na hi nan values ha na hi ya number ha 
#  tho aap na_values parameter ma bata sakta ho kis tara ki values ko nan
# values bolna ha

In [14]:
pd.read_csv('aug_train.csv',na_values=['Male'])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,NaN,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,NaN,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

## 16 Loading a huge dataset in chunks

In [ ]:
# example apka paad bhut bada dataset ha lakhs cror rows ka 
# then use the chunksize 
# 19 thousand rows ha 
# we want 5 housand rows

In [15]:
dfs = pd.read_csv('aug_train.csv',chunksize=5000)
dfs

In [ ]:
# aab aap kuch bhi karta ho vo loop ma karta ho
for chunks in dfs:
    print(chunks.size)

70000
70000
70000
58212

In [19]:
for chunks in dfs:
    print(chunks.size.shape)

# import

## import excel file

In [ ]:
# now we study pandas input /output

In [ ]:
# same read_csv jada read_excel file ha

In [ ]:
path = r"C:\Users\sumit\My_code_files\Data Science codes\week 7-advanced pandas\pandas joins\students.xlsx"
pd.read_excel(path)

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [ ]:
# now hum student id ko index bana chata ha

In [24]:
path = r"C:\Users\sumit\My_code_files\Data Science codes\week 7-advanced pandas\pandas joins\students.xlsx"
pd.read_excel(path,index_col='student_id')

                          name  partner
student_id
1                Kailash Harjo       23
2                  Esha Butala        1
3               Parveen Bhalla        3
4                  Marlo Dugal       14
5                  Kusum Bahri        6
6           Lakshmi Contractor       10
7                 Tarun Thaker        9
8               Radheshyam Dey        5
9            Nitika Chatterjee        4
10              Aayushman Sant        8
11          David Mukhopadhyay       20
12                  Radha Dutt       19
13              Munni Varghese       24
14            Pranab Natarajan       22
15                   Preet Sha       16
16                Elias Dodiya       25
17                Yasmin Palan        7
18             Fardeen Mahabir       13
19                Qabeel Raman       12
20               Hanuman Hegde       11
21                  Seema Kota       15
22                  Yash Sethi       21
23              Chhavi Lachman       18
24                Radhika Suri       17
25             Shashank D’Alia        2

In [ ]:
# yadi apko dursi sheet open karna ho excel file ka andr
pd.read_csv(path ,sheet_name = None)
# now parameter is same as read_csv and read_excel 
# they are similar function

## import text file

In [ ]:
# example aap nlp ma kam kar raho ho apka text file ka sath kam karna
# ho sakta ha
# apko alag alag format ma txt file mila gi 
# lakin aap use karo ga read_csv function hi # kuch error ata ha 
# ya wrong format ma data ha tho aap usa tik karta ho
# jo functions apna sika ha

In [26]:
path = r"C:\Users\sumit\My_code_files\Data Science codes\week 4-Advanced python\Session 10 task\test file.txt"

pd.read_csv(path)

                    1.Why solve assignment Question?
0             2.It improves understanding and logic
1           3.How to Consistent With taking Sessions
2  4. Study daily make a timeblock focus and indi...
3                                5. focus and flow

In [27]:
path = r"C:\Users\sumit\My_code_files\Data Science codes\week 4-Advanced python\Session 10 task\input.txt"

pd.read_csv(path)

    1\t2
0   3\t4
1   5\t6
2   7\t8
3  9\t10

In [36]:
path = r"C:\Users\sumit\My_code_files\Data Science codes\week 4-Advanced python\Session 10 task\input.txt"

pd.read_csv(path,sep = '\s',engine='python',)

<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
C:\Users\sumit\AppData\Local\Temp\ipykernel_3948\4132596967.py:3: SyntaxWarning: invalid escape sequence '\s'
  pd.read_csv(path,sep = '\s',engine='python',)

   1   2
0  3   4
1  5   6
2  7   8
3  9  10

## import from json
json is javascript on notation 
- it is a universal format meaning every programming lanuaguage understand it 
- json usecase and application . like their is a server on that their is a api 
- jab aap api par request karta ho tho api padat kar ka 
apko json data sent karta ha 
- yahi json data ko alag alag programming lanuage use kar sakta ha .

In [ ]:
# so we have a recipe ingredient dataset .
# for classfication machine learning model

In [ ]:
import pandas as pd
pd.read_json('train.json')
# ya tho a local file thi jo hamari machine par thi

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [ ]:
# you also do from a url 
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')
# ya ek currency exhcnage ka data ha 
# inr ka alag alaga country ma kitna value ha

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,0.0428
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,0.8140
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,0.9710
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,4.4800
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,1.1800
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,2.8200
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,0.2070
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-08,1751932801,0.3130

## import from sql
sql = structed query language 
- it is a way to do communication to database .
- in companies or kaggle you get various dataset that are in sql format

In [ ]:
# sbasa pahla aap sql file ko ek database software ma 
# run karta ho . mysql ,postsql
# you install a library mysqlconnector 
# this is bridge betwen both .
# now you talk between sql and pandas
import mysql.connector
connector_variable = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = '',
    database = '' # name of your database
)
# code run karna sa huma ek mysql.connector object milta ha
# ya connection object ko use karka aap aga ka karta ho

In [ ]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",connector_variable)
# ya internally apka dataframe create kar dega

In [ ]:
# very important functions aap sql database sa python pandas 
# ma data la ka aa sakta

# Export
- jitna bhi to wala function ha vo pandas ma export karna wala ha  pd.to_
- to_csv
- to_excel
- to_html
- to_json
- to_sql

In [ ]:
# now we learn various of data how to export them . 
# now apka paas data ha dataframe sa kisi specific data ma export karna 
# chata ho 
# the good things their are various export functions in pandas

In [ ]:
# we create a empty datafraem
import pandas as pd

## export to_csv

In [ ]:
# ipl dataset par hamna bhut kam kiya ha

In [5]:
our_path = r"C:\Users\sumit\My_code_files\Data Science codes\week 7-advanced pandas\pandas joins\deliveries.csv"
df = pd.read_csv(our_path)
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [8]:
batsman_df = df.groupby('batsman')['batsman_runs'].sum().reset_index()
batsman_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4        A Flintoff            62
..              ...           ...
456     YV Takawale           192
457   Yashpal Singh            47
458     Younis Khan             3
459    Yuvraj Singh          2591
460          Z Khan           117

[461 rows x 2 columns]

In [ ]:
# now we need to export our data
#                  name of the file 
batsman_df.to_csv('batsman_runs.csv')

In [ ]:
# koi output nahi aya ga aap dego ki 
# jis folder directory ma aap ho
# waha par ek file add ho gayi ha 
# problem is ki jabardashi ki column index add ho gaya ha
# agara isa solve karnaha

In [10]:
batsman_df.to_csv('batsman_runs_data.csv',index=False)

In [ ]:
# deko data ko apni pasand apna format ma la aaho
# aor export kar sakta ho data ko

## export to_excel

In [ ]:
# same groupby of batsman runs
#                   # name of the file 
batsman_df.to_excel('batsman_runs.xlsx')

In [ ]:
# if you want to store data in sheets then 
# you also do it.

## export to_html
aap chaho tho apna pandas dataframe ko html tables ma convert kar sakta ho

In [ ]:
# example apko ek blog likana ha aor 
# usma apna dataframe ko display karna ha
# aap use karo to_html ko

In [ ]:
df

0         1
1         2
2         3
3         4
4         5
         ..
150455    2
150456    3
150457    4
150458    5
150459    6
Name: ball, Length: 150460, dtype: int64

In [20]:
sixes =  df.query('batsman_runs== 6')

In [23]:
# ipl ki har ball par kitna sixes lagta ha 
overs = [1,2,3,4,5,6]
batsman_sixes = sixes[sixes['ball'].isin(overs)]

In [25]:
sixes_df = batsman_sixes.pivot_table(
    index='over',
    columns='ball',
    values='batsman_runs',
    aggfunc='count'
)
sixes_df

ball   1   2   3   4   5   6
over
1      4   7  17  23  18  18
2     17  17  26  36  30  32
3     44  34  44  38  35  47
4     40  50  39  63  43  43
5     43  47  68  43  49  48
6     51  67  35  47  46  50
7     25  35  21  33  43  22
8     38  40  47  40  46  28
9     57  45  41  46  45  31
10    31  30  43  38  36  45
11    50  55  49  41  51  47
12    55  49  61  55  51  40
13    54  74  47  66  63  55
14    62  64  64  56  52  58
15    52  77  68  66  54  65
16    58  82  81  73  76  66
17    63  76  74  74  85  63
18    75  88  84  99  82  80
19    67  66  90  81  96  74
20    78  73  86  93  70  74

In [27]:
sixes_df.to_html('ipl_sixes.html')

## export to_json

In [ ]:
# we have to create a dataframe 
# - name of the batsman
# - teams of batsman
# - runs scored

In [32]:
teams_df = df.groupby(by =[ 'batting_team','batsman'])['batsman_runs'].sum().unstack()
teams_df

batsman,A Ashish Reddy,A Chandila,A Chopra,A Choudhary,A Flintoff,A Kumble,A Mishra,A Mithun,A Mukund,A Nehra,...,Y Nagar,Y Venugopal Rao,YA Abdulla,YK Pathan,YS Chahal,YV Takawale,Yashpal Singh,Younis Khan,Yuvraj Singh,Z Khan
batting_team,,,,,,,,,,,,,,,,,,,,,
Chennai Super Kings,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Deccan Chargers,35.0,NaN,NaN,NaN,NaN,NaN,84.0,NaN,NaN,NaN,...,NaN,446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Daredevils,NaN,NaN,NaN,NaN,NaN,NaN,163.0,NaN,NaN,25.0,...,285.0,468.0,NaN,NaN,NaN,NaN,NaN,NaN,248.0,10.0
Gujarat Lions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kings XI Punjab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,898.0,NaN
Kochi Tuskers Kerala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kolkata Knight Riders,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1893.0,NaN,NaN,47.0,NaN,NaN,NaN
Mumbai Indians,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,88.0,NaN,NaN,NaN,40.0
Pune Warriors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,581.0,NaN
Rajasthan Royals,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1029.0,NaN,NaN,NaN,3.0,NaN,NaN
Rising Pune Supergiant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rising Pune Supergiants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Royal Challengers Bangalore,NaN,NaN,NaN,25.0,NaN,35.0,NaN,34.0,19.0,NaN,...,NaN,NaN,NaN,NaN,15.0,104.0,NaN,NaN,376.0,67.0
Sunrisers Hyderabad,245.0,NaN,NaN,NaN,NaN,NaN,93.0,NaN,NaN,1.0,...,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,488.0,NaN

In [ ]:
# export the data 
teams_df.to_json('ipl.json')

In [ ]:
# import the data  
pd.read_json('ipl.json')

,A Ashish Reddy,A Chandila,A Chopra,A Choudhary,A Flintoff,A Kumble,A Mishra,A Mithun,A Mukund,A Nehra,...,Y Nagar,Y Venugopal Rao,YA Abdulla,YK Pathan,YS Chahal,YV Takawale,Yashpal Singh,Younis Khan,Yuvraj Singh,Z Khan
Chennai Super Kings,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Deccan Chargers,35.0,NaN,NaN,NaN,NaN,NaN,84.0,NaN,NaN,NaN,...,NaN,446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Daredevils,NaN,NaN,NaN,NaN,NaN,NaN,163.0,NaN,NaN,25.0,...,285.0,468.0,NaN,NaN,NaN,NaN,NaN,NaN,248.0,10.0
Gujarat Lions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kings XI Punjab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,898.0,NaN
Kochi Tuskers Kerala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kolkata Knight Riders,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1893.0,NaN,NaN,47.0,NaN,NaN,NaN
Mumbai Indians,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,88.0,NaN,NaN,NaN,40.0
Pune Warriors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,581.0,NaN
Rajasthan Royals,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1029.0,NaN,NaN,NaN,3.0,NaN,NaN
Rising Pune Supergiant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rising Pune Supergiants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Royal Challengers Bangalore,NaN,NaN,NaN,25.0,NaN,35.0,NaN,34.0,19.0,NaN,...,NaN,NaN,NaN,NaN,15.0,104.0,NaN,NaN,376.0,67.0
Sunrisers Hyderabad,245.0,NaN,NaN,NaN,NaN,NaN,93.0,NaN,NaN,1.0,...,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,488.0,NaN

## export to_sql
hamra paas kuch data ha aor huma usa dataframe ma add karna chata ha

In [ ]:
import pymysql
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('url you provide')

df.to_sql('our_ipl',con=engine,if_exists='append')

# api

In [ ]:
# humna sika data is avaialbe in csv file and database
# now what happen data is avaiable but

In [ ]:
# now we discuss two scenerio
# data ki dursa ki website par ha 
# wo data aap api ka through access kar sakta ha .
# api ko find karna 
# api sa data lana 
# api data ko pandas dataframe ma 
# fir aap us par analysis kar sakta ho

In [ ]:
# another scenrio data is avaialbe on website 
# lakin vo apko api ka through da nahi raha 
# app html code ko nikaloga
# and usma html tags ma sa data nikaloga . 
# jo data un hona chupa raka ha usko extract karaga 
# fir usko pandas dataframe ma convert karna ki koshish karega

## what is an API
api = application programming interface
In simple terms what api do 
- api two softwares ka bitch ma communication karta ha
- api is data pipeline 
- jo information ko point A sa point B tak puchata ha

```mermaid
flowchart LR
  node_1["Software 1"]
  node_2["Software 2"]
  node_1 -- API --> node_2
```

## train ticket book example
for example muja delhi to mumbai jana ha tho mena ticket book b8 ki 17 number ki ticket book kar di from make my trip sa aap muja vo ticket paytm ,phone pa ,indigo, irctc sabhi website par vo ticket already book dhik rahi ha        
        
in sab ka bitch information share kasa ho rahi ha ya data ha irctc ka same data aviablle pass jo sabko available kara da raha ha

- tho irctc ka database ha
- usna en database ka upar  kuch function bana diya hoga 
- vo function is database ka data bhar uta uta kar dikata ha 
- tho inka data json hoga unko alag alag platform la raha ha 
- example software 1(paytm) ka code java ma hoga vo bhi api sa bhat kar sakta ha
- example software 2(Make my trip )ma python ma ha vo bhi bhat kar sakta ha 
- ya sabhi us sa bhat kar sakta ha

```mermaid
flowchart LR
  node_1["irctc database"]
  node_2["function(API) "]
  node_3['Make My trip']
  node_4['Paytm']
  node_5['Rail Yatri']
  node_1 -- Data --> node_2
  node_2 --jSON --> node_3
  node_2 --jSON --> node_4
  node_2 --jSON --> node_5
```

### summary notes 
if someone ask you what is api 
- api is a function .
- but that function is online(have url)
- and the url on the server.     
- anybody can access url give input and take output
- the only difference is the output data format is Json python dictionary key value pair

```mermaid
flowchart TD
  node_1["What is Api in Programming "]
  node_2["Api is a function "]
  node_3["that function is online having url"]
  node_4["and the url on the server "]
  node_5["anybody can accesson url give input and take output  "]
  node_1 --> node_2 
  node_2 --> node_3 
  node_3 --> node_4 
  node_4 --> node_5
```

In [35]:
import pandas as pd
import requests

- find api
- create account and get api key 
- see the documentation what kind of api
- function they provide to communicate to database
- use the api function insert you api key 
- call the api fetch data from api
- convert into pandas datafram
- do analysis

In [ ]:
# my api key 
'4d47bb2ea9c7e0862c7880411d0c835d'

In [36]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0ZDQ3YmIyZWE5YzdlMDg2MmM3ODgwNDExZDBjODM1ZCIsIm5iZiI6MTc1MTk4MzQ4NC40OTMsInN1YiI6IjY4NmQyNTdjNGNiMTU4ZDdiZGVkNWZjYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.GC3nYruWlG6gP7ukQwGWHMtvAEBLNuRtKCRBH_H6UqI"
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg","genre_ids":[18,80],"id":278,"original_language":"en","original_title":"The Shawshank Redemption","overview":"Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.","popularity":26.5392,"poster_path":"/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg","release_date":"1994-09-23","title":"The Shawshank Redemption","video":false,"vote_average":8.712,"vote_count":28517},{"adult":false,"backdrop_path":"/tmU7GeKVybMWFButWEGl2M4GeiP.jpg","genre_ids":[18,80],"id":238,"original_language":"en","original_title":"The Godfather","overview":"Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.","popularity":28.04,"poster_path":"/3bhkrj58Vtu7enYsRolD1fZdja1.jpg","release_date":"1972-03-14","title":"The Godfather","video":false,"vote_average":8.688,"vote_count":21595},{"adult":false,"backdrop_path":"/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg","genre_ids":[16,14,28,35,10402],"id":803796,"original_language":"en","original_title":"KPop Demon Hunters","overview":"When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.","popularity":226.7064,"poster_path":"/43c1efKzA1kigNzY0HBzeoXp8LR.jpg","release_date":"2025-06-20","title":"KPop Demon Hunters","video":false,"vote_average":8.624,"vote_count":476},{"adult":false,"backdrop_path":"/kGzFbGhp99zva6oZODW5atUtnqi.jpg","genre_ids":[18,80],"id":240,"original_language":"en","original_title":"The Godfather Part II","overview":"In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.","popularity":15.0516,"poster_path":"/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg","release_date":"1974-12-20","title":"The Godfather Part II","video":false,"vote_average":8.571,"vote_count":13045},{"adult":false,"backdrop_path":"/zb6fM1CX41D9rF9hdgclu0peUmy.jpg","genre_ids":[18,36,10752],"id":424,"original_language":"en","original_title":"Schindler's List","overview":"The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.","popularity":13.13,"poster_path":"/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg","release_date":"1993-12-15","title":"Schindler's List","video":false,"vote_average":8.565,"vote_count":16520},{"adult":false,"backdrop_path":"/bxgTSUenZDHNFerQ1whRKplrMKF.jpg","genre_ids":[18],"id":389,"original_language":"en","original_title":"12 Angry Men","overview":"The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.","popularity":14.4156,"poster_path":"/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg","release_date":"1957-04-10","title":"12 Angry Men","video":false,"vote_average":8.549,"vote_count":9231},{"adult":false,"backdrop_path":"/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg","genre_ids":[16,10751,14],"id":129,"original_language":"ja","original_title":"千と千尋の神隠し","overview":"A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.","popularity":16.085,"poster_path":"/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg","release_date":"2001-07-20","title":"Spirited Away","video":false,"vote_average":8.5,"vote_count":17261},{"adult":false,"backdrop_path":"/enNubozHn9pXi0ycTVYUWfpHZm.jpg","genre_ids":[18,28,80,53],"id":155,"original_language":"en","original_title":"The Dark Knight","overview":"Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.","popularity":27.0151,"poster_path":"/qJ2tW6WMUDux911r6m7haRef0WH.jpg","release_date":"2008-07-16","title":"The Dark Knight","video":false,"vote_average":8.521,"vote_count":34036},{"adult":false,"backdrop_path":"/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg","genre_ids":[35,18,10749],"id":19404,"original_language":"hi","original_title":"दिलवाले दुल्हनिया ले जायेंगे","overview":"Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.","popularity":6.794,"poster_path":"/2CAL2433ZeIihfX1Hb2139CX0pW.jpg","release_date":"1995-10-20","title":"Dilwale Dulhania Le Jayenge","video":false,"vote_average":8.518,"vote_count":4494},{"adult":false,"backdrop_path":"/amZavErrjrdgDwhsIdpWxHNenIx.jpg","genre_ids":[14,18,80],"id":497,"original_language":"en","original_title":"The Green Mile","overview":"A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.","popularity":15.7106,"poster_path":"/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg","release_date":"1999-12-10","title":"The Green Mile","video":false,"vote_average":8.505,"vote_count":18188},{"adult":false,"backdrop_path":"/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg","genre_ids":[35,53,18],"id":496243,"original_language":"ko","original_title":"기생충","overview":"All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.","popularity":25.1028,"poster_path":"/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg","release_date":"2019-05-30","title":"Parasite","video":false,"vote_average":8.5,"vote_count":19210},{"adult":false,"backdrop_path":"/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg","genre_ids":[53,80,35],"id":680,"original_language":"en","original_title":"Pulp Fiction","overview":"A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.","popularity":17.9018,"poster_path":"/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg","release_date":"1994-09-10","title":"Pulp Fiction","video":false,"vote_average":8.488,"vote_count":28822},{"adult":false,"backdrop_path":"/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg","genre_ids":[12,14,28],"id":122,"original_language":"en","original_title":"The Lord of the Rings: The Return of the King","overview":"As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​","popularity":20.3542,"poster_path":"/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg","release_date":"2003-12-17","title":"The Lord of the Rings: The Return of the King","video":false,"vote_average":8.487,"vote_count":25217},{"adult":false,"backdrop_path":"/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg","genre_ids":[16,10749,18],"id":372058,"original_language":"ja","original_title":"君の名は。","overview":"High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.","popularity":15.0061,"poster_path":"/8GJsy7w7frGquw1cy9jasOGNNI1.jpg","release_date":"2016-08-26","title":"Your Name.","video":false,"vote_average":8.482,"vote_count":11843},{"adult":false,"backdrop_path":"/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg","genre_ids":[35,18,10749],"id":13,"original_language":"en","original_title":"Forrest Gump","overview":"A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.","popularity":22.3856,"poster_path":"/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg","release_date":"1994-06-23","title":"Forrest Gump","video":false,"vote_average":8.468,"vote_count":28353},{"adult":false,"backdrop_path":"/x4biAVdPVCghBlsVIzB6NmbghIz.jpg","genre_ids":[37],"id":429,"original_language":"it","original_title":"Il buono, il brutto, il cattivo","overview":"While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.","popularity":17.1165,"poster_path":"/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg","release_date":"1966-12-22","title":"The Good, the Bad and the Ugly","video":false,"vote_average":8.464,"vote_count":9064},{"adult":false,"backdrop_path":"/l33oR0mnvf20avWyIMxW02EtQxn.jpg","genre_ids":[12,18,878],"id":157336,"original_language":"en","original_title":"Interstellar","overview":"The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.","popularity":33.0358,"poster_path":"/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg","release_date":"2014-11-05","title":"Interstellar","video":false,"vote_average":8.456,"vote_count":37374},{"adult":false,"backdrop_path":"/7TF4p86ZafnxFuNqWdhpHXFO244.jpg","genre_ids":[18,80],"id":769,"original_language":"en","original_title":"GoodFellas","overview":"The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.","popularity":12.8604,"poster_path":"/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg","release_date":"1990-09-12","title":"GoodFellas","video":false,"vote_average":8.455,"vote_count":13466},{"adult":false,"backdrop_path":"/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg","genre_ids":[28,18],"id":346,"original_language":"ja","original_title":"七人の侍","overview":"A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.","popularity":7.9835,"poster_path":"/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg","release_date":"1954-04-26","title":"Seven Samurai","video":false,"vote_average":8.455,"vote_count":3926},{"adult":false,"backdrop_path":"/tDFvXn4tane9lUvFAFAUkMylwSr.jpg","genre_ids":[16,18,10752],"id":12477,"original_language":"ja","original_title":"火垂るの墓","overview":"In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.","popularity":0.0082,"poster_path":"/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg","release_date":"1988-04-16","title":"Grave of the Fireflies","video":false,"vote_average":8.45,"vote_count":5945}],"total_pages":512,"total_results":10227}

In [ ]:
# this is the whole data 
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 26.5392,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.712,
   'vote_count': 28517},
  {'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 28.04,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.688,
   'vote_count': 21595},
  {'adult': False,
   'backdrop_path': '/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg',
   'genre_ids': [16, 14, 28, 35, 10402],
   'id': 803796,
   'original_language': 'en',
   'original_title': 'KPop Demon Hunters',
   'overview': "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
   'popularity': 226.7064,
   'poster_path': '/43c1efKzA1kigNzY0HBzeoXp8LR.jpg',
   'release_date': '2025-06-20',
   'title': 'KPop Demon Hunters',
   'video': False,
   'vote_average': 8.624,
   'vote_count': 476},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 15.0516,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.571,
   'vote_count': 13045},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 13.13,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.565,
   'vote_count': 16520},
  {'adult': False,
   'backdrop_path': '/bxgTSUenZDHNFerQ1whRKplrMKF.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 14.4156,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.549,
   'vote_count': 9231},
  {'adult': False,
   'backdrop_path': '/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 16.085,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 17261},
  {'adult': False,
   'backdrop_path': '/enNubozHn9pXi0ycTVYUWfpHZm.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 27.0151,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.521,
   'vote_count': 34036},
  {'adult': False,
   'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 6.794,
   'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.518,
   'vote_count': 4494},
  {'adult': False,
   'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 15.7106,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.505,
   'vote_count': 18188},
  {'adult': False,
   'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 25.1028,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 19210},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 17.9018,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.488,
   'vote_count': 28822},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 20.3542,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.487,
   'vote_count': 25217},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 15.0061,
   'poster_path': '/8GJsy7w7frGquw1cy9jasOGNNI1.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.482,
   'vote_count': 11843},
  {'adult': False,
   'backdrop_path': '/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 22.3856,
   'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.468,
   'vote_count': 28353},
  {'adult': False,
   'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 17.1165,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-22',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.464,
   'vote_count': 9064},
  {'adult': False,
   'backdrop_path': '/l33oR0mnvf20avWyIMxW02EtQxn.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 33.0358,
   'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
   'release_date': '2014-11-05',
   'title': 'Interstellar',
   'video': False,
   'vote_average': 8.456,
   'vote_count': 37374},
  {'adult': False,
   'backdrop_path': '/7TF4p86ZafnxFuNqWdhpHXFO244.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 12.8604,
   'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.455,
   'vote_count': 13466},
  {'adult': False,
   'backdrop_path': '/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 7.9835,
   'poster_path': '/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.455,
   'vote_count': 3926},
  {'adult': False,
   'backdrop_path': '/tDFvXn4tane9lUvFAFAUkMylwSr.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.0082,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.45,
   'vote_count': 5945}],
 'total_pages': 512,
 'total_results': 10227}

In [ ]:
# go to the json viewer and see the structue of it.

In [ ]:
# hum page 1 par ha 
# har ek page ma 19 movies show hoti ha 
# total_pages : 552
# total_results : 11032

## important columns
- id
- title
- release_date
- overview
- popularity
- vote_average
- vote_count

In [ ]:
11032 * 7 # shape of dataframe

In [ ]:
# now travel in the nested dictionary

In [ ]:
response.json()['results']
# you get list of dictionary what to see

[{'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 26.5392,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'title': 'The Shawshank Redemption',
  'video': False,
  'vote_average': 8.712,
  'vote_count': 28517},
 {'adult': False,
  'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 28.04,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'title': 'The Godfather',
  'video': False,
  'vote_average': 8.688,
  'vote_count': 21595},
 {'adult': False,
  'backdrop_path': '/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg',
  'genre_ids': [16, 14, 28, 35, 10402],
  'id': 803796,
  'original_language': 'en',
  'original_title': 'KPop Demon Hunters',
  'overview': "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
  'popularity': 226.7064,
  'poster_path': '/43c1efKzA1kigNzY0HBzeoXp8LR.jpg',
  'release_date': '2025-06-20',
  'title': 'KPop Demon Hunters',
  'video': False,
  'vote_average': 8.624,
  'vote_count': 476},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 15.0516,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'title': 'The Godfather Part II',
  'video': False,
  'vote_average': 8.571,
  'vote_count': 13045},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 13.13,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'title': "Schindler's List",
  'video': False,
  'vote_average': 8.565,
  'vote_count': 16520},
 {'adult': False,
  'backdrop_path': '/bxgTSUenZDHNFerQ1whRKplrMKF.jpg',
  'genre_ids': [18],
  'id': 389,
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 14.4156,
  'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
  'release_date': '1957-04-10',
  'title': '12 Angry Men',
  'video': False,
  'vote_average': 8.549,
  'vote_count': 9231},
 {'adult': False,
  'backdrop_path': '/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 16.085,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'title': 'Spirited Away',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 17261},
 {'adult': False,
  'backdrop_path': '/enNubozHn9pXi0ycTVYUWfpHZm.jpg',
  'genre_ids': [18, 28, 80, 53],
  'id': 155,
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 27.0151,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'title': 'The Dark Knight',
  'video': False,
  'vote_average': 8.521,
  'vote_count': 34036},
 {'adult': False,
  'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 6.794,
  'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
  'release_date': '1995-10-20',
  'title': 'Dilwale Dulhania Le Jayenge',
  'video': False,
  'vote_average': 8.518,
  'vote_count': 4494},
 {'adult': False,
  'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 15.7106,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'title': 'The Green Mile',
  'video': False,
  'vote_average': 8.505,
  'vote_count': 18188},
 {'adult': False,
  'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 25.1028,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'title': 'Parasite',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 19210},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 17.9018,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'title': 'Pulp Fiction',
  'video': False,
  'vote_average': 8.488,
  'vote_count': 28822},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 20.3542,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'title': 'The Lord of the Rings: The Return of the King',
  'video': False,
  'vote_average': 8.487,
  'vote_count': 25217},
 {'adult': False,
  'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 15.0061,
  'poster_path': '/8GJsy7w7frGquw1cy9jasOGNNI1.jpg',
  'release_date': '2016-08-26',
  'title': 'Your Name.',
  'video': False,
  'vote_average': 8.482,
  'vote_count': 11843},
 {'adult': False,
  'backdrop_path': '/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 13,
  'original_language': 'en',
  'original_title': 'Forrest Gump',
  'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
  'popularity': 22.3856,
  'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
  'release_date': '1994-06-23',
  'title': 'Forrest Gump',
  'video': False,
  'vote_average': 8.468,
  'vote_count': 28353},
 {'adult': False,
  'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
  'genre_ids': [37],
  'id': 429,
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 17.1165,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-22',
  'title': 'The Good, the Bad and the Ugly',
  'video': False,
  'vote_average': 8.464,
  'vote_count': 9064},
 {'adult': False,
  'backdrop_path': '/l33oR0mnvf20avWyIMxW02EtQxn.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 33.0358,
  'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  'release_date': '2014-11-05',
  'title': 'Interstellar',
  'video': False,
  'vote_average': 8.456,
  'vote_count': 37374},
 {'adult': False,
  'backdrop_path': '/7TF4p86ZafnxFuNqWdhpHXFO244.jpg',
  'genre_ids': [18, 80],
  'id': 769,
  'original_language': 'en',
  'original_title': 'GoodFellas',
  'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
  'popularity': 12.8604,
  'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
  'release_date': '1990-09-12',
  'title': 'GoodFellas',
  'video': False,
  'vote_average': 8.455,
  'vote_count': 13466},
 {'adult': False,
  'backdrop_path': '/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg',
  'genre_ids': [28, 18],
  'id': 346,
  'original_language': 'ja',
  'original_title': '七人の侍',
  'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
  'popularity': 7.9835,
  'poster_path': '/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
  'release_date': '1954-04-26',
  'title': 'Seven Samurai',
  'video': False,
  'vote_average': 8.455,
  'vote_count': 3926},
 {'adult': False,
  'backdrop_path': '/tDFvXn4tane9lUvFAFAUkMylwSr.jpg',
  'genre_ids': [16, 18, 10752],
  'id': 12477,
  'original_language': 'ja',
  'original_title': '火垂るの墓',
  'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
  'popularity': 0.0082,
  'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
  'release_date': '1988-04-16',
  'title': 'Grave of the Fireflies',
  'video': False,
  'vote_average': 8.45,
  'vote_count': 5945}]

In [ ]:
# convert into data frame 
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,26.5392,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.712,28517
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",28.0400,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.688,21595
2,False,/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg,"[16, 14, 28, 35, 10402]",803796,en,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...",226.7064,/43c1efKzA1kigNzY0HBzeoXp8LR.jpg,2025-06-20,KPop Demon Hunters,False,8.624,476
3,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,15.0516,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13045
4,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,13.1300,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.565,16520
5,False,/bxgTSUenZDHNFerQ1whRKplrMKF.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,14.4156,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.549,9231
6,False,/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",16.0850,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.500,17261
7,False,/enNubozHn9pXi0ycTVYUWfpHZm.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,27.0151,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.521,34036
8,False,/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",6.7940,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.518,4494
9,False,/amZavErrjrdgDwhsIdpWxHNenIx.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,15.7106,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.505,18188
10,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",25.1028,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.500,19210
11,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80, 35]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",17.9018,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,Pulp Fiction,False,8.488,28822
12,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,20.3542,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,The Lord of the Rings: The Return of the King,False,8.487,25217
13,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,15.0061,/8GJsy7w7frGquw1cy9jasOGNNI1.jpg,2016-08-26,Your Name.,False,8.482,11843
14,False,/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,22.3856,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.468,28353
15,False,/x4biAVdPVCghBlsVIzB6NmbghIz.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,17.1165,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.464,9064
16,False,/l33oR0mnvf20avWyIMxW02EtQxn.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,33.0358,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,Interstellar,False,8.456,37374
17,False,/7TF4p86ZafnxFuNqWdhpHXFO244.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",12.8604,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.455,13466
18,False,/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,7.9835,/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg,1954-04-26,Seven Samurai,False,8.455,3926
19,False,/tDFvXn4tane9lUvFAFAUkMylwSr.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0082,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.450,5945

In [ ]:
pd.DataFrame(response.json()['results']).columns
# now vo columns niklo jo apko chaya

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'release_date', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [49]:
df = pd.DataFrame(response.json()['results'])[[ 'id','title','release_date', 'overview', 'popularity', 'vote_average', 'vote_count']]
df

,id,title,release_date,overview,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,1994-09-23,Imprisoned in the 1940s for the double murder ...,26.5392,8.712,28517
1,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",28.0400,8.688,21595
2,803796,KPop Demon Hunters,2025-06-20,"When K-pop superstars Rumi, Mira and Zoey aren...",226.7064,8.624,476
3,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,15.0516,8.571,13045
4,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,13.1300,8.565,16520
5,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,14.4156,8.549,9231
6,129,Spirited Away,2001-07-20,"A young girl, Chihiro, becomes trapped in a st...",16.0850,8.500,17261
7,155,The Dark Knight,2008-07-16,Batman raises the stakes in his war on crime. ...,27.0151,8.521,34036
8,19404,Dilwale Dulhania Le Jayenge,1995-10-20,"Raj is a rich, carefree, happy-go-lucky second...",6.7940,8.518,4494
9,497,The Green Mile,1999-12-10,A supernatural tale set on death row in a Sout...,15.7106,8.505,18188
10,496243,Parasite,2019-05-30,"All unemployed, Ki-taek's family takes peculia...",25.1028,8.500,19210
11,680,Pulp Fiction,1994-09-10,"A burger-loving hit man, his philosophical par...",17.9018,8.488,28822
12,122,The Lord of the Rings: The Return of the King,2003-12-17,As armies mass for a final battle that will de...,20.3542,8.487,25217
13,372058,Your Name.,2016-08-26,High schoolers Mitsuha and Taki are complete s...,15.0061,8.482,11843
14,13,Forrest Gump,1994-06-23,A man with a low IQ has accomplished great thi...,22.3856,8.468,28353
15,429,"The Good, the Bad and the Ugly",1966-12-22,While the Civil War rages on between the Union...,17.1165,8.464,9064
16,157336,Interstellar,2014-11-05,The adventures of a group of explorers who mak...,33.0358,8.456,37374
17,769,GoodFellas,1990-09-12,"The true story of Henry Hill, a half-Irish, ha...",12.8604,8.455,13466
18,346,Seven Samurai,1954-04-26,A samurai answers a village's request for prot...,7.9835,8.455,3926
19,12477,Grave of the Fireflies,1988-04-16,"In the final months of World War II, 14-year-o...",0.0082,8.450,5945

In [50]:
# now you analysie it 
df['popularity'].mean()

28.062120000000004

# Webscraping

In [ ]:
# today we scrape the ambiton box website jo review deti ha companies ka 
# bara ma

### import libraries

In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
requests.get(url = 'https://www.ambitionbox.com/list-of-companies?page=1')

In [3]:
# 403 menaing bad request server na tumara request reject kar diya . 
requests.get(url = 'https://www.ambitionbox.com/list-of-companies?page=1').text

'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;www&#46;ambitionbox&#46;com&#47;list&#45;of&#45;companies&#63;" on this server.<P>\nReference&#32;&#35;18&#46;e7055a68&#46;1752048278&#46;d2e6a90\n<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;e7055a68&#46;1752048278&#46;d2e6a90</P>\n</BODY>\n</HTML>\n'

In [ ]:
# deko web devlopment ma ek cheez hoti ha robust.txt
# va par tum text file ma name likata ho 
# jinko tum chato ho ki web scrapper crawle na kar paya
# ya fir google search engine crawl na kar paya

In [ ]:
# solution aap http par asa request bhajo ki ya browser sa aa raha ha
# agar tum normally asa website par hit kar raha ho tho lag raha ki tum
# bot ho 
# yadi tuma webiste par hit karna ha tho hum ek extra information bhejo ga
# header asa laga ka ki tho ambiton webiste ko laga ki 
# ya bot ka through nahi broser ka through koi human beings bhej raha ha

In [ ]:
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
url = 'https://www.ambitionbox.com/list-of-companies?page=1'
requests.get(url= url, headers=headers)

In [2]:
import requests  # Step 1: Import the requests library

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}
url = 'https://www.ambitionbox.com/list-of-companies?page=1'

response = requests.get(url, headers=headers)  # Step 2: Make the GET request
webpage = response.text  # Step 3: Extract the HTML content as text

print(webpage)  # Optional: Print or process the HTML

:

:

In [ ]:
# aab aap inspect button par click karo
# content par click karo aor usko code deko 
# aor fir us content ko extract karo using beautifull soup