In [ ]:
import numpy as np
import pandas as pd
# today seassion is very important it is on groupby 
# if you learn you became a good data analyst
# apna alag alag dataset ma filter sort karna sika 
# groupsby is study of groups 
# databases ma bhi groupby hota ha
# pandas and sql groupby is very similar

In [ ]:
# tho hamra paas two dataset ha sika ga movies wala par pratice kara ga deliveries wala pratice kara ga

In [ ]:
# hamara paas imbd ki top 1000 movies ka ha

In [7]:
movies = pd.read_csv('imdb-top-1000.csv')
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Runtime        1000 non-null   int64
 3   Genre          1000 non-null   object
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   object
 6   Star1          1000 non-null   object
 7   No_of_Votes    1000 non-null   int64
 8   Gross          1000 non-null   float64
 9   Metascore      843 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 78.3+ KB

In [ ]:
# aap groupby ma data ka andr groups form karta ho on the basis of some coloumn
# ab konsa coloumn ko aap use karo ga group form karna ka liya
# iska idea kasa laga ga 
# generally apka pass two types ka coloumn hoga 
# ek numerical or categorical 
# example imbd_rating numerical ha and genera = action ,drama categorical ha 
# group by used in only in cateogorical variable

In [8]:
movies.shape

(1000, 10)

In [ ]:
# so total thousand movies ma drame wali,action wali movies ko alag karna chata hu.

# aggreate func
Pandas offers a variety of aggregation functions that can be used with the `.agg()` method. Here's a list of common ones:

- **Mean**: Calculates the mean of the values.
- **Median**: Finds the median of the values.
- **Mode**: Returns the most frequently occurring value.
- **Sum**: Sums up all the values.
- **Min**: Finds the minimum value.
- **Max**: Finds the maximum value.
- **Std**: Calculates the standard deviation.
- **Var**: Calculates the variance.
- **Count**: Counts the number of non-null values.
- **Prod**: Calculates the product of all values.

You can also use custom functions or apply different functions to different columns by passing a dictionary to `.agg()`

In [9]:
genres = movies.groupby('Genre') # coloumn ka name
genres

## applying builtin aggreation function on groupby

### sum

In [10]:
genres.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

### min

In [ ]:
genres.min()
# sari minimum values usna ascii values ka upar kar diya

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [ ]:
# so bol sakta ho action ki sabsa purani movie 1924 ma ayi thi 
# action ma sabsa kam rating wali movie ha 7.6

### mean

In [15]:
genres.mean(numeric_only=True)

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [ ]:
# so action movies ka avg runtime imbd rating and so on ...

### standard deviation

In [17]:
genres.std(numeric_only=True)

             Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     28.500706     0.304258  432946.814748  2.256724e+08  12.421252
Adventure  33.317320     0.229781  301188.347642  1.697543e+08  12.345393
Animation  14.530471     0.253221  262173.231571  2.091840e+08   8.813646
Biography  25.514466     0.267140  271284.191372  1.363251e+08  11.028187
Comedy     22.946213     0.228771  188653.570564  1.946513e+08  11.829160
Crime      27.689231     0.335477  373999.730656  1.571191e+08  13.099102
Drama      27.740490     0.267229  305554.162841  2.201164e+08  12.744687
Family     10.606602     0.000000  137008.302816  3.048412e+08  16.970563
Fantasy    12.727922     0.141421   22179.111299  7.606861e+07        NaN
Film-Noir   4.000000     0.152753   54649.083277  7.048472e+07   1.527525
Horror     13.604812     0.311302  234883.508691  9.965017e+07  15.362291
Mystery    14.475423     0.310791  404621.915297  1.567524e+08  18.604435
Thriller         NaN          NaN            NaN           NaN        NaN
Western    17.153717     0.420317  263489.554280  1.230626e+07   9.032349

## find the top 3 genres by total earning 
ek producer ha vo jan na chata ha ki usa konsi movies bana ni chaya. kaha apna pasa lagan chaya

In [23]:
movies.groupby('Genre').sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [ ]:
# ya 3 genrea jo sabsa jada revene kamta ha  dhyan sa not profit

In [ ]:
# dusra tarika 
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [ ]:
# tho second wala tarika is fast 
# because first ma apna sara coloumns by sum apply kiya fir coloumn nikala
# second ma apna usi coloumn ko nikala jisma aapko sum bana na tha . 
# dhyan sa jab apka paas big dataset ho tho apko second wala yani phala series nikal kar aggregate operation lagana chaya

## find the genre with highest avg IMDB rating

In [ ]:
movies

In [46]:
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [ ]:
movies # movies ka dataset ha

In [40]:
# usma hamna groupby kiya genre sa
movies.groupby('Genre')

In [ ]:
# fir imbd rating nikali

In [41]:
movies.groupby('Genre')['IMDB_Rating']

In [43]:
# fir usko sort kiya 
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Horror       7.909091
Comedy       7.901290
Family       7.800000
Thriller     7.800000
Name: IMDB_Rating, dtype: float64

In [45]:
# top 3 genres
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

## find director with most popularity

In [ ]:
movies

In [ ]:
# tho ya populaity ka koi coloumn nahi ha lakin hum number of votes ko popularity samaj la ga .

In [54]:
# number of votes and director 
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [ ]:
# tho chritopher nolan ki movies ko sabsa jada votes mila ha yani popular ha

## find the highest rated movie of each genre

In [ ]:
# group by karo generes
# fir fency indexing

In [63]:
movies.groupby('Genre')[['Series_Title','IMDB_Rating']].max()

                                  Series_Title  IMDB_Rating
Genre
Action                                 Yôjinbô          9.0
Adventure                           Zombieland          8.6
Animation          Ôkami kodomo no Ame to Yuki          8.6
Biography                              Zerkalo          8.9
Comedy                Zindagi Na Milegi Dobara          8.6
Crime                        À bout de souffle          9.2
Drama                                Zwartboek          9.3
Family     Willy Wonka & the Chocolate Factory          7.8
Fantasy                              Nosferatu          8.1
Film-Noir                        The Third Man          8.1
Horror                               The Thing          8.5
Mystery                                Vertigo          8.4
Thriller                       Wait Until Dark          7.8
Western                 The Outlaw Josey Wales          8.8

##  find number of movies done by each actor

In [70]:
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False).head(1)

Star1
Tom Hanks    12
Name: Series_Title, dtype: int64

In [72]:
movies['Star1'].value_counts().head(1)

Star1
Tom Hanks    12
Name: count, dtype: int64

jab bhi apsa esa Ques pucha jaya aap 3 step ma kam kar raha ho 
1. you do groupby by certain coloumn
2. aap apna desired coloumn nikal raha ho jispa apko jis par  operation run karna ha 
3. fir us par aggreate operation chala raha ho

1. groups ma kiya
2. coloumn nikala
3. aggreate operation kiya

In [ ]:
# is sa aap 90 % problem solve kar lo ga

# Groupby Attributes and Methods

## find total number of groups -- len

kitna groups form hua ya kasa pata chala ga

In [ ]:
len(movies.groupby('Genre'))

14

In [ ]:
# tho total 14 types of genre ha

In [ ]:
movies['Genre'].nunique() # number of unique items/rows

14

abhi hamna pura data ko groups ma divide kiya har group ka andr kitna

##  find items in each group -- size
har groups ka andr kitna rows ha

In [ ]:
# har genre ma kitni movies gyi 
movies.groupby('Genre').size()
# ya index ka basis par sort ha

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [ ]:
movies['Genre'].value_counts()
# ya values ka upar sort ha

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

##  first()/last() / nth item
agar aap chaho tho aap har ek group ka first item nikal sakta ho

In [84]:
genres = movies.groupby('Genre')
# first func kiya karaga apka 14 groups ma gusa ga aor us first movie ko nikal ka apka samna raka ga 
genres.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [ ]:
# aap last movie bhi nikal sakta ho har ek genre ma 
genres.last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [86]:
# nth yani apni marzi sa koi bhi number ki movie nikal sakta ho 
# muja har ek genere ki 7th movie nikal ni ha
genres.nth(6) # 7th index nikal tho 6 kyu kyuki vo 0 sa start hoti ha

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [ ]:
# dhyan sa deko ya apko har ek genre nahi dikyi da raha 
# jisma 7th movie ha wahi dikyi da raha ha 
# kyuki usma 7th movie ha hi nahi tho kaha sa dekiyi dega

##  get_group / vs filtering
ham ek particular group ma  dek sakta ha  item ha

In [87]:
# hum dekna chata ha ki kitni horror movies ha unka name kiya  
genres.get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [88]:
genres.get_group('Fantasy')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [ ]:
# by filtering 
movies['Genre'] == 'Fantasy'
movies[movies['Genre'] == 'Fantasy']

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [ ]:
# so filtering ma usa 14 times run karna pada 
# lakin get groups ma usna phala sa hi groups bana raka ha

## groups attribute

In [ ]:
genres.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [ ]:
# ya apko ek dictionary return karta ha 

# action in phali movie ka index ya par store ha

## describe 
apka group ka har ek numerical coloumn ko summarise karta ha 
kiya kiya dekitha ha 
- count
- mean 
- std
- min
- 25%
- 50%
- 75%
- max

In [ ]:

genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [ ]:
# 25 percent comedy movies 96 minute ki hoti ha

## sample

In [94]:
# 14 genre ha har ek genre ki random movie 
genres.sample()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
666,Lat sau san taam,1992,128,Action,7.8,John Woo,Yun-Fat Chow,46700,565451439.0,NaN
797,"O Brother, Where Art Thou?",2000,107,Adventure,7.7,Joel Coen,Ethan Coen,286742,45512588.0,69.0
211,Ôkami kodomo no Ame to Yuki,2012,117,Animation,8.1,Mamoru Hosoda,Aoi Miyazaki,38803,224400323.0,71.0
525,My Left Foot: The Story of Christy Brown,1989,103,Biography,7.9,Jim Sheridan,Daniel Day-Lewis,68076,14743391.0,97.0
221,Zindagi Na Milegi Dobara,2011,155,Comedy,8.1,Zoya Akhtar,Hrithik Roshan,67927,3108485.0,NaN
708,À bout de souffle,1960,90,Crime,7.8,Jean-Luc Godard,Jean-Paul Belmondo,73251,336705.0,NaN
40,American History X,1998,119,Drama,8.5,Tony Kaye,Edward Norton,1034705,6719864.0,62.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
714,The Lady Vanishes,1938,96,Mystery,7.8,Alfred Hitchcock,Margaret Lockwood,47400,474203697.0,98.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0

In [95]:
#genres.sample(2)
# yadi aap 2 la matlab har ek genre ki 2 random movies mili ga 
# lakin kisi mat 2 movies nahi ha tho error.
genres.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
901,End of Watch,2012,109,Action,7.6,David Ayer,Jake Gyllenhaal,228132,41003371.0,68.0
896,Hell or High Water,2016,102,Action,7.6,David Mackenzie,Chris Pine,204175,26862450.0,88.0
991,Kelly's Heroes,1970,144,Adventure,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
93,Inglourious Basterds,2009,153,Adventure,8.3,Quentin Tarantino,Brad Pitt,1267869,120540719.0,69.0
971,Omohide poro poro,1991,118,Animation,7.6,Isao Takahata,Miki Imai,27071,453243.0,90.0
783,Coraline,2009,100,Animation,7.7,Henry Selick,Dakota Fanning,197761,75286229.0,80.0
38,The Pianist,2002,150,Biography,8.5,Roman Polanski,Adrien Brody,729603,32572577.0,85.0
107,Amadeus,1984,160,Biography,8.3,Milos Forman,F. Murray Abraham,369007,51973029.0,88.0
683,The Breakfast Club,1985,97,Comedy,7.8,John Hughes,Emilio Estevez,357026,45875171.0,66.0
848,Blazing Saddles,1974,93,Comedy,7.7,Mel Brooks,Cleavon Little,125993,119500000.0,73.0
163,Eskiya,1996,128,Crime,8.2,Yavuz Turgul,Sener Sen,64118,764480450.0,NaN
86,Andhadhun,2018,139,Crime,8.3,Sriram Raghavan,Ayushmann Khurrana,71875,1373943.0,NaN
863,Cape Fear,1962,106,Drama,7.7,J. Lee Thompson,Gregory Peck,26457,863391987.0,76.0
661,The Remains of the Day,1993,134,Drama,7.8,James Ivory,Anthony Hopkins,66065,22954968.0,84.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0

## nunique
number of unique items

In [96]:
# yadi aap isa group by par karo ga tho
# har ek genre ma kitni unique movies ha
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [ ]:
# 61  unique years yani ki action ma multiple movies ame year ma aya hogi

# agg method 
aap cha ho tho ek sath multiple aggreation operation laga sakta ha example (sum ,mean,count,min max)
abhi tak ham ek bari ma ek aggre laga raha tha aap chaho tho ek sath multiple laga sakta ho

In [98]:
genres.sum(numeric_only=True)

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [ ]:
# asa ho sakta ha ki aap numeric coloumn par alag alag type of agrreation operation lagana chata ho
# jasa runtime ma sum kuch jada kam ka nahi use mean
# jasa imbd rating  ma sum kuch jada kam ka nahi use mean
# lakin number of votes ma sum,groos ma bhi aor meta score ma bhi

## passing dict

In [103]:
genres.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [104]:
genres.agg(
    {
        'Runtime': 'mean',
        'IMDB_Rating': 'mean',
        'No_of_Votes': 'sum',
        "Gross" : 'sum',
        "Metascore": 'min'
    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

## passing list

In [109]:
# aap 3 operation chalana chata ho min,max ,avg
genres.agg(['min','max','sum'])

                              Series_Title  \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                                \
                                           max
Genre
Action                                 Yôjinbô
Adventure                           Zombieland
Animation          Ôkami kodomo no Ame to Yuki
Biography                              Zerkalo
Comedy                Zindagi Na Milegi Dobara
Crime                        À bout de souffle
Drama                                Zwartboek
Family     Willy Wonka & the Chocolate Factory
Fantasy                              Nosferatu
Film-Noir                        The Third Man
Horror                               The Thing
Mystery                                Vertigo
Thriller                       Wait Until Dark
Western                 The Outlaw Josey Wales

                                                             Released_Year  \
                                                         sum           min
Genre
Action     The Dark KnightThe Lord of the Rings: The Retu...          1924
Adventure  InterstellarBack to the FutureInglourious Bast...          1925
Animation  Sen to Chihiro no kamikakushiThe Lion KingHota...          1940
Biography  Schindler's ListGoodfellasHamiltonThe Intoucha...          1928
Comedy     GisaengchungLa vita è bellaModern TimesCity Li...          1921
Crime      The GodfatherThe Godfather: Part II12 Angry Me...          1931
Drama      The Shawshank RedemptionFight ClubForrest Gump...          1925
Family     E.T. the Extra-TerrestrialWilly Wonka & the Ch...          1971
Fantasy                Das Cabinet des Dr. CaligariNosferatu          1920
Film-Noir   The Third ManThe Maltese FalconShadow of a Doubt          1941
Horror     PsychoAlienThe ThingThe ExorcistNight of the L...          1933
Mystery    MementoRear WindowVertigoShutter IslandKahaani...          1938
Thriller                                     Wait Until Dark          1967
Western    Il buono, il brutto, il cattivoOnce Upon a Tim...          1965

                                                                   Runtime  \
            max                                                sum     min
Genre
Action     2019  2008200320102001200219991980197719621954200019...      45
Adventure    PG  2014198520091981196819621959201319751963194819...      88
Animation  2020  2001199419882016201820172008199719952019200920...      71
Biography  2020  1993199020202011200220171995198420182013201320...      93
Comedy     2020  2019199719361931200919641940200120001973196019...      68
Crime      2019  1972197419571994200219991995199120192006199519...      80
Drama      2020  1994199919941975202019981946201420061998198819...      64
Family     1982                                           19821971     100
Fantasy    1922                                           19201922      76
Film-Noir  1949                                       194919411943     100
Horror     2017       19601979198219731968196120171978193320042001      71
Mystery    2012   200019541958201020121995197219381988201219981997      96
Thriller   1967                                               1967     108
Western    1976                                   1966196819651976     132

                      IMDB_Rating  ...  \
           max    sum         min  ...
Genre                              ...
Action     321  22196         7.6  ...
Adventure  228   9656         7.6  ...
Animation  137   8166         7.6  ...
Biography  209  11970         7.6  ...
Comedy     188  17380         7.6  ...
Crime      229  13524         7.6  ...
Drama      242  36049         7.6  ...
Family     115    215         7.8  ...
Fantasy     94    170         7.9  ...
Film-Noir  108    312         7.8  ...
Horror     122   1123         7.6  ...
Mystery    138   1429         7.6  ...
Thriller   108    108         7.8  ...
Western    165    593         7.8  ...

                                                       Star1 No_of_Votes  \
                                                         sum         min
Genre
Action     Christian BaleElijah WoodLeonardo DiCaprioElij...       25312
Adventure  Matthew McConaugheyMichael J. FoxBrad PittJürg...       29999
Animation  Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...       25229
Biography  Liam NeesonRobert De NiroLin-Manuel MirandaÉri...       27254
Comedy     Kang-ho SongRoberto BenigniCharles ChaplinChar...       26337
Crime      Marlon BrandoAl PacinoHenry FondaJohn Travolta...       27712
Drama      Tim RobbinsBrad PittTom HanksJack NicholsonSur...       25088
Family                               Henry ThomasGene Wilder      178731
Fantasy                             Werner KraussMax Schreck       57428
Film-Noir           Orson WellesHumphrey BogartTeresa Wright       59556
Horror     Anthony PerkinsSigourney WeaverKurt RussellEll...       27007
Mystery    Guy PearceJames StewartJames StewartLeonardo D...       33982
Thriller                                      Audrey Hepburn       27733
Western    Clint EastwoodHenry FondaClint EastwoodClint E...       65659

                                    Gross                             \
               max       sum          min          max           sum
Genre
Action     2303232  72282412       3296.0  936662225.0  3.263226e+10
Adventure  1512360  22576163      61001.0  874211619.0  9.496922e+09
Animation   999790  21978630     128985.0  873839108.0  1.463147e+10
Biography  1213505  24006844      21877.0  753585104.0  8.276358e+09
Comedy      939631  27620327       1305.0  886752933.0  1.566387e+10
Crime      1826188  33533615       6013.0  790482117.0  8.452632e+09
Drama      2343110  61367304       3600.0  924558264.0  3.540997e+10
Family      372490    551221    4000000.0  435110554.0  4.391106e+08
Fantasy      88794    146222  337574718.0  445151978.0  7.827267e+08
Film-Noir   158731    367215     449191.0  123353292.0  1.259105e+08
Horror      787806   3742556      89029.0  298791505.0  1.034649e+09
Mystery    1129894   4203004    1035953.0  474203697.0  1.256417e+09
Thriller     27733     27733   17550741.0   17550741.0  1.755074e+07
Western     688390   1289665    5321508.0   31800000.0  5.822151e+07

          Metascore
                min    max      sum
Genre
Action         33.0   98.0  10499.0
Adventure      41.0  100.0   5020.0
Animation      61.0   96.0   6082.0
Biography      48.0   97.0   6023.0
Comedy         45.0   99.0   9840.0
Crime          47.0  100.0   6706.0
Drama          28.0  100.0  19208.0
Family         67.0   91.0    158.0
Fantasy         NaN    NaN      0.0
Film-Noir      94.0   97.0    287.0
Horror         46.0   97.0    880.0
Mystery        52.0  100.0    633.0
Thriller       81.0   81.0     81.0
Western        69.0   90.0    313.0

[14 rows x 27 columns]

## list and dict together.

In [110]:
genres.agg(
    {
        'Runtime': ['min','max','median'],
        'IMDB_Rating': 'mean',
        'No_of_Votes': ['sum','count'],
        "Gross" : 'sum',
        "Metascore": 'min'
    }
)

          Runtime             IMDB_Rating No_of_Votes               Gross  \
              min  max median        mean         sum count           sum
Genre
Action         45  321  127.5    7.949419    72282412   172  3.263226e+10
Adventure      88  228  127.0    7.937500    22576163    72  9.496922e+09
Animation      71  137   99.5    7.930488    21978630    82  1.463147e+10
Biography      93  209  129.0    7.938636    24006844    88  8.276358e+09
Comedy         68  188  106.0    7.901290    27620327   155  1.566387e+10
Crime          80  229  122.0    8.016822    33533615   107  8.452632e+09
Drama          64  242  121.0    7.957439    61367304   289  3.540997e+10
Family        100  115  107.5    7.800000      551221     2  4.391106e+08
Fantasy        76   94   85.0    8.000000      146222     2  7.827267e+08
Film-Noir     100  108  104.0    7.966667      367215     3  1.259105e+08
Horror         71  122  103.0    7.909091     3742556    11  1.034649e+09
Mystery        96  138  117.5    7.975000     4203004    12  1.256417e+09
Thriller      108  108  108.0    7.800000       27733     1  1.755074e+07
Western       132  165  148.0    8.350000     1289665     4  5.822151e+07

          Metascore
                min
Genre
Action         33.0
Adventure      41.0
Animation      61.0
Biography      48.0
Comedy         45.0
Crime          47.0
Drama          28.0
Family         67.0
Fantasy         NaN
Film-Noir      94.0
Horror         46.0
Mystery        52.0
Thriller       81.0
Western        69.0

# looping on groups

In [118]:
for group,data in movies.groupby('Genre'):
    print(type(group),type(data))

<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>

In [117]:
for group,data in movies.groupby('Genre'):
    print(data)

                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

      Genre  IMDB_Rating           Director              Star1  No_of_Votes  \
2    Action          9.0  Christopher Nolan     Christian Bale      2303232
5    Action          8.9      Peter Jackson        Elijah Wood      1642758
8    Action          8.8  Christopher Nolan  Leonardo DiCaprio      2067042
10   Action          8.8      Peter Jackson        Elijah Wood      1661481
13   Action          8.7      Peter Jackson        Elijah Wood      1485555
..      ...          ...                ...                ...          ...
968  Action          7.6    Joel Schumacher    Michael Douglas       171640
979  Action          7.6     Richard Donner         Mel Gibson       236894
982  Action          7.6      George Miller         Mel Gibson       166588
983  Action          7.6        Walter Hill       Michael Beck        93878
985  Action          7.6         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2    534858444.0       84.0
5    377845905.0       94.0
8    292576195.0       74.0
10   315544750.0       92.0
13   342551365.0       87.0
..           ...        ...
968   40903593.0       56.0
979   65207127.0       68.0
982   12465371.0       77.0
983   22490039.0       65.0
985   43000000.0       76.0

[172 rows x 10 columns]
                       Series_Title Released_Year  Runtime      Genre  \
21                     Interstellar          2014      169  Adventure
47               Back to the Future          1985      116  Adventure
93             Inglourious Basterds          2009      153  Adventure
110                        Das Boot          1981      149  Adventure
114           2001: A Space Odyssey          1968      149  Adventure
..                              ...           ...      ...        ...
957  Fear and Loathing in Las Vegas          1998      118  Adventure
964                        Dead Man          1995      121  Adventure
966                       Apollo 13            PG      140  Adventure
984                The Muppet Movie          1979       95  Adventure
991                  Kelly's Heroes          1970      144  Adventure

     IMDB_Rating           Director                Star1  No_of_Votes  \
21           8.6  Christopher Nolan  Matthew McConaughey      1512360
47           8.5    Robert Zemeckis       Michael J. Fox      1058081
93           8.3  Quentin Tarantino            Brad Pitt      1267869
110          8.3  Wolfgang Petersen      Jürgen Prochnow       231855
114          8.3    Stanley Kubrick          Keir Dullea       603517
..           ...                ...                  ...          ...
957          7.6      Terry Gilliam          Johnny Depp       259753
964          7.6       Jim Jarmusch          Johnny Depp        90442
966          7.6         Ron Howard            Tom Hanks       269197
984          7.6      James Frawley           Jim Henson        32802
991          7.6    Brian G. Hutton       Clint Eastwood        45338

           Gross  Metascore
21   188020017.0       74.0
47   210609762.0       87.0
93   120540719.0       69.0
110   11487676.0       86.0
114   56954992.0       84.0
..           ...        ...
957   10680275.0       41.0
964    1037847.0       62.0
966  173837933.0       77.0
984   76657000.0       74.0
991    1378435.0       50.0

[72 rows x 10 columns]
                          Series_Title Released_Year  Runtime      Genre  \
23       Sen to Chihiro no kamikakushi          2001      125  Animation
43                       The Lion King          1994       88  Animation
46                      Hotaru no haka          1988       89  Animation
56                      Kimi no na wa.          2016      106  Animation
58   Spider-Man: Into the Spider-Verse          2018      117  Animation
..                                 ...           ...      ...        ...
956                              Mulan          1998       88  Animation
971                  Omohide poro poro          1991      118  Animation
976                 The Little Mermaid          1989       83  Animation
986                     Watership Down          1978       91  Animation
992                    The Jungle Book          1967       78  Animation

     IMDB_Rating             Director             Star1  No_of_Votes  \
23           8.6       Hayao Miyazaki     Daveigh Chase       651376
43           8.5         Roger Allers       Rob Minkoff       942045
46           8.5        Isao Takahata   Tsutomu Tatsumi       235231
56           8.4       Makoto Shinkai  Ryûnosuke Kamiki       194838
58           8.4      Bob Persichetti      Peter Ramsey       375110
..           ...                  ...               ...          ...
956          7.6        Tony Bancroft        Barry Cook       256906
971          7.6        Isao Takahata         Miki Imai        27071
976          7.6         Ron Clements       John Musker       237696
986          7.6         Martin Rosen       John Hubley        33656
992          7.6  Wolfgang Reitherman       Phil Harris       166409

           Gross  Metascore
23    10055859.0       96.0
43   422783777.0       88.0
46   150734678.0       94.0
56     5017246.0       79.0
58   190241310.0       87.0
..           ...        ...
956  120620254.0       71.0
971     453243.0       90.0
976  111543479.0       88.0
986  232841485.0       64.0
992  141843612.0       65.0

[82 rows x 10 columns]
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7     Schindler's List          1993      195  Biography          8.9
15          Goodfellas          1990      146  Biography          8.7
18            Hamilton          2020      160  Biography          8.6
35    The Intouchables          2011      112  Biography          8.5
38         The Pianist          2002      150  Biography          8.5
..                 ...           ...      ...        ...          ...
923     La Vie En Rose          2007      140  Biography          7.6
940  Finding Neverland          2004      106  Biography          7.6
949               Blow          2001      124  Biography          7.6
952      The Hurricane          1999      146  Biography          7.6
987   Midnight Express          1978      121  Biography          7.6

             Director               Star1  No_of_Votes        Gross  Metascore
7    Steven Spielberg         Liam Neeson      1213505   96898818.0       94.0
15    Martin Scorsese      Robert De Niro      1020727   46836394.0       90.0
18        Thomas Kail  Lin-Manuel Miranda        55291  440984783.0       90.0
35    Olivier Nakache       Éric Toledano       760360   13182281.0       57.0
38     Roman Polanski        Adrien Brody       729603   32572577.0       85.0
..                ...                 ...          ...          ...        ...
923     Olivier Dahan    Marion Cotillard        82781   10301706.0       66.0
940      Marc Forster         Johnny Depp       198677   51680613.0       67.0
949         Ted Demme         Johnny Depp       240714   52990775.0       52.0
952    Norman Jewison   Denzel Washington        91557   50668906.0       74.0
987       Alan Parker          Brad Davis        73662   35000000.0       59.0

[88 rows x 10 columns]
                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

      Genre  IMDB_Rating         Director            Star1  No_of_Votes  \
19   Comedy          8.6     Bong Joon Ho     Kang-ho Song       552778
26   Comedy          8.6  Roberto Benigni  Roberto Benigni       623629
51   Comedy          8.5  Charles Chaplin  Charles Chaplin       217881
52   Comedy          8.5  Charles Chaplin  Charles Chaplin       167839
64   Comedy          8.4  Rajkumar Hirani       Aamir Khan       344445
..      ...          ...              ...              ...          ...
977  Comedy          7.6     David Zucker   Leslie Nielsen       152871
978  Comedy          7.6      John Hughes     Steve Martin       124773
989  Comedy          7.6    Robert Altman    Elliott Gould        26337
994  Comedy          7.6   Richard Lester      John Lennon        40351
995  Comedy          7.6    Blake Edwards   Audrey Hepburn       166544

           Gross  Metascore
19    53367844.0       96.0
26    57598247.0       59.0
51      163245.0       96.0
52       19181.0       99.0
64     6532908.0       67.0
..           ...        ...
977   78756177.0       76.0
978   49530280.0       72.0
989     959000.0       87.0
994   13780024.0       96.0
995  679874270.0       76.0

[155 rows x 10 columns]
                Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1              The Godfather          1972      175  Crime          9.2
3     The Godfather: Part II          1974      202  Crime          9.0
4               12 Angry Men          1957       96  Crime          9.0
6               Pulp Fiction          1994      154  Crime          8.9
22            Cidade de Deus          2002      130  Crime          8.6
..                       ...           ...      ...    ...          ...
958              Funny Games          1997      108  Crime          7.6
960                 Sleepers          1996      147  Crime          7.6
974  The Godfather: Part III          1990      162  Crime          7.6
980             Blood Simple          1984       99  Crime          7.6
999             The 39 Steps          1935       86  Crime          7.6

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
3    Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4            Sidney Lumet     Henry Fonda       689845    4360000.0       96.0
6       Quentin Tarantino   John Travolta      1826188  107928762.0       94.0
22     Fernando Meirelles      Kátia Lund       699256    7563397.0       79.0
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058  217345863.0       69.0
960        Barry Levinson  Robert De Niro       186734   49100000.0       49.0
974  Francis Ford Coppola       Al Pacino       359809   66666062.0       60.0
980             Joel Coen      Ethan Coen        87745    2150000.0       82.0
999      Alfred Hitchcock    Robert Donat        51853  302787539.0       93.0

[107 rows x 10 columns]
                        Series_Title Released_Year  Runtime  Genre  \
0           The Shawshank Redemption          1994      142  Drama
9                         Fight Club          1999      139  Drama
11                      Forrest Gump          1994      142  Drama
17   One Flew Over the Cuckoo's Nest          1975      133  Drama
20                   Soorarai Pottru          2020      153  Drama
..                               ...           ...      ...    ...
990                     Giù la testa          1971      157  Drama
993                           Blowup          1966      111  Drama
996                            Giant          1956      201  Drama
997            From Here to Eternity          1953      118  Drama
998                         Lifeboat          1944       97  Drama

     IMDB_Rating                Director              Star1  No_of_Votes  \
0            9.3          Frank Darabont        Tim Robbins      2343110
9            8.8           David Fincher          Brad Pitt      1854740
11           8.8         Robert Zemeckis          Tom Hanks      1809221
17           8.7            Milos Forman     Jack Nicholson       918088
20           8.6           Sudha Kongara             Suriya        54995
..           ...                     ...                ...          ...
990          7.6            Sergio Leone        Rod Steiger        30144
993          7.6  Michelangelo Antonioni     David Hemmings        56513
996          7.6          George Stevens   Elizabeth Taylor        34075
997          7.6          Fred Zinnemann     Burt Lancaster        43374
998          7.6        Alfred Hitchcock  Tallulah Bankhead        26471

           Gross  Metascore
0     28341469.0       80.0
9     37030102.0       66.0
11   330252182.0       82.0
17   112000000.0       83.0
20   556832648.0        NaN
..           ...        ...
990     696690.0       77.0
993  632532802.0       82.0
996  195217415.0       84.0
997   30500000.0       85.0
998  852142728.0       78.0

[289 rows x 10 columns]
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy
568                     Nosferatu          1922       94  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0
568          7.9   F.W. Murnau    Max Schreck        88794  445151978.0

     Metascore
321        NaN
568        NaN
           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
309       The Third Man          1949      104  Film-Noir          8.1
456  The Maltese Falcon          1941      100  Film-Noir          8.0
712   Shadow of a Doubt          1943      108  Film-Noir          7.8

             Director            Star1  No_of_Votes        Gross  Metascore
309        Carol Reed     Orson Welles       158731     449191.0       97.0
456       John Huston  Humphrey Bogart       148928    2108060.0       96.0
712  Alfred Hitchcock    Teresa Wright        59556  123353292.0       94.0
                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
49                     Psycho          1960      109  Horror          8.5
75                      Alien          1979      117  Horror          8.4
271                 The Thing          1982      109  Horror          8.1
419              The Exorcist          1973      122  Horror          8.0
544  Night of the Living Dead          1968       96  Horror          7.9
707             The Innocents          1961      100  Horror          7.8
724                   Get Out          2017      104  Horror          7.7
844                 Halloween          1978       91  Horror          7.7
876         The Invisible Man          1933       71  Horror          7.7
932                       Saw          2004      103  Horror          7.6
948                The Others          2001      101  Horror          7.6

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211   32000000.0       97.0
75         Ridley Scott  Sigourney Weaver       787806   78900000.0       89.0
271      John Carpenter      Kurt Russell       371271   13782838.0       57.0
419    William Friedkin     Ellen Burstyn       362393  232906145.0       81.0
544    George A. Romero       Duane Jones       116557      89029.0       89.0
707        Jack Clayton      Deborah Kerr        27007    2616000.0       88.0
724        Jordan Peele    Daniel Kaluuya       492851  176040665.0       85.0
844      John Carpenter  Donald Pleasence       233106   47000000.0       87.0
876         James Whale      Claude Rains        30683  298791505.0       87.0
932           James Wan        Cary Elwes       379020   56000369.0       46.0
948  Alejandro Amenábar     Nicole Kidman       337651   96522687.0       74.0
          Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69             Memento          2000      113  Mystery          8.4
81         Rear Window          1954      112  Mystery          8.4
119            Vertigo          1958      128  Mystery          8.3
145     Shutter Island          2010      138  Mystery          8.2
220            Kahaani          2012      122  Mystery          8.1
393     Twelve Monkeys          1995      129  Mystery          8.0
420             Sleuth          1972      138  Mystery          8.0
714  The Lady Vanishes          1938       96  Mystery          7.8
829          Spoorloos          1988      107  Mystery          7.7
899          El cuerpo          2012      112  Mystery          7.6
959          Dark City          1998      100  Mystery          7.6
961       Lost Highway          1997      134  Mystery          7.6

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712   25544867.0
81       Alfred Hitchcock             James Stewart       444074   36764313.0
119      Alfred Hitchcock             James Stewart       364368    3200000.0
145       Martin Scorsese         Leonardo DiCaprio      1129894  128012934.0
220           Sujoy Ghosh               Vidya Balan        57806    1035953.0
393         Terry Gilliam              Bruce Willis       578443   57141459.0
420  Joseph L. Mankiewicz          Laurence Olivier        44748    4081254.0
714      Alfred Hitchcock         Margaret Lockwood        47400  474203697.0
829        George Sluizer  Bernard-Pierre Donnadieu        33982  367916835.0
899           Oriol Paulo             Jose Coronado        57549  140340673.0
959           Alex Proyas              Rufus Sewell       187927   14378331.0
961           David Lynch              Bill Pullman       131101    3796699.0

     Metascore
69        80.0
81       100.0
119      100.0
145       63.0
220        NaN
393       74.0
420        NaN
714       98.0
829        NaN
899        NaN
959       66.0
961       52.0
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore
700  Terence Young  Audrey Hepburn        27733  17550741.0       81.0

## solve the Ques 
find the highest rated movie of each genre

In [120]:
df = pd.DataFrame(columns=movies.columns)
df

Empty DataFrame
Columns: [Series_Title, Released_Year, Runtime, Genre, IMDB_Rating, Director, Star1, No_of_Votes, Gross, Metascore]
Index: []

In [125]:
df = pd.DataFrame(columns=movies.columns)

for group,data in movies.groupby('Genre'):
    #print(type(group),type(data))
    movies_df = (data[data['IMDB_Rating']== data['IMDB_Rating'].max()])
    df = pd.concat([df,movies_df])
df

C:\Users\sumit\AppData\Local\Temp\ipykernel_10988\58980011.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df,movies_df])

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

# apply -- builtin function
whenever you use groupby jab bhi aap apply func ka use kar raha hot ho you use this strategy
- split ,apply, combine 
- aap apply func ma apna custom 
logic function bhej sakta ho 
- split into groups
- apply the custom logic
- combine the groups

In [ ]:
genres = movies.groupby('Genre') # split into groups
genres.apply(min)  # har coloumn ma miniumum value nikal kar da raha ha

C:\Users\sumit\AppData\Local\Temp\ipykernel_10988\640834237.py:2: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genres.apply(min)
C:\Users\sumit\AppData\Local\Temp\ipykernel_10988\640834237.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

## find number of movies starting with A for each group
har particular genre ma kitni movies ha jo A sa start hoti ha

In [133]:
def foo(group): # tho hamara func ko input ma dataframe mil rha ha 
    return group['Series_Title'].str.startswith('A').sum()

In [134]:
genres.apply(foo)

C:\Users\sumit\AppData\Local\Temp\ipykernel_10988\2904676014.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

## find ranking of each movie in the group according to IMDB score
huma rank dena khud ka genre ma konsa rank ha . 
example the dark knight ek action movie ma muja usko rank dena uska khud ka group by ma based on imbd rating . 
har group ka alag rank hoga based on imbd rating

In [141]:
def rank_movie(group ):
    group['genre_rank'] = group['IMDB_Rating'].rank(ascending = False)
    return group

In [142]:
genres.apply(rank_movie)

C:\Users\sumit\AppData\Local\Temp\ipykernel_10988\2409710219.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              genre_rank
Genre
Action   2           1.0
         5           2.0
         8           3.5
         10          3.5
         13          6.0
...                  ...
Thriller 700         1.0
Western  12          1.0
         48          2.0
         115         3.0
         691         4.0

[1000 rows x 11 columns]

## find normalized IMDB rating group wise

$ normalised-score = \frac{x - x_{min}}{x_{max}-x_{min}}$

In [ ]:
# aap har ek group ka basis par analysis karna chata ho 
# example india level par exam hua aap har state ma kitna rank aya bacha ka ya dekna chata ho

In [ ]:
def normal(group):
    # apply the normalising formula 
    group['normal_rating'] = round((group['IMDB_Rating'] - group['IMDB_Rating'].min())/(group['IMDB_Rating'].max()- group['IMDB_Rating'].min()),2)
    return group

In [150]:
genres.apply(normal)

C:\Users\sumit\AppData\Local\Temp\ipykernel_10988\1987004062.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              normal_rating
Genre
Action   2             1.00
         5             0.93
         8             0.86
         10            0.86
         13            0.79
...                     ...
Thriller 700            NaN
Western  12            1.00
         48            0.70
         115           0.50
         691           0.00

[1000 rows x 11 columns]

# groupby on multiple cols
abhi hum ek cateogorical coloumn ka basis par groupby kar raha tha . genre,actor,director ka upar  hum chaya tho hum multiple categorical  coloumns ka basis par bhi group by laga sakta ha

In [159]:
duo = movies.groupby(['Director','Star1',])
#duo.size()
duo

In [156]:
# example aap chata ho two categorical coloumns 
# ka basis par group by karna chata ho
# acator and director ka bais ka upar
duo = movies.groupby(['Director','Star1',])
# duo.size() # so their are 898 combination of director and actor 
duo.get_group(('Aamir Khan','Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

## find the most earning actor -- director combo

In [162]:
duo['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

## find the best(in-terms of metascore(avg)) actor -- genre combo
konsa actor and genre ka best combination ha

In [177]:
movies.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values(by='Metascore',ascending=False).head(1)

              Star1  Genre  Metascore
230  Ellar Coltrane  Drama      100.0

In [170]:
movies.groupby(['Star1','Genre'])['Metascore'].mean().reset_index()

                    Star1      Genre  Metascore
0              Aamir Khan     Action        NaN
1              Aamir Khan  Adventure       84.0
2              Aamir Khan     Comedy       67.0
3    Aaron Taylor-Johnson     Action       66.0
4              Abhay Deol      Drama        NaN
..                    ...        ...        ...
824  Zbigniew Zamachowski     Comedy       88.0
825       Zooey Deschanel     Comedy       76.0
826        Çetin Tekindor      Drama        NaN
827         Éric Toledano  Biography       57.0
828      Ömer Faruk Sorak     Comedy        NaN

[829 rows x 3 columns]

## agg on multiple groupby

In [ ]:
duo.agg(['min','max','count'])

                                                  Series_Title  \
                                                           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab
Abhishek Kapoor     Amit Sadh                      Kai po che!
...                                                        ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara
                    Vijay Varma                      Gully Boy
Çagan Irmak         Çetin Tekindor              Babam ve Oglum
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.

                                                                      \
                                                           max count
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par     1
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7     1
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle     1
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab     1
Abhishek Kapoor     Amit Sadh                      Kai po che!     1
...                                                        ...   ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid     1
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara     1
                    Vijay Varma                      Gully Boy     1
Çagan Irmak         Çetin Tekindor              Babam ve Oglum     1
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.     1

                                   Released_Year             Runtime       \
                                             min   max count     min  max
Director            Star1
Aamir Khan          Amole Gupte             2007  2007     1     165  165
Aaron Sorkin        Eddie Redmayne          2020  2020     1     129  129
Abdellatif Kechiche Léa Seydoux             2013  2013     1     180  180
Abhishek Chaubey    Shahid Kapoor           2016  2016     1     148  148
Abhishek Kapoor     Amit Sadh               2013  2013     1     130  130
...                                          ...   ...   ...     ...  ...
Zaza Urushadze      Lembit Ulfsak           2013  2013     1      87   87
Zoya Akhtar         Hrithik Roshan          2011  2011     1     155  155
                    Vijay Varma             2019  2019     1     154  154
Çagan Irmak         Çetin Tekindor          2005  2005     1     112  112
Ömer Faruk Sorak    Cem Yilmaz              2004  2004     1     127  127

                                              Genre  ... IMDB_Rating  \
                                   count        min  ...       count
Director            Star1                            ...
Aamir Khan          Amole Gupte        1      Drama  ...           1
Aaron Sorkin        Eddie Redmayne     1      Drama  ...           1
Abdellatif Kechiche Léa Seydoux        1      Drama  ...           1
Abhishek Chaubey    Shahid Kapoor      1     Action  ...           1
Abhishek Kapoor     Amit Sadh          1      Drama  ...           1
...                                  ...        ...  ...         ...
Zaza Urushadze      Lembit Ulfsak      1      Drama  ...           1
Zoya Akhtar         Hrithik Roshan     1     Comedy  ...           1
                    Vijay Varma        1      Drama  ...           1
Çagan Irmak         Çetin Tekindor     1      Drama  ...           1
Ömer Faruk Sorak    Cem Yilmaz         1  Adventure  ...           1

                                   No_of_Votes                      Gross  \
                                           min     max count          min
Director            Star1
Aamir Khan          Amole Gupte         168895  168895     1    1223869.0
Aaron Sorkin        Eddie Redmayne       89896   89896     1  853090410.0
Abdellatif Kechiche Léa Seydoux         138741  138741     1    2199675.0
Abhishek Chaubey    Shahid Kapoor        27175   27175     1  218428303.0
Abhishek Kapoor     Amit Sadh            32628   32628     1    1122527.0
...                                        ...     ...   ...          ...
Zaza Urushadze      Lembit Ulfsak        40382   40382     1     144501.0
Zoya Akhtar         Hrithik Roshan       67927   67927     1    3108485.0
                    Vijay Varma          31886   31886     1    5566534.0
Çagan Irmak         Çetin Tekindor       78925   78925     1  461855363.0
Ömer Faruk Sorak    Cem Yilmaz           56960   56960     1  196206077.0

                                                      Metascore
                                            max count       min   max count
Director            Star1
Aamir Khan          Amole Gupte       1223869.0     1       NaN   NaN     0
Aaron Sorkin        Eddie Redmayne  853090410.0     1      77.0  77.0     1
Abdellatif Kechiche Léa Seydoux       2199675.0     1      89.0  89.0     1
Abhishek Chaubey    Shahid Kapoor   218428303.0     1       NaN   NaN     0
Abhishek Kapoor     Amit Sadh         1122527.0     1      40.0  40.0     1
...                                         ...   ...       ...   ...   ...
Zaza Urushadze      Lembit Ulfsak      144501.0     1      73.0  73.0     1
Zoya Akhtar         Hrithik Roshan    3108485.0     1       NaN   NaN     0
                    Vijay Varma       5566534.0     1      65.0  65.0     1
Çagan Irmak         Çetin Tekindor  461855363.0     1       NaN   NaN     0
Ömer Faruk Sorak    Cem Yilmaz      196206077.0     1       NaN   NaN     0

[898 rows x 24 columns]

In [ ]:
# apply also work same

# Exercise

In [2]:
import pandas as pd
ipl = pd.read_csv('deliveries.csv')
ipl

,(match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [ ]:
ipl.shape
# ya ball by ball data ipl ma 
# crik info crikbuzz is tara ka data rakta ha

(179078, 21)

In [190]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   (match_id         179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
dtypes: int64(13), object(8)
memory usage: 28.7+ MB

In [188]:
ipl.columns

Index(['(match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

###  find the top 10 batsman in terms of runs

In [ ]:
# group the ipl data based on batsman

In [191]:
ipl.groupby(by='batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

###  find the batsman with max no of sixes

In [198]:
sixs = ipl[ipl['batsman_runs'] == 6]
sixs.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(1)

batsman
CH Gayle    327
Name: batsman, dtype: int64

### find batsman with most number of 4's and 6's in last 5 overs

In [3]:
# all conditions 
ipl['batsman_runs']== 6 # bastman na 6 run score kiya 
ipl['batsman_runs']== 4  # bastman na 4 run score kiya 
ipl['over'] > 15 # over last 5 yani 16 sa 20

0         False
1         False
2         False
3         False
4         False
          ...
179073     True
179074     True
179075     True
179076     True
179077     True
Name: over, Length: 179078, dtype: bool

In [ ]:

overs = ipl['over'] > 15
fours_and_sixs = (ipl['batsman_runs']== 4) | (ipl['batsman_runs']== 6)
comb_condition = overs & fours_and_sixs 
temp_df = ipl[comb_condition]
temp_df.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(10)

batsman
MS Dhoni          340
AB de Villiers    208
RG Sharma         208
KA Pollard        206
V Kohli           160
YK Pathan         149
KD Karthik        145
Yuvraj Singh      130
AD Russell        129
AT Rayudu         114
Name: batsman, dtype: int64

### find V Kohli's record against all teams

In [ ]:
# filter the data uni rows ko jisma batsma virat kohli ha 
temp_df = ipl[ipl['batsman'] =='V Kohli']
# virat kohli na kitna run banya against team
temp_df.groupby(by='bowling_team')['batsman_runs'].sum().reset_index()
# agar ma ya batu har team ka against kitna 6's or 4's mara.

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [216]:
ipl.columns

Index(['(match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

### Create a function that can return the highest score of any batsman

In [ ]:
temp_df

In [23]:
# filter the rows by batsman
temp_df = ipl[ipl['batsman'] =='V Kohli']
temp_df.groupby('(match_id')['batsman_runs'].sum().sort_values(ascending=False).values[0]

113

In [25]:
def highest_score(batsman):
    temp_df = ipl[ipl['batsman'] == batsman]
    return temp_df.groupby('(match_id')['batsman_runs'].sum().sort_values(ascending=False).values[0]

In [26]:
highest_score(batsman='V Kohli')

113

In [29]:
highest_score(batsman='DA Warner')

126

In [30]:
highest_score('MS Dhoni')

89

# Notes

Both **Pandas joins** and **SQL joins** are based on the principles of **set theory**, particularly operations on sets such as **union, intersection, and difference**. Let’s break this down in terms of **set theory**:

---

### **1️⃣ INNER JOIN → Intersection (A ∩ B)**
- **Concept**: Returns only the matching rows between two datasets.
- **Set Theory Equivalent**: The **intersection** of two sets.
- **Example**:
  - SQL: `SELECT * FROM A INNER JOIN B ON A.id = B.id`
  - Pandas: `df1.merge(df2, on="id", how="inner")`
  
#### **Set Notation**:
\[
A \cap B = \{ x \mid x \in A \text{ and } x \in B \}
\]

#### **Venn Diagram**:
```
     +---------+
     |   A ∩ B  |  <-- Only common elements
     +---------+
```

---

### **2️⃣ LEFT JOIN → Left Set with Intersection (A ∪ (A ∩ B))**
- **Concept**: Returns all rows from the left dataset and only matching rows from the right dataset.
- **Set Theory Equivalent**: The **union of set A and the intersection (A ∩ B)**.
- **Example**:
  - SQL: `SELECT * FROM A LEFT JOIN B ON A.id = B.id`
  - Pandas: `df1.merge(df2, on="id", how="left")`

#### **Set Notation**:
\[
A \cup (A \cap B) = A
\]

#### **Venn Diagram**:
```
    +----------+
    |    A     | <-- Includes all of A
    |  A ∩ B   | <-- Matching elements from B
    +----------+
```

---

### **3️⃣ RIGHT JOIN → Right Set with Intersection (B ∪ (A ∩ B))**
- **Concept**: Returns all rows from the right dataset and only matching rows from the left dataset.
- **Set Theory Equivalent**: The **union of set B and the intersection (A ∩ B)**.
- **Example**:
  - SQL: `SELECT * FROM A RIGHT JOIN B ON A.id = B.id`
  - Pandas: `df1.merge(df2, on="id", how="right")`

#### **Set Notation**:
\[
B \cup (A \cap B) = B
\]

#### **Venn Diagram**:
```
    +----------+
    |    B     | <-- Includes all of B
    |  A ∩ B   | <-- Matching elements from A
    +----------+
```

---

### **4️⃣ FULL OUTER JOIN → Union (A ∪ B)**
- **Concept**: Returns all rows from both datasets, with `NULLs` where no match is found.
- **Set Theory Equivalent**: The **union of both sets**.
- **Example**:
  - SQL: `SELECT * FROM A FULL OUTER JOIN B ON A.id = B.id`
  - Pandas: `df1.merge(df2, on="id", how="outer")`

#### **Set Notation**:
\[
A \cup B = \{ x \mid x \in A \text{ or } x \in B \}
\]

#### **Venn Diagram**:
```
    +---------+
    |  A ∪ B  | <-- Includes all elements from A and B
    +---------+
```

---

### **5️⃣ LEFT ANTI JOIN → A - (A ∩ B)**
- **Concept**: Returns rows from the left dataset that **do not** have a match in the right dataset.
- **Set Theory Equivalent**: **Set difference**.
- **Example**:
  - SQL: `SELECT * FROM A WHERE A.id NOT IN (SELECT id FROM B)`
  - Pandas: `df1.merge(df2, on="id", how="left", indicator=True).query('_merge == "left_only"').drop('_merge', axis=1)`

#### **Set Notation**:
\[
A - B = \{ x \mid x \in A \text{ and } x \notin B \}
\]

#### **Venn Diagram**:
```
    +------+
    |  A   | <-- Only elements in A, not in B
    +------+
```

---

### **6️⃣ RIGHT ANTI JOIN → B - (A ∩ B)**
- **Concept**: Returns rows from the right dataset that **do not** have a match in the left dataset.
- **Set Theory Equivalent**: **Set difference**.
- **Example**:
  - SQL: `SELECT * FROM B WHERE B.id NOT IN (SELECT id FROM A)`
  - Pandas: `df1.merge(df2, on="id", how="right", indicator=True).query('_merge == "right_only"').drop('_merge', axis=1)`

#### **Set Notation**:
\[
B - A = \{ x \mid x \in B \text{ and } x \notin A \}
\]

#### **Venn Diagram**:
```
    +------+
    |  B   | <-- Only elements in B, not in A
    +------+
```

---

### **Final Comparison Table**
| Join Type | SQL Query | Pandas Syntax | Set Theory Equivalent |
|-----------|----------|--------------|------------------------|
| **INNER JOIN** | `SELECT * FROM A INNER JOIN B ON A.id = B.id` | `df1.merge(df2, on="id", how="inner")` | **Intersection (A ∩ B)** |
| **LEFT JOIN** | `SELECT * FROM A LEFT JOIN B ON A.id = B.id` | `df1.merge(df2, on="id", how="left")` | **A with intersection (A ∪ (A ∩ B))** |
| **RIGHT JOIN** | `SELECT * FROM A RIGHT JOIN B ON A.id = B.id` | `df1.merge(df2, on="id", how="right")` | **B with intersection (B ∪ (A ∩ B))** |
| **FULL OUTER JOIN** | `SELECT * FROM A FULL OUTER JOIN B ON A.id = B.id` | `df1.merge(df2, on="id", how="outer")` | **Union (A ∪ B)** |
| **LEFT ANTI JOIN** | `SELECT * FROM A WHERE A.id NOT IN (SELECT id FROM B)` | `df1.merge(df2, on="id", how="left", indicator=True).query('_merge == "left_only"')` | **Set difference (A - B)** |
| **RIGHT ANTI JOIN** | `SELECT * FROM B WHERE B.id NOT IN (SELECT id FROM A)` | `df1.merge(df2, on="id", how="right", indicator=True).query('_merge == "right_only"')` | **Set difference (B - A)** |

---

### **Summary**
- SQL and Pandas **joins** are fundamentally based on **set operations**.
- **INNER JOIN** is equivalent to **intersection (A ∩ B)**.
- **LEFT JOIN** and **RIGHT JOIN** keep one full set and its intersection with the other.
- **FULL OUTER JOIN** is equivalent to **union (A ∪ B)**.
- **LEFT ANTI JOIN** and **RIGHT ANTI JOIN** are **set differences (A - B, B - A)**.

Understanding **joins through set theory** makes it easier to visualize and apply them in both **SQL and Pandas**. Let me know if you need **diagrams or deeper explanations**! 🚀