# Create Dataframe

What is DataFrame
- so whenever you have tablour Data
- Matrix , Table(Rows and columns )
- Collection of Series /1d array

table ko Dataframe bhula jata ha 
uska ek row ko bhi series bhula jata ha aor ek column ko bhi Series bhula jata ha

### using list

In [1]:
# agar apko Dataframe bana ha tho usma 2d list apko chaya
# we create a dataframe with list of student data
# 4 student ha unka iq,marks ,package

In [2]:
import numpy as np 
import pandas as pd
student_data = [
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
]
pd.DataFrame(student_data,columns=['iq','marks','package'])

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

### using dict

In [3]:
# same Data but using Dictionary

In [4]:
student_dict = {
    'iq': [100,90,120,80,0,0],
    'marks': [80,70,100,50,0,0],
    'package': [10,7,14,2,0,0]
}
students = pd.DataFrame(data=student_dict)
students

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
4    0      0        0
5    0      0        0

In [5]:
# Generally aap Dataframe create nahi import karta ho

### using read_csv

In [6]:
movies = pd.read_csv('movies.csv')
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [7]:
# ipl dataset of in 2008

In [8]:
ipl = pd.read_csv('ipl-matches.csv')
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

# DataFrame Attributes

## shape
kitna number of rows and kitna numbers of columns ha

In [9]:
movies.shape
# 1629 mera pass  movie ha  rows 
# aor 18 columns ma hamra divided ha

(1629, 18)

In [10]:
ipl.shape
# total 950 mathces ha vo 20 columns ma information  divided ha
# tho agar apsa koi pucha ipl ma abhi tak total kitna matches  hua ha answer on 
# your screen

(950, 20)

## dtypes
jasa series ma vo dtype bta deta vasa hi Dataframe ma bhi yadi apko  dtypes dekna ha tho use it

In [11]:
movies.dtypes
# dataframe ma har ek coloumns ka datatype kiya

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [12]:
ipl.dtypes
# dataframe collection of Series (coloumsns)
# tho har ek series ka data type kiya

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

## index
pandas ek khud sa index da deta ha har ek rows and coloumns ko

In [13]:
movies.index

RangeIndex(start=0, stop=1629, step=1)

In [14]:
ipl.index

RangeIndex(start=0, stop=950, step=1)

## columns 
ya muja mera dataframe ma sa sara coloumns nikal kar deta ha

In [15]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [16]:
ipl.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

In [17]:
students.columns # type: ignore

Index(['iq', 'marks', 'package'], dtype='object')

## values 
aap apna dataframe ki values ko fetch kiya fir apko deka diya 
ya ek 2d numpy array hoga

In [18]:
students.values # type: ignore

array([[100,  80,  10],
       [ 90,  70,   7],
       [120, 100,  14],
       [ 80,  50,   2],
       [  0,   0,   0],
       [  0,   0,   0]], dtype=int64)

In [19]:
movies.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']], dtype=object)

# Dataframe methods

## head and tail 
top 5 rows and last 5 rows dekna ka liya 
yani overiew of data lena ka liya

In [20]:
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [21]:
# last 2 mathces in ipl
ipl.tail(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

## sample
ya muja randomly rows nikal kar deta ha mera df ma sa 
taki bias na ho

In [22]:
movies.sample()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
667,Staying Alive (2012 film),tt2188893,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Staying_Alive_(2...,Staying Alive,Staying Alive,0,2012,89,Drama,5.7,26,A newspaper sub-editor Aditya (Ananth Mahadev...,A newspaper sub-editor Aditya (Ananth Mahadev...,NaN,Jahangir Khan|Ananth Narayan Mahadevan|Navni P...,NaN,3 February 2012 (India)

In [23]:
# take a sample of 5 random ipl matches
ipl.sample(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
399,980967,Hyderabad,2016-05-06,2016,34,Sunrisers Hyderabad,Gujarat Lions,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,5.0,NaN,B Kumar,"['DA Warner', 'S Dhawan', 'KS Williamson', 'MC...","['DR Smith', 'BB McCullum', 'SK Raina', 'KD Ka...",M Erasmus,S Ravi
81,1254094,Dubai,2021-10-07,2021,53,Chennai Super Kings,Punjab Kings,Dubai International Cricket Stadium,Punjab Kings,field,N,Punjab Kings,Wickets,6.0,NaN,KL Rahul,"['RD Gaikwad', 'F du Plessis', 'MM Ali', 'RV U...","['KL Rahul', 'MA Agarwal', 'SN Khan', 'M Shahr...",K Srinivasan,RK Illingworth
421,980923,Hyderabad,2016-04-18,2016,12,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,7.0,NaN,DA Warner,"['DA Warner', 'S Dhawan', 'MC Henriques', 'EJG...","['MJ Guptill', 'PA Patel', 'AT Rayudu', 'RG Sh...",HDPK Dharmasena,VK Sharma
462,829767,Delhi,2015-05-01,2015,31,Delhi Daredevils,Kings XI Punjab,Feroz Shah Kotla,Delhi Daredevils,field,N,Delhi Daredevils,Wickets,9.0,NaN,NM Coulter-Nile,"['MA Agarwal', 'SS Iyer', 'SS Tiwary', 'JP Dum...","['V Sehwag', 'M Vohra', 'SE Marsh', 'WP Saha',...",RK Illingworth,S Ravi
144,1216537,Abu Dhabi,2020-10-30,2020/21,50,Kings XI Punjab,Rajasthan Royals,Sheikh Zayed Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,BA Stokes,"['KL Rahul', 'Mandeep Singh', 'CH Gayle', 'N P...","['RV Uthappa', 'BA Stokes', 'SV Samson', 'SPD ...",CB Gaffaney,S Ravi

## info
ya apko high level overview deta ha data ka 
bhut tara ka information apko ek sath dekai dega
- coloumn name
- kitni missing values nahi ha
- coloumn ka data type 
- kitni float,int ,obj data type ha 
- ram ma kitna memory la raha ha

In [24]:
movies.info()
# not null matlab vo values jo missing nahi ha 
# deko relase date ma kuch values missing ha

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [25]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

## Describe
ek mathametical summary dena ka kam ata ha apka df ma numerical coloumn ko detech karka unka upar operate kar jata ha 
- count = not null values 
- mean = central tendacy of data (balancing point)
- std =  dispersion of data (spread kitna ha )
- min = minimum value of data
- 25 % = yani 25 percent values is sa picha ha 
- 50 % = yani 50  percent values is sa picha ha(median)
- 75 % = yani 75  percent values is sa picha ha
- max = maximu values in data

In [26]:
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [27]:
# 25 percent movies asi ha jinka rating 4.4 ya ussa kam ha
# 50 percent movies asi ha jinka rating 5.6 ya  ussa kam ha-> median 
# 75 percent movies asi ha jinka rating less than 6.8

In [28]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

## isnull
ya apko bata ha ki data ma missing value ha ki nahi 
- false matlab waha missing value nahi ha
- True matlab waha missing value ha

In [29]:
movies.isnull()# it gives us a boolean dataframe lakin not much useful
movies.isnull().sum() # isna True value yani 1 ko add kar diya

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [30]:
# now we know the information ki 
# 103 movies ka path missing 
# 20 movies ka koi story nahi ha
# 5 movies ma actors ka nahi pata .

## duplicated 
repeated data yani duplicated data ka koi point ha same information repeat it
- kiya koi row repeat ho raha ha  
- false matlab vo duplicate nahi hua unique value 
- True matlab vo duplicate ha repat hua ha second time aya ha

In [31]:
movies.duplicated() # -> a boolean dataframe 
movies.duplicated().sum() # count all the duplicate values

0

In [32]:
ipl.duplicated().sum()

0

In [33]:
student_dict = {
    'iq': [100,90,120,80,0,0],
    'marks': [80,70,100,50,0,0],
    'package': [10,7,14,2,0,0]
}
students = pd.DataFrame(data=student_dict)
students

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
4    0      0        0
5    0      0        0

In [34]:
students.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [35]:
students.duplicated().sum()

1

## rename
ya apka coloumn ka name change kar deta ha

In [36]:
students

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
4    0      0        0
5    0      0        0

In [37]:
# example students ma hum marks ko --> percentage
# or  package ko lpa

In [38]:
students.rename(columns={
    "marks":'perecentage',
    "package": 'LPA'
})
# pass a dictionary in the rename func in col parameter
# col = {'original name':"new name "}

    iq  perecentage  LPA
0  100           80   10
1   90           70    7
2  120          100   14
3   80           50    2
4    0            0    0
5    0            0    0

In [39]:
# lakin ya view ha permenat changes nahi ha 
students.rename(columns={"marks":'perecentage',"package": 'LPA',},inplace=True)
students

    iq  perecentage  LPA
0  100           80   10
1   90           70    7
2  120          100   14
3   80           50    2
4    0            0    0
5    0            0    0

# DF Math Methods

## sum
sum  in df row wise(axis = 1) and col wise(axis = 0)

In [40]:
students

    iq  perecentage  LPA
0  100           80   10
1   90           70    7
2  120          100   14
3   80           50    2
4    0            0    0
5    0            0    0

In [41]:
students.sum() # defualt axis = 0 meaning perform operation top to down
# coloumn wise e

iq             390
perecentage    300
LPA             33
dtype: int64

In [42]:
# each student marks total
students.sum(axis=1)

0    190
1    167
2    234
3    132
4      0
5      0
dtype: int64

In [43]:
# this can generalise to all math methods in dataframe

## mean

In [44]:
# Ques : what is the average of all class
students.mean()

iq             65.0
perecentage    50.0
LPA             5.5
dtype: float64

In [45]:
# Ques: what is the avg of each student
students.mean(axis=1)

0    63.333333
1    55.666667
2    78.000000
3    44.000000
4     0.000000
5     0.000000
dtype: float64

## max 
maximum value in df row wise and col wise

In [46]:
students.max()

iq             120
perecentage    100
LPA             14
dtype: int64

In [47]:
students.max(axis=1)

0    100
1     90
2    120
3     80
4      0
5      0
dtype: int64

In [48]:
# highest score of the movie
movies['imdb_rating'].max()

9.4

## min
minimum value in df row wise and col wise

## all statsical methods
mean ,median ,std,var,skewness,kurtosis,max,min

# select col from DF
how can you Read, access single or multiple coloumns from a Dataframe

### single columns 
select the single coloumns like indexing(list,str,numpy) in python it's like dictionary key value pair  dict_name['key'] = value 
- Dataframe["coloumn name"]

In [49]:
# example I want to see the names of the movies
# it will give you Series object  
movies['title_x']

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: object

In [50]:
## kon kon sa stadium ma aaj tak matches hua ha 
ipl["Venue"]

0                Narendra Modi Stadium, Ahmedabad
1                Narendra Modi Stadium, Ahmedabad
2                           Eden Gardens, Kolkata
3                           Eden Gardens, Kolkata
4                        Wankhede Stadium, Mumbai
                          ...
945                                  Eden Gardens
946                              Wankhede Stadium
947                              Feroz Shah Kotla
948    Punjab Cricket Association Stadium, Mohali
949                         M Chinnaswamy Stadium
Name: Venue, Length: 950, dtype: object

### multiple coloumns 
we use the fancy indexing concept passes a list what coloumns you want to extract. 
output subset  will a Dataframe

In [51]:
# we want to know movie name, relase data,actors
# remember whatever order you pass coloumn they will appera in the 
# same order like this 

movies.columns
movies[['title_x','year_of_release','actors']]

,title_x,year_of_release,actors
0,Uri: The Surgical Strike,2019,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1,Battalion 609,2019,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2,The Accidental Prime Minister (film),2019,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3,Why Cheat India,2019,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4,Evening Shadows,2018,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...,...,...,...
1624,Tera Mera Saath Rahen,2001,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625,Yeh Zindagi Ka Safar,2001,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626,Sabse Bada Sukh,2018,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627,Daaka,2019,Gippy Grewal|Zareen Khan|
1628,Humsafar,2011,Fawad Khan|

In [52]:
# ipl match ma konsi team thi aor jeta ko ,team 1 team 2
ipl.columns
ipl[['Team1','Team2','WinningTeam']]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

# select rows from DF
- **iloc** - searches using index position 
- **loc** - searches using index label

## iloc

### single row 
it's like indexing see the one element at one time

In [53]:
# Q: select the first movie
# so each row is also a Series 
movies.iloc[0]

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object

In [54]:
# Q: fifth ipl ki details batao
ipl.iloc[5]

ID                                                           1304115
City                                                          Mumbai
Date                                                      2022-05-21
Season                                                          2022
MatchNumber                                                       69
Team1                                                 Delhi Capitals
Team2                                                 Mumbai Indians
Venue                                       Wankhede Stadium, Mumbai
TossWinner                                            Mumbai Indians
TossDecision                                                   field
SuperOver                                                          N
WinningTeam                                           Mumbai Indians
WonBy                                                        Wickets
Margin                                                           5.0
method                                                           NaN
Player_of_Match                                            JJ Bumrah
Team1Players       ['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...
Team2Players       ['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...
Umpire1                                                  Nitin Menon
Umpire2                                                 Tapan Sharma
Name: 5, dtype: object

### multiple row 
it's like slicing  it have two rules
- start :stop: step whai tak jayega otherwise default position par hoga

In [55]:
# Q: see the first five movies
movies.iloc[0:5]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

### fancy indexing 
passes a list of indices you want to extract

In [56]:
# Q: suppose  you need 0 ,4 and 5th movie
movies.iloc[[0,4,5]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)

## loc
Accesing items/rows using labels

### single row label
access fetch one item

In [57]:
student_dict = {
    "name":['manish','anand','piyush','ayush','aryaveer','sachin'],
    'iq': [100,90,120,80,0,0],
    'marks': [80,70,100,50,0,0],
    'package': [10,7,14,2,0,0]
}
students = pd.DataFrame(data=student_dict)
students.set_index('name',inplace=True)
# you can set index as your coloumns 
students

           iq  marks  package
name
manish    100     80       10
anand      90     70        7
piyush    120    100       14
ayush      80     50        2
aryaveer    0      0        0
sachin      0      0        0

In [58]:
# Q: I want to know information about piyus 
students.loc['piyush']

iq         120
marks      100
package     14
Name: piyush, dtype: int64

### multiple row labels 
using slicing

In [59]:
students.loc['anand':'aryaveer']
# start : stop 
# observe one last item is included

           iq  marks  package
name
anand      90     70        7
piyush    120    100       14
ayush      80     50        2
aryaveer    0      0        0

In [60]:
students.loc['manish':'aryaveer':2]

           iq  marks  package
name
manish    100     80       10
piyush    120    100       14
aryaveer    0      0        0

### fancy indexing

In [61]:
students.loc[['anand','piyush','manish']]

         iq  marks  package
name
anand    90     70        7
piyush  120    100       14
manish  100     80       10

### concept point
deko humna aapna index provide kiya ha students df ma lakin iska matlab ya nahi ki aap iloc use nahi kar sakta aap chaho tho use kar sakta ho

In [62]:
students.iloc[0] # this is marks of manish

iq         100
marks       80
package     10
Name: manish, dtype: int64

In [63]:
students.iloc[0::2]

           iq  marks  package
name
manish    100     80       10
piyush    120    100       14
aryaveer    0      0        0

In [64]:
students.iloc[[0,3,4]]

           iq  marks  package
name
manish    100     80       10
ayush      80     50        2
aryaveer    0      0        0

# select both rows and coloumns 
use concept of 2d indexing or slicing 
- iloc always provide index position 
- loc always provide the name

## iloc

In [65]:
# using iloc find first 3 movies an and first 3 col.
movies.iloc[0:3,0:3] # rows: col

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

## loc

In [66]:
# now using loc lables by names
movies.loc[0:3,'title_x':'poster_path'] # rows: col

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...

In [67]:
# slcing using label 
students.loc['manish':'aryaveer','iq':'marks']

           iq  marks
name
manish    100     80
anand      90     70
piyush    120    100
ayush      80     50
aryaveer    0      0

## summary 
their are two types of Indexing
- **iloc** - first that uses internally by pandas index position
- **loc** - second that uses by user externally define apna banya gaya  names labels

In [68]:
# iloc for index
# loc for labels 
# simple concept

# filtering a DF
Based on given condition you have to apply the logic on that and filter the dataframe

In [69]:
# so we have to solve the Question and built the understanding of
# filtering a dataframe you use a lot in Data science journey

### find all the winning team in the ipl finals 
har season ma kon si ipl team na jita ha

In [70]:
# Thinking about the promblem
# season col ma year lika ha 
# matchnumber ma final,semifinal Quater lika ha 
# fir wining team ko fetch karaga 

# tho we are asking the match number is final 
# it gives us boolean 
mask = ipl['MatchNumber'] =='Final'
new_df = ipl[mask]
new_df
new_df[['Season','WinningTeam']]
# final wiiner in each season of iple

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [71]:
# one line solution 
ipl[ipl['MatchNumber'] == 'Final'][['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

### out of all ipl mathces how many ipl matches have super over
agar team 1 na super 100 run banya and Team 2 na bhi 100 run banya match is Draw.
so now super 1 over by team 1 and team 2 who score highest run he wins

In [72]:
# thinking konsa col hamara data ma ya information da sakta ha 
# so we find ki SuperOver name ha ek col ma usma 2 values ha Y or N yes or no 
ipl['SuperOver'] =='Y'
ipl[ipl['SuperOver'] =='Y']
# we want to find how many number of rows 
ipl[ipl['SuperOver'] =='Y'].shape
ipl[ipl['SuperOver'] =='Y'].shape[0] # only rows 
# so their are total 14 mathces in ipl jaha par super over hua

14

### how many matches won by csk in kolkata city

In [73]:
# ma jan na cha hu kitna match chennai na jitna in kolkata city 
# so thinking we have to check for two condition 
# where city is kolkata and winning Team is chennai 
ipl['WinningTeam'] == 'Chennai Super Kings'
ipl.head(7)
ipl['City'] == 'Kolkata'
# apply the and opeator in both condition 
ipl[(ipl['City'] == 'Kolkata') &(ipl['WinningTeam'] == 'Chennai Super Kings')]
# now find number of rows using shape 
ipl[(ipl['City'] == 'Kolkata') &(ipl['WinningTeam'] == 'Chennai Super Kings')].shape
# only row in the tuple
ipl[(ipl['City'] == 'Kolkata') &(ipl['WinningTeam'] == 'Chennai Super Kings')].shape[0]

5

In [74]:
# we are not using And we use bitwise & jo boolean series ma dono True values ko nikala ga

In [75]:
# so total 5 mathces jita chennai team in kolkata city

### toss winner or match winner in percentage
hum dekna chata ha ki toss jitna sa match winner ma kuch hota ha ki nahi

In [76]:
# find the no of  toss winner and wining team and  are same
# hum dono coloumns ko compare kar dega 
ipl['TossWinner'] == ipl['WinningTeam']
# True toss jita match jita , False toss jita,matcha hara 
# use indexing concept 
ipl[ipl['TossWinner'] == ipl['WinningTeam']]
# find number of rows using shape 
ipl[ipl['TossWinner'] == ipl['WinningTeam']].shape[0]
# divide the ratio
ratio = ipl[ipl['TossWinner'] == ipl['WinningTeam']].shape[0]/ipl.shape[0]
ratio * 100
print(" {}% times toss wining and match wining team is same ".format(round(ratio * 100)))

 51% times toss wining and match wining team is same

In [ ]:
# so toss jitna itna important nahi ha match jitna ka

### movies that have imbd rating > 8 and votes greathan than 10000

In [96]:
# find movies jinka imbd rating > 8
movies.head(1)
movies['imdb_rating'] >= 8
movies[movies['imdb_rating'] >= 8]
# find imbd votes greator than or equal to  10000
movies['imdb_votes'] >=10000
movies[movies['imdb_rating'] >= 8]
# we have to find when both are true 
# movies[() & ()]
movies[(movies['imdb_rating'] >= 8) & (movies['imdb_votes'] >10000)]
# find number of movies using shape 
movies[(movies['imdb_rating'] > 8) & (movies['imdb_votes'] >10000)].shape
# extract only rows
movies[(movies['imdb_rating'] > 8) & (movies['imdb_votes'] >10000)].shape[0]

43

In [ ]:
# tho asi 43 movies ha

In [100]:
movies[(movies['imdb_rating'] > 8) & (movies['imdb_votes'] >10000)][['title_x']]

                          title_x
0        Uri: The Surgical Strike
11                      Gully Boy
37              Article 15 (film)
40                Super 30 (film)
143                       Tumbbad
146                     Andhadhun
325              Pink (2016 film)
354                 Dangal (film)
418                        Masaan
426          Drishyam (2015 film)
436                 Talvar (film)
469             Queen (2014 film)
536                 Haider (film)
566                   Ugly (film)
567                     PK (film)
589                  Vishwaroopam
612            Bhaag Milkha Bhaag
638                 Shahid (film)
668       Paan Singh Tomar (film)
669                       Kahaani
693            Gangs of Wasseypur
694   Gangs of Wasseypur – Part 2
709                        Barfi!
714              OMG – Oh My God!
778      Zindagi Na Milegi Dobara
869             Udaan (2010 film)
912                      3 Idiots
930                 Gulaal (film)
1058     Black Friday (2007 film)
1066               Chak De! India
1127             Taare Zameen Par
1180             Khosla Ka Ghosla
1183         Lage Raho Munna Bhai
1188           Omkara (2006 film)
1195              Rang De Basanti
1223            Black (2005 film)
1252                 Iqbal (film)
1384                       Swades
1403          Munna Bhai M.B.B.S.
1554   The Legend of Bhagat Singh
1567                       Lagaan
1568                       Lagaan
1571               Dil Chahta Hai

### Action movies with rating higher than 7.5

In [119]:
# so this Question is interseting you learn new thing
# app geners ma deko vo kahi = action|drama , crime|action , 
# tho geners ma multiple genres ha movie ka huma lena ha atleast action tho ho 
# so we have to split it than check in that action ha ki nahi 
movies.sample()
movies['genres']
# convert into string becasue then you apply string methods
movies['genres'].str.split('|')
# now
'Action' in movies['genres'].str.split('|') # that not work because wo df ko ek entity 
# maan raha ha  so what the solution 
# 
mask1 = movies['genres'].str.split('|').apply(lambda x : "Action" in x)
# x ya par meri every movie row ha us par ya operation apply kara 
mask2 = movies['imdb_rating'] > 7.5
# now apply both
movies[mask1 & mask2]
movies[mask1 & mask2].shape[0]

33

In [120]:
# contians function also work 
mask1 = movies['genres'].str.contains('Action') 
mask2 = movies['imdb_rating'] > 7.5

movies[mask1 & mask2]
movies[mask1 & mask2].shape[0]

33

In [ ]:
# tho asi 33 movies ha

In [110]:
# find where type(generes) of the movie is Action 
movies.sample()
movies['genres'] =='Action'
movies[movies['genres'] =='Action']
# find imbd rating greator than 7
movies['imdb_rating'] > 7
# now take intersedtio and operator between 
# only 3 movies ha 
movies[(movies['imdb_rating'] > 7) & (movies['genres'] =='Action')].shape[0]
movies[(movies['imdb_rating'] > 7) & (movies['genres'] =='Action')]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
367,Gabbar Is Back,tt2424988,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gabbar_Is_Back,Gabbar is Back,Gabbar is Back,0,2015,128,Action,7.1,21430,Gabbar Singh Rajput (Akshay Kumar) creates his...,A grief-stricken man takes the law into his ow...,NaN,Akshay Kumar|Shruti Haasan|Kareena Kapoor|Jaid...,1 win,1 May 2015 (India)
368,Gabbar Is Back,tt2424988,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gabbar_is_Back,Gabbar is Back,Gabbar is Back,0,2015,128,Action,7.1,21430,Gabbar Singh Rajput (Akshay Kumar) creates his...,A grief-stricken man takes the law into his ow...,NaN,Akshay Kumar|Shruti Haasan|Kareena Kapoor|Jaid...,1 win,1 May 2015 (India)
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)

### write a function that give you track record of 2 teams against each other
example yadi ma apko 2 teams du rcb vs csk tho rcb na kitna match jita or csk na kitna match jita

In [ ]:
# thinking behind func
# input ma two teams  output ma how much match won between them

ipl.sample()
['Team1','Team2','WinningTeam']
# input ma team1 and team2
# fir un dono team ma matches kab hua 
# fir usma sa winning team first thi or second thi 
# fir shape sa count kar lao 
def win_matches(first_team,second_team):

    ipl['Team1'] == first_team
    ipl['Team2'] == second_team
    ans1 = ipl[(ipl['Team1'] == first_team) & (ipl['Team2'] == second_team) & (ipl['WinningTeam']== first_team)].shape[0]
    ans2 = ipl[(ipl['Team1'] == first_team) & (ipl['Team2'] == second_team) & (ipl['WinningTeam']== second_team)].shape[0]
    
    print('{} won =  {} matches'.format(first_team,ans1))
    print('{} won =  {} matches'.format(second_team,ans2))
    
win_matches(first_team = 'Royal Challengers Bangalore',second_team = 'Chennai Super Kings')

Royal Challengers Bangalore won =  8 matches
Chennai Super Kings won =  56 matches

# Adding new coloumns

## completely new

In [149]:
# so ya sari bollywood movies ka data ha tho hum ek new coloumn india add karta ha
movies_df = movies.copy()
movies_df['country'] = "India"
movies_df.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),India
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),India

## from existing ones

In [ ]:
# chalo ek new coloumn add karta ha lead actor ka jo actor list ma ha
movies_df.dropna(inplace=True)
# because warna hamra function kam nahi karaga np.nan ma

In [151]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 298 entries, 11 to 1623
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           298 non-null    object
 1   imdb_id           298 non-null    object
 2   poster_path       298 non-null    object
 3   wiki_link         298 non-null    object
 4   title_y           298 non-null    object
 5   original_title    298 non-null    object
 6   is_adult          298 non-null    int64
 7   year_of_release   298 non-null    int64
 8   runtime           298 non-null    object
 9   genres            298 non-null    object
 10  imdb_rating       298 non-null    float64
 11  imdb_votes        298 non-null    int64
 12  story             298 non-null    object
 13  summary           298 non-null    object
 14  tagline           298 non-null    object
 15  actors            298 non-null    object
 16  wins_nominations  298 non-null    object
 17  release_date      298 non-null    object
 18  country           298 non-null    object
dtypes: float64(1), int64(3), object(15)
memory usage: 46.6+ KB

In [156]:
movies_df['lead actor']= movies_df['actors'].str.split('|').apply(lambda x : x[0])
movies_df.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,country,lead actor
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA),India,Ranveer Singh
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India),India,Gavie Chahal
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA),India,Ayushmann Khurrana
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA),India,Sidharth Malhotra
96,Raid (2018 film),tt7363076,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raid_(2018_film),Raid,Raid,0,2018,122,Action|Crime|Drama,7.4,13159,Set in the 80s in Uttar Pradesh India Raid i...,A fearless income tax officer raids the mansio...,Heroes don't always come in uniform,Ajay Devgn|Saurabh Shukla|Ileana D'Cruz|Amit S...,2 wins & 3 nominations,16 March 2018 (India),India,Ajay Devgn