In [1]:
print('joruney start')

joruney start

In [3]:
import mysql.connector
import pandas as pd

In [5]:
connector = mysql.connector.connect(host='localhost',user='root',password='improve@7',database='campusx')
df = pd.read_sql_query("SELECT * FROM USERS",connector)
df

C:\Users\sumit\AppData\Local\Temp\ipykernel_15576\1513778440.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM USERS",connector)

   user_id    name             email password
0        1  manish  manish@gmail.com     1234
1        2   sumit   sumit@yahoo.com     1010
2        3   deepu   deepu@gmail.com     None
3        4  aditya              None     1234
4        5   anand   anand@gmail.com     1234
5        6   ayush   ayush@gmail.com    12345
6        7  piyush  piyush@gmail.com     6789

# read database

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/campusx")

# Query with pandas
df = pd.read_sql("SELECT * FROM USERS", engine)
df

   user_id    name             email password
0        1  manish  manish@gmail.com     1234
1        2   sumit   sumit@yahoo.com     1010
2        3   deepu   deepu@gmail.com     None
3        4  aditya              None     1234
4        5   anand   anand@gmail.com     1234
5        6   ayush   ayush@gmail.com    12345
6        7  piyush  piyush@gmail.com     6789

# write database

In [5]:
df = pd.read_csv('class.csv',sep=';')
df

   class_id class_name       teacher  class_year
0         1   Math 101     Mr. Smith        2021
1         2  English 1   Ms. Johnson        2021
2         3  Science 1       Dr. Lee        2022
3         4  History 1  Ms. Williams        2022

## class

In [8]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/sql_cx_live")
df = pd.read_csv('class.csv',sep=';')

# Write to SQL
df.to_sql(
    name="class",         # table name in MySQL
    con=engine,
    if_exists="replace",  # replace if table exists (use 'append' to add)
    index=False           # don’t add pandas index as column
)

4

## groups

In [3]:
pd.read_csv('groups.csv' ,sep=';')

   group_id group_name
0         1    Group 1
1         2    Group 2
2         3    Group 3
3         7    Group 7

In [9]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/sql_cx_live")
df1 = pd.read_csv('groups.csv' ,sep=';')

# Write to SQL
df1.to_sql(
    name="groups",         # table name in MySQL
    con=engine,
    if_exists="replace",  # replace if table exists (use 'append' to add)
    index=False           # don’t add pandas index as column
)

4

## membership

In [12]:
pd.read_csv('membership.csv',sep=';')

    membership_id  group_id  user_id
0               1         1        1
1               2         1        2
2               3         1        3
3               4         1        4
4               5         2        1
5               6         2        4
6               7         3        1
7               8         3        3
8               9         4        1
9              10         1        5
10             11         1        6

In [14]:
df = pd.read_csv('membership.csv',sep=';')

# Write to SQL
df.to_sql(
    name="membership",         # table name in MySQL
    con=engine,
    index=False           
)

11

In [25]:
pd.read_csv('person1.csv',sep=';')

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie

In [26]:
df = pd.read_csv('person1.csv',sep=';')

# Write to SQL
df.to_sql(
    name="person1",         # table name in MySQL
    con=engine,
    index=False           
)

3

In [27]:
pd.read_csv('person2.csv',sep=';')

   id     name
0   3  Charlie
1   4    David
2   5    Emily

In [29]:
df = pd.read_csv('person2.csv',sep=';')

# Write to SQL
df.to_sql(
    name="person2",         # table name in MySQL
    con=engine,
    index=False           
)

3

In [31]:
pd.read_csv('students.csv',sep = ';')

   student_id first_name last_name  class_id  enrollment_year
0           1       John     Smith         1             2021
1           2       Jane       Doe         2             2020
2           3        Bob   Johnson         1             2021
3           4      Sally     Brown         3             2022
4           5        Tom  Williams         2             2022
5           6      Alice     Davis         4             2020

In [33]:
df = pd.read_csv('students.csv',sep = ';')

# Write to SQL
df.to_sql(
    name="students",         # table name in MySQL
    con=engine,
    index=False           
)

6

In [2]:
import pandas as pd
pd.read_csv(r'C:\Users\sumit\My_code_files\Data Science codes\week 15-SQL Continued\datasets-session-35\users.csv')

   user_id      name               email password
0        1    Nitish    nitish@gmail.com    p252h
1        2  Khushboo  khushboo@gmail.com    hxn9b
2        3   Vartika   vartika@gmail.com    9hu7j
3        4     Ankit     ankit@gmail.com    lkko3
4        5      Neha      neha@gmail.com    3i7qm
5        6   Anupama   anupama@gmail.com   46rdw2
6        7   Rishabh   rishabh@gmail.com   4sw123

In [3]:
import pandas as pd
from sqlalchemy import create_engine

# Correctly encoded password
engine = create_engine("mysql+pymysql://root:improve%407@localhost/sql_cx_live")
df = pd.read_csv(r'C:\Users\sumit\My_code_files\Data Science codes\week 15-SQL Continued\datasets-session-35\users.csv')

# Write to SQL
df.to_sql(
    name="users",         # table name in MySQL
    con=engine,
    if_exists="replace",  # replace if table exists (use 'append' to add)
    index=False           # don’t add pandas index as column
)

7

In [5]:
pd.read_csv('users1.csv',sep = ';')

   user_id     name  age  emergency_contact
0        1   Nitish   34                 11
1        2    Ankit   32                  1
2        3     Neha   23                  1
3        4  Radhika   34                  3
4        8  Abhinav   31                 11
5       11    Rahul   29                  8

In [6]:
df = pd.read_csv('users1.csv',sep = ';')

# Write to SQL
df.to_sql(
    name="users1",         # table name in MySQL
    con=engine,
    index=False           
)

6