Question : How To gain Domain knowlege <br>
Answer : Spent time in the domain ,read and study about particular domain . The more project you make in a domain better you understand the domain .

 That why when people switch job they prefer in same domain . Example : A person working in swiggy (foodtech) he gets two offers of job from zomato or amazon . he prefer zomatao . he work in same domain . so industry ma uska demand ha

deko ai tools are coming . lakin domain knowldage person shield bana kar raka ha , kyuki ai tool ko uska domain level ka inution ya experience nahi hoga.

actionable advice : koi ek cheez pakad kar uska upar kam karo you gain domain knowldge .

ma apna deka thu muja ek sa jada domain knowldge ma interset ha .       
ya it is possible that you have knowldge of two or many domain combination ho.

# Project Roadmmap
1. we scrape a website about smartphone data
2. We clean the data 
3. We do analysises on it.
4. we make a dashboard in streamlit

you also extend the idea make smartphone price predicator app

We use the same smartphone data which we scrape using the selnium last class

## Today Task
Our today task is that we clean the data we scrape from the samrtprix website .

In [115]:
import numpy as np
import pandas as pd

In [116]:
smartphone = pd.read_csv('smartphones.csv')
smartphone

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,"₹34,990",83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,"₹14,990",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),"₹28,990",85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,"₹19,990",80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,"₹24,990",74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

so sir na phala hi manual assesment kar diya ha .       
hum usko dekan ha

## Data Assessing

### Quality Issues

1. **model** - some brands are written diiferently like OPPO in model column `consistency`
2. **price** - has unneccesary '₹' `validity`
3. **price** - has ',' between numbers `validity`
4. **price** - phone Namotel has a price of 99 `accuracy`
5. **ratings** - missing values `completeness`
6. **processor** - has some incorrect values for some samsung phones(row # -642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002) `validity`
7. There is ipod on row 756 `validity`
8. **memory** - incorrect values in rows (441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002) `validity`
9. **battery** - incorrect values in rows(113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002) `validity`
10. **display** - sometimes frequency is not available `completeness`
11. **display** - incorrect values in rows(378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002) `validity`
12. certain phones are foldable and the info is scattered `validity`
13. **camera** - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
14. **camera** - problem with rows (100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016
) `validity`
15. **card** - sometimes contains info about os and camera `validity`
16. **os** - sometimes contains info about bluetooth and fm radio `validity`
17. **os** - issue with rows (324,378) `validity`
18. **os** - sometimes contains os version name like lollipop `consistency`
19. missing values in camera, card and os `completeness`
20. datatype  of price and rating is incorrect `validity`



### Tidiness Issues

1. **sim** - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
2. **ram** - can be split into 2 cols RAM and ROM
3. **processor** - can be split into processor name, cores and cpu speed.
4. **battery** - can be split into battery capacity, fast_charging_available
5. **display** - can be split into size, resolution_width, resolution_height and frequency
6. **camera** - can be split into front and rear camera
7. **card** - can be split into supported, extended_upto

sir na 2 hour tak manual assement ki fir uska baad points lika . example vo

Explanation about it quality issue in our dataset.
- deko kahi par Oppo lika ha aor kahi par OPPO lika ha ya ha data ma consistency issue kahi par capital letter ma ha kahi par small letters ma lika ha tho
- ruppes coloumn ma price ka symbol ha jo uncessary ha and bitch ma vo comma sa separated bhi ha. 
- namophone 99 rupeees ka ya anomoly ha kyuki phones 99 rupess ma nahi ata . (may be scam)
- some values are missing in rating columns
- some rows numbers have quality issue in processor
- hamra paas ek ipod ha usko hum remove karega.
- deko hamena webscraping kiya tho thoda shifting ho gaya ha usa bhi thik karna ha. (shifting ki waja sa thoda hamara unclean data ha)
- operting system ma fm radio or bluetooth ha
- operaing system ma kahi jaga android version ka name ha tho kahi jaga uska os ka name ha .

structure issue in our dataset
- sim vard coloum ko 3 alag column ma split karo dual sim , har ek phone ki lagbam dual sim kuch 10 phone hoga baas single sim wala 3G sabhi phones ma 4G bhi phones ma ha 5G har phone ma nahi ha tho ya differenting factor ha. NFC Thoda premeir phones ma hota ha.  aor IR blaster china ka phones ma hota ha
- processor sa bhi 3 information 
    - name of the processor
    - kitna core ka process ha dual,hecta 
    - frequency ya speed kitna ha processor ka 
- ram ka hum coloumns ram and rom
- batter sa bhi 2 columns banta sakta 
- displays sa bhi screen and refresh rate
- camera ha front and back 
- card kuch khas nahi baas memory card ha ki nahi ha tho kitna gb ka ha.
- operating system konsa ha and konsa version ha 
- scren divide ko kareka pixes sa pixel by inch vo bhi bhut acha feature ho sakta ha . 
- agar aap chaho tho aap koi aor acha columns (variable bhi bana sakta ho.)

NFC = Near field communication (jo thoda premium phones ma hota ha . )
ya wirelss type of communication jo thoda premium phones ma hota ha.
By just Tab . you do payements.

feature engering  meaning you do analysis you think you make more columns out of it.    
- feature means columns (variable)
- engineering means creating new columns

In today you do iterative process       
thoda assesment fir thoda cleaning , fir assesment fir cleaning .

## programmetic cleaning

In [117]:
# deko head tail karna ki jarraut nahi haman data dek liya
# sample  bhi humana data dek liya.

In [118]:
smartphone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   object
 1   price      1020 non-null   object
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object
 4   processor  1020 non-null   object
 5   ram        1020 non-null   object
 6   battery    1020 non-null   object
 7   display    1020 non-null   object
 8   camera     1019 non-null   object
 9   card       1013 non-null   object
 10  os         1003 non-null   object
dtypes: float64(1), object(10)
memory usage: 87.8+ KB

In [119]:
# rating ma missing values hamana already bo lik diya ha . 
smartphone.isnull().sum()

model          0
price          0
rating       141
sim            0
processor      0
ram            0
battery        0
display        0
camera         1
card           7
os            17
dtype: int64

In [120]:
smartphone.describe()
# apko kuch khas ya par nahi milega .

           rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [121]:
smartphone.duplicated().sum()

0

In [122]:
# deko phala aap basic level cleaning karo and fir aap
# uska upar programmetic assessment karo
# deko yadi chota data ha tho tho aap manual assesment karo
# you feel more powerful with it. 
# lakin yadi big data ha tho do programmetic assessment .

# Do cleaning

In [123]:
# know ths solution stucture 
# lakin tho aaj hu completness nahi validiy issue sa saruhat karega . 
# kyuki jada values nahi ha hamara paas

## make copy

In [124]:
df = smartphone.copy()
df

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,"₹34,990",83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,"₹14,990",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),"₹28,990",85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,"₹19,990",80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,"₹24,990",74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

## price
lets start with price coloumn  it have 3 columns 
- rupees symbol 
- comma in between 
- datatype string ha usko integer karo

In [125]:
# ja bhi ruppes symbol deka usko replace karo empty space sa

In [126]:
df['price'].str.replace('₹','')

0       54,999
1       19,989
2       16,499
3       14,999
4       24,999
         ...
1015    34,990
1016    14,990
1017    28,990
1018    19,990
1019    24,990
Name: price, Length: 1020, dtype: object

In [127]:
# fir aap all the commas ko empty space yani nothingless sa replace karo
df['price'].str.replace('₹','').str.replace(',','')

0       54999
1       19989
2       16499
3       14999
4       24999
        ...
1015    34990
1016    14990
1017    28990
1018    19990
1019    24990
Name: price, Length: 1020, dtype: object

In [128]:
# ab iska dattype ko integer karna hoga
df['price'].str.replace('₹','').str.replace(',','').astype(np.int64)

0       54999
1       19989
2       16499
3       14999
4       24999
        ...
1015    34990
1016    14990
1017    28990
1018    19990
1019    24990
Name: price, Length: 1020, dtype: int64

In [129]:
# make permanet change in the coloumns 
df['price'] = df['price'].str.replace('₹','').str.replace(',','').astype(np.int64)

In [130]:
df['price']

0       54999
1       19989
2       16499
3       14999
4       24999
        ...
1015    34990
1016    14990
1017    28990
1018    19990
1019    24990
Name: price, Length: 1020, dtype: int64

In [131]:
# wow we solve all the problems in it.

In [132]:
# deko rating ma missing values ha hum usko knn immunator valyes sa fill
# kar sakta ha . 
# we do in later

## sim

In [133]:
df['sim']

0                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
1                      Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
2                      Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
3                      Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
4                      Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
                              ...
1015                   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
1016                   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
1017    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...
1018              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
1019                   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
Name: sim, Length: 1020, dtype: object

In [134]:
# hamena mehnat karka rows khoja jinma 
# hum us row ko variable ma dal raha ha 
# like processor 
# hamana google sheet ma jo deko vo 2 index tha
# aor pandas ma 2 index hum picha tha isliya unko same kiya

In [135]:
df.reset_index(inplace=True)

In [136]:
df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1015,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1016,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1017,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1018,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1019,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [137]:
df['index'] = df['index'] + 2

In [138]:
df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [139]:
# jin coloumns ma problem hui unka ek alag dataframe ma daleta ha

In [140]:
processor_rows = set((642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002))
ram_rows = set((441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002))
battery_rows = set((113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002))
display_rows = set((378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002))
camera_rows = set((100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016 ))

In [141]:
# take union of all 
union_all = processor_rows | ram_rows | battery_rows | display_rows | camera_rows
print(union_all)

{273, 534, 792, 553, 819, 308, 309, 571, 572, 575, 323, 324, 584, 846, 854, 855, 858, 859, 610, 100, 613, 615, 365, 367, 113, 883, 884, 630, 378, 896, 642, 647, 649, 394, 659, 915, 916, 919, 151, 667, 157, 927, 929, 161, 932, 684, 687, 945, 441, 956, 701, 705, 450, 711, 723, 728, 990, 995, 484, 485, 1002, 750, 238, 756, 759, 1016, 506, 764}

In [142]:
# why we take set . because set data stucture 
# is collection of all unique elments

In [143]:
# this is all problematic rows

In [144]:
df[df['index'].isin(union_all)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
...,...,...,...,...,...,...,...,...,...,...,...,...
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
988,990,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [145]:
# so out of 1020 rows we have 68 probabalic rows 
# jisma kisi ek atleast row ma problem ha.

In [146]:
# take union of all 
intersection_all = processor_rows & ram_rows & battery_rows & display_rows & camera_rows
print(intersection_all)

{929, 642, 932, 647, 649, 1002, 750, 659, 819, 884, 759, 667, 927}

In [147]:
df[df['index'].isin(intersection_all)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
640,642,Nokia 105 Plus,1299,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
647,649,Motorola Moto A10,1339,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN
657,659,Zanco Tiny T1,2799,NaN,Single Sim,"32 MB RAM, 32 MB inbuilt",200 mAh Battery,"0.49 inches, 64 x 32 px Display",No Rear Camera,No FM Radio,Bluetooth,NaN
665,667,itel it2163S,958,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1200 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
748,750,Nokia 400 4G,3290,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 64 GB",Bluetooth,Browser,NaN
757,759,Karbonn KU3i,995,NaN,Dual Sim,"52 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 16 GB",Bluetooth,NaN
817,819,itel Magic X,2239,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"48 MB RAM, 128 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
927,929,Samsung Guru E1200,1685,NaN,Single Sim,No Wifi,800 mAh Battery,"1.5 inches, 128 x 128 px Display",No Rear Camera,No FM Radio,NaN,NaN
930,932,iKall K88 Pro 4G,2099,NaN,"Dual Sim, 3G, 4G, VoLTE","48 MB RAM, 128 MB inbuilt",1800 mAh Battery,"2.4 inches, 240 x 360 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,Browser
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera

In [148]:
# deko ya 13 rows almost every 4 coloumns have some problem 
# yahi vo columns ha jisma shifting hui ha .

In [149]:
# inka mean price nikala 
df[df['index'].isin(intersection_all)]['price'].mean()

2537.6923076923076

In [150]:
# we notice ya problems un phones ma ha jinka price point bhut kam ha .

In [151]:
# tho average price inka ha 2500 ruppess
# 2500 ka phone milta ha market ma 
# ya sara keyboard phone ha

In [152]:
# lakin hum analysis kar raha ha smartphone data par tho 
# ham en keyboard  phones ko drop kar dega .

In [153]:
# so 3400 thousand ka nicha smartphone nahi ha .

In [154]:
df = df[df['price'] > 3400]

In [155]:
df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [156]:
# deko en 991 phones  keybaord phones ho sakta ha
# lakin smarphone ka sara phone 3400 ka upar hi ata ha

In [157]:
df[df['index'].isin(intersection_all)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

In [158]:
# ab apka ya 3 phones bacha ha

## processor

now hum ek ek coloumns ko clena karta ha usko dekta ha .

In [159]:
df[df['index'].isin(processor_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
857,859,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

In [160]:
# ya sara keyboard phones ha so we drop it 
# isko index pakodo aor drop kar do 
df[df['index'].isin(processor_rows)].index.to_list()

[645, 857, 882, 925]

In [161]:
df.drop([645, 857, 882, 925],inplace=True)

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\486334192.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop([645, 857, 882, 925],inplace=True)

In [162]:
df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

## ram rows

In [163]:
df[df['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
582,584,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"

In [164]:
# tho phal is keyboard (feauture phone) ko drop karta ha 
df.drop(582,inplace=True)

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\22856165.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(582,inplace=True)

In [165]:
df[df['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0

In [166]:
# tho in 2 phones ma problem ha ki inska ram diya gaya ha rom nahi diya gaya ha

## battery

In [167]:
df[df['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,378,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
754,756,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [168]:
# so sara sa iphone ma battery ki jaga display information aa gaya
# aor sara left shift ho gaya ha . 

# first ya nokia ka keyboard aor ipod ko remove karo 
df.drop([376,754],inplace=True)

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\3030001642.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop([376,754],inplace=True)

In [169]:
# hamra paas bacha sara iphone

In [170]:
df[df['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [171]:
# we are using the shiting function

In [172]:
temp_df = df[df['index'].isin(battery_rows)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

## shfting code

In [173]:
#    rows sliching ,columns sliching
# meaning all rows but start coloumns after 7 
temp_df.iloc[:,7:]

,battery,display,camera,card,os
111,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
439,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
762,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [174]:
temp_df.iloc[:,7:].shift(1,axis=1) # axis =1 for columns

,battery,display,camera,card,os
111,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
913,None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [175]:
our_array = temp_df.iloc[:,7:].shift(1,axis=1).values
our_array

array([[None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None, '5.4 inches, 1080\u2009x\u20092340\u2009px Display',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None, '5.4 inches, 1080\u2009x\u20092340\u2009px Display',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None, '4.7 inches, 750\u2009x\u20091334\u2009px Display',
        '12\u2009MP Rear & 7\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v15'],
       [None,
        '6.06 inches, 1170\u2009x\u20092532\u2009px, 120 Hz Display with Punch Hole',
        '50\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v15'],
       [None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14.0'],
       [None, '6.1 inches, 750\u2009x\u20091580\u2009px Display',
        '12\u2009MP Rear & 10.8\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v16'],
       [None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14.0'],
       [None, '5.4 inches, 1080\u2009x\u20092340\u2009px Display',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [None,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14']], dtype=object)

In [176]:
x_index = temp_df.index
x_index

Index([111, 149, 307, 363, 439, 448, 628, 762, 853, 913, 914], dtype='int64')

In [177]:
df.loc[temp_df.index,temp_df.columns]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [178]:
# en index and coloumns ma hamrai temp df ki values ko set karo 
df.loc[temp_df.index,temp_df.columns[7:]] = our_array

In [179]:
# chalo dekta ha editing hua ha k nahi
df[df['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [180]:
# har waha editing ho gaya ha hamara ji

## display rows

In [181]:
df[df['index'].isin(display_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [182]:
# hara ya wahi wala iphone tha tho pichala wala solve kiya tha isliya ya bhi tik ho gaya

## camera rows

In [183]:
df[df['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [184]:
#  this are  feature phone 
# 155,275
df.drop([155,275],inplace=True)

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\1588539464.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop([155,275],inplace=True)

In [185]:
df[df['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [186]:
# deko ja par bhi foldable display lika ha wha par wo right shift ho gaya ha data 
# jaha normal camera ha wha tik ha 
temp_df = df[df['index'].isin(camera_rows)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [187]:
temp_df[temp_df['camera'].str.contains('MP')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [188]:
# do negation of it . now we find the all mistakes phone 
camera_df = temp_df[~temp_df['camera'].str.contains('MP')]
camera_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [189]:
# just swap the coloumns values  of camera and card 

df.loc[camera_df.index,'camera']

98                    Foldable Display
159     Foldable Display, Dual Display
236     Foldable Display, Dual Display
271                       Dual Display
306     Foldable Display, Dual Display
321     Foldable Display, Dual Display
322     Foldable Display, Dual Display
365     Foldable Display, Dual Display
392     Foldable Display, Dual Display
482     Foldable Display, Dual Display
504     Foldable Display, Dual Display
569     Foldable Display, Dual Display
570                       Dual Display
613                       Dual Display
682                       Dual Display
703     Foldable Display, Dual Display
709                       Dual Display
721                       Dual Display
726                   Foldable Display
790     Foldable Display, Dual Display
844                       Dual Display
894     Foldable Display, Dual Display
943     Foldable Display, Dual Display
954                   Foldable Display
993                   Foldable Display
1014                  Foldable Display
Name: camera, dtype: object

In [190]:
camera_df['card']

98                   50 MP Quad Rear & 16 MP Front Camera
159     50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...
236     50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...
271                                      2 MP Rear Camera
306          12 MP + 12 MP Dual Rear & 10 MP Front Camera
321     50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...
322     64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...
365           50 MP + 8 MP Dual Rear & 32 MP Front Camera
392           50 MP + 8 MP Dual Rear & 32 MP Front Camera
482     50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera
504          12 MP + 12 MP Dual Rear & 10 MP Front Camera
569     12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...
570     64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...
613     64 MP + 20 MP + 2 MP Triple Rear & Main Front ...
682     64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...
703     50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...
709     64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...
721     50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...
726     50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...
790     108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...
844                         5 MP Rear & 2 MP Front Camera
894     64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...
943     50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...
954                  50 MP Quad Rear & 16 MP Front Camera
993                                48 MP Quad Rear Camera
1014    50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...
Name: card, dtype: object

In [191]:
camera_df['card'].values

array(['50\u2009MP Quad Rear & 16\u2009MP Front Camera',
       '50\u2009MP + 48\u2009MP + 32\u2009MP Triple Rear & 32\u2009MP + 32\u2009MP Dual Front Camera',
       '50\u2009MP + 13\u2009MP + 8\u2009MP Triple Rear & 20\u2009MP Front Camera',
       '2\u2009MP Rear Camera',
       '12\u2009MP + 12\u2009MP Dual Rear & 10\u2009MP Front Camera',
       '50\u2009MP + 12\u2009MP + 10\u2009MP Triple Rear & 10\u2009MP + 4\u2009MP Dual Front Camera',
       '64\u2009MP + 16\u2009MP + 8\u2009MP Triple Rear & 32\u2009MP Front Camera',
       '50\u2009MP + 8\u2009MP Dual Rear & 32\u2009MP Front Camera',
       '50\u2009MP + 8\u2009MP Dual Rear & 32\u2009MP Front Camera',
       '50\u2009MP Quad Rear & 16\u2009MP + 16\u2009MP Dual Front Camera',
       '12\u2009MP + 12\u2009MP Dual Rear & 10\u2009MP Front Camera',
       '12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 10\u2009MP + 4\u2009MP Dual Front Camera',
       '64\u2009MP + 13\u2009MP + 12\u2009MP Triple Rear & 32\u2009MP Front Camera',
       '64\u2009MP + 20\u2009MP + 2\u2009MP Triple Rear & Main Front Camera',
       '64\u2009MP + 13\u2009MP + 0.3\u2009MP Triple Rear & 10\u2009MP Front Camera',
       '50\u2009MP + 16\u2009MP + 13\u2009MP Triple Rear & 32\u2009MP Front Camera',
       '64\u2009MP + 16\u2009MP + 12\u2009MP Triple Rear & 16\u2009MP Front Camera',
       '50\u2009MP + 13\u2009MP + 5\u2009MP Triple Rear & 12\u2009MP Front Camera',
       '50\u2009MP + 13\u2009MP + 8\u2009MP Triple Rear & 10.7\u2009MP Front Camera',
       '108\u2009MP + 13\u2009MP + 8\u2009MP Triple Rear & 20\u2009MP Front Camera',
       '5\u2009MP Rear & 2\u2009MP Front Camera',
       '64\u2009MP + 16\u2009MP + 8\u2009MP Triple Rear & 32\u2009MP Front Camera',
       '50\u2009MP + 12\u2009MP + 10\u2009MP Triple Rear & 10\u2009MP + 4\u2009MP Dual Front Camera',
       '50\u2009MP Quad Rear & 16\u2009MP Front Camera',
       '48\u2009MP Quad Rear Camera',
       '50\u2009MP + 50\u2009MP + 10\u2009MP Triple Rear & 32\u2009MP Front Camera'],
      dtype=object)

In [192]:
# asssign the card information in dataframe

In [193]:
df.loc[camera_df.index,'camera'] = camera_df['card'].values

In [194]:
# now everything data is clean 
df[df['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

## card

In [195]:
df['card'].value_counts()

card
Memory Card Supported, upto 1 TB                                       171
Memory Card Not Supported                                              123
Android v12                                                            107
Memory Card Supported, upto 512 GB                                     105
Memory Card (Hybrid), upto 1 TB                                         90
Memory Card Supported                                                   89
Memory Card Supported, upto 256 GB                                      87
Android v13                                                             46
Android v11                                                             41
Memory Card (Hybrid)                                                    30
Memory Card (Hybrid), upto 256 GB                                       13
Memory Card (Hybrid), upto 512 GB                                       11
Android v10                                                             11
Memory Card Supported, upto 128 GB                                       6
Memory Card Supported, upto 2 TB                                         5
Memory Card Supported, upto 32 GB                                        4
Memory Card (Hybrid), upto 128 GB                                        3
Memory Card (Hybrid), upto 64 GB                                         3
50 MP Quad Rear & 16 MP Front Camera                                     2
12 MP + 12 MP Dual Rear & 10 MP Front Camera                             2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       2
64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                    2
50 MP + 8 MP Dual Rear & 32 MP Front Camera                              2
Android v9.0 (Pie)                                                       2
HarmonyOS v2.0                                                           1
50 MP + 16 MP + 13 MP Triple Rear & 32 MP Front Camera                   1
64 MP + 16 MP + 12 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front Camera                    1
50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Front Camera                  1
Memory Card (Hybrid), upto 2 TB                                          1
108 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                   1
5 MP Rear & 2 MP Front Camera                                            1
iOS v13                                                                  1
HarmonyOS                                                                1
48 MP Quad Rear Camera                                                   1
64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Front Camera                  1
12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       1
Android v10.0                                                            1
64 MP + 20 MP + 2 MP Triple Rear & Main Front Camera                     1
iOS v10                                                                  1
64 MP + 13 MP + 12 MP Triple Rear & 32 MP Front Camera                   1
50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32 MP Dual Front Camera      1
Memory Card Supported, upto 1000 GB                                      1
50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera                        1
Android v12.1                                                            1
64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front Camera                    1
2 MP Rear Camera                                                         1
50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                    1
50 MP + 50 MP + 10 MP Triple Rear & 32 MP Front Camera                   1
Name: count, dtype: int64

In [196]:
# ja par ma MP usko replace kar do not supported sa
df[df['card'].str.contains('MP')]
# all the cards which have information

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
69,71,Oppo Find N Fold,99990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...,Android v12
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [197]:
# replace it
card_df = df[df['card'].str.contains('MP')]
card_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
69,71,Oppo Find N Fold,99990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...,Android v12
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [198]:
df.loc[camera_df.index,'card'] = 'Memory Card Not Supported'

In [199]:
df[df['card'].str.contains('MP')]['card']

69    64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...
Name: card, dtype: object

In [200]:
# replace this mp

In [201]:
df['card'] = df['card'].str.replace(
    pat='64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front Camera',
    repl='Memory Card Not Supported'
)

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\456004459.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['card'] = df['card'].str.replace(

In [202]:
df['card'].value_counts()

card
Memory Card Supported, upto 1 TB       171
Memory Card Not Supported              150
Android v12                            107
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         90
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Android v13                             46
Android v11                             41
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Android v10                             11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 64 GB         3
Memory Card (Hybrid), upto 128 GB        3
Android v9.0 (Pie)                       2
Android v12.1                            1
Memory Card Supported, upto 1000 GB      1
iOS v10                                  1
Android v10.0                            1
iOS v13                                  1
HarmonyOS v2.0                           1
Memory Card (Hybrid), upto 2 TB          1
HarmonyOS                                1
Name: count, dtype: int64

In [203]:
df[df['card'].str.contains('Android')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
8,10,Nothing Phone 1,26749,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
9,11,OnePlus Nord 2T 5G,28999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
12,14,Xiaomi Redmi Note 12 Pro 5G,24762,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
17,19,OPPO Reno 9 Pro Plus,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","16 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
18,20,OnePlus 10R 5G,32999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
...,...,...,...,...,...,...,...,...,...,...,...,...
1009,1011,Xiaomi Civi 3,32990,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 20 MP + 2 MP Triple Rear & 32 MP + 32 ...,Android v13,No FM Radio
1011,1013,Oppo Find X6,69990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP Fron...,Android v12,No FM Radio
1012,1014,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor","2 GB RAM, 32 GB inbuilt",3020 mAh Battery,"5 inches, 854 x 480 px Display",2 MP Rear Camera,Android v11,No FM Radio
1013,1015,Google Pixel 8 Pro,70990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor 3, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.73 inches, 1440 x 3120 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio

In [204]:
df[df['card'].str.contains('Memory Card')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,Android v12
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [205]:
# all those rows jaha operating system ha 
# negation of it
temp_df = df[~df['card'].str.contains('Memory Card')]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
8,10,Nothing Phone 1,26749,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
9,11,OnePlus Nord 2T 5G,28999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
12,14,Xiaomi Redmi Note 12 Pro 5G,24762,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
17,19,OPPO Reno 9 Pro Plus,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","16 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
18,20,OnePlus 10R 5G,32999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
...,...,...,...,...,...,...,...,...,...,...,...,...
1009,1011,Xiaomi Civi 3,32990,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 20 MP + 2 MP Triple Rear & 32 MP + 32 ...,Android v13,No FM Radio
1011,1013,Oppo Find X6,69990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP Fron...,Android v12,No FM Radio
1012,1014,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor","2 GB RAM, 32 GB inbuilt",3020 mAh Battery,"5 inches, 854 x 480 px Display",2 MP Rear Camera,Android v11,No FM Radio
1013,1015,Google Pixel 8 Pro,70990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor 3, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.73 inches, 1440 x 3120 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio

In [206]:
df.loc[temp_df.index , 'card']

8       Android v12
9       Android v12
12      Android v12
17      Android v13
18      Android v12
           ...
1009    Android v13
1011    Android v12
1012    Android v11
1013    Android v13
1015    Android v12
Name: card, Length: 213, dtype: object

In [207]:
# so we have to shift the card information to os 
# nan values ko fir replace karo memory card not supported sa 
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
8,10,Nothing Phone 1,26749,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
9,11,OnePlus Nord 2T 5G,28999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
12,14,Xiaomi Redmi Note 12 Pro 5G,24762,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
17,19,OPPO Reno 9 Pro Plus,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","16 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
18,20,OnePlus 10R 5G,32999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
...,...,...,...,...,...,...,...,...,...,...,...,...
1009,1011,Xiaomi Civi 3,32990,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 20 MP + 2 MP Triple Rear & 32 MP + 32 ...,Android v13,No FM Radio
1011,1013,Oppo Find X6,69990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP Fron...,Android v12,No FM Radio
1012,1014,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor","2 GB RAM, 32 GB inbuilt",3020 mAh Battery,"5 inches, 854 x 480 px Display",2 MP Rear Camera,Android v11,No FM Radio
1013,1015,Google Pixel 8 Pro,70990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor 3, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.73 inches, 1440 x 3120 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio

In [208]:
temp_df['card']

8       Android v12
9       Android v12
12      Android v12
17      Android v13
18      Android v12
           ...
1009    Android v13
1011    Android v12
1012    Android v11
1013    Android v13
1015    Android v12
Name: card, Length: 213, dtype: object

In [209]:
temp_df.index

Index([   8,    9,   12,   17,   18,   20,   21,   24,   29,   37,
       ...
        971,  974,  975, 1007, 1008, 1009, 1011, 1012, 1013, 1015],
      dtype='int64', length=213)

In [210]:
temp_df.iloc[:,10:].shift(1,axis=1)

      card           os
8     None  Android v12
9     None  Android v12
12    None  Android v12
17    None  Android v13
18    None  Android v12
...    ...          ...
1009  None  Android v13
1011  None  Android v12
1012  None  Android v11
1013  None  Android v13
1015  None  Android v12

[213 rows x 2 columns]

In [211]:
#our operating system array 
os_array = temp_df.iloc[:,10:].shift(1,axis=1).values
os_array

array([[None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v10'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v10'],
       [None, 'Android v11'],
       [None, 'Android v9.0 (Pie)'],
       [None, 'Android v13'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12.1'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'iOS v10'],
       [None, 'Android v12'],
       [None, 'Android v10.0'],
       [None, 'Android v10'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'iOS v13'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v10'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'HarmonyOS v2.0'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v10'],
       [None, 'Android v10'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v10'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v10'],
       [None, 'Android v10'],
       [None, 'Android v11'],
       [None, 'Android v9.0 (Pie)'],
       [None, 'HarmonyOS'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v10'],
       [None, 'Android v10'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v13'],
       [None, 'Android v12'],
       [None, 'Android v11'],
       [None, 'Android v13'],
       [None, 'Android v12']], dtype=object)

In [ ]:
# before 
df.loc[temp_df.index,temp_df.columns[10:]]

             card           os
8     Android v12  No FM Radio
9     Android v12  No FM Radio
12    Android v12  No FM Radio
17    Android v13  No FM Radio
18    Android v12    Bluetooth
...           ...          ...
1009  Android v13  No FM Radio
1011  Android v12  No FM Radio
1012  Android v11  No FM Radio
1013  Android v13  No FM Radio
1015  Android v12  No FM Radio

[213 rows x 2 columns]

In [215]:
# apply operating assiging them 
df.loc[temp_df.index,temp_df.columns[10:]] = os_array

In [216]:
# after checking it
df.loc[temp_df.index,temp_df.columns[10:]]

      card           os
8     None  Android v12
9     None  Android v12
12    None  Android v12
17    None  Android v13
18    None  Android v12
...    ...          ...
1009  None  Android v13
1011  None  Android v12
1012  None  Android v11
1013  None  Android v13
1015  None  Android v12

[213 rows x 2 columns]

In [217]:
# aap check karo 
df['card'].value_counts()

card
Memory Card Supported, upto 1 TB       171
Memory Card Not Supported              150
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         90
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card Supported, upto 1000 GB      1
Memory Card (Hybrid), upto 2 TB          1
Name: count, dtype: int64

In [ ]:
df['card'].isnull().sum()
# 213 values ma operating system tha

213

In [225]:
df['card'].isnull().sum()

213

In [ ]:
df.loc[temp_df.index,'card']

8       None
9       None
12      None
17      None
18      None
        ...
1009    None
1011    None
1012    None
1013    None
1015    None
Name: card, Length: 213, dtype: object

In [226]:
df.loc[temp_df.index,'card']  = 'Memory Card Not Supported'

In [227]:
df.loc[temp_df.index,'card']

8       Memory Card Not Supported
9       Memory Card Not Supported
12      Memory Card Not Supported
17      Memory Card Not Supported
18      Memory Card Not Supported
                  ...
1009    Memory Card Not Supported
1011    Memory Card Not Supported
1012    Memory Card Not Supported
1013    Memory Card Not Supported
1015    Memory Card Not Supported
Name: card, Length: 213, dtype: object

In [229]:
df['card'].isnull().sum()

0

In [ ]:
# yes you do it.

In [230]:
df['card'].value_counts()

card
Memory Card Not Supported              363
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         90
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card Supported, upto 1000 GB      1
Memory Card (Hybrid), upto 2 TB          1
Name: count, dtype: int64

In [ ]:
# wow tho hamena aab card problem ho bhi solve kar diya ha . 
# sabhi ma memory card information ha

## operating system

In [231]:
df['os'].value_counts()

os
Android v12                           394
Android v11                           273
Android v13                            91
Android v10                            69
Android v9.0 (Pie)                     29
Android v10.0                          23
iOS v16                                15
iOS v15                                12
Android v8.1 (Oreo)                    10
iOS v14                                 6
Memory Card Not Supported               6
Android v11.0                           4
Android v8.0 (Oreo)                     4
iOS v13                                 4
iOS v15.0                               3
Harmony v2.0                            2
Memory Card (Hybrid), upto 2 TB         2
Memory Card (Hybrid), upto 256 GB       2
HarmonyOS v2.0                          2
Android v5.1.1 (Lollipop)               2
EMUI v12                                2
Android v6.0 (Marshmallow)              2
Memory Card Supported, upto 256 GB      2
Android v12.1                           2
iOS v14.0                               2
Memory Card Supported, upto 128 GB      1
HarmonyOS                               1
RTOS (Series 30+)                       1
Android v7.1 (Nougat)                   1
Hongmeng OS v4.0                        1
Android                                 1
Android v5.1 (Lollipop)                 1
Memory Card (Hybrid)                    1
iOS v10                                 1
Pragati OS (Powered by Android)         1
Bluetooth                               1
Hongmeng OS v3.0                        1
Android v4.4.2 (KitKat)                 1
iOS v17                                 1
Memory Card Supported                   1
iOS v12.3                               1
iOS v13.0                               1
HarmonyOS v2                            1
Android v9 (Pie)                        1
Name: count, dtype: int64

In [ ]:
# isma abhi bhi kuch jagea memory card ha 
# matlab waha par hamra paas operating system ka information ha hi nahi

In [ ]:
# memory card ko dekta ha waha kiya scene chal raha ha

In [235]:
os_temp_df = df[df['os'].str.contains('Memory Card')]
os_temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Not Supported,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card Not Supported,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,Memory Card Not Supported,"Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"

In [234]:
df[df['os'].str.contains('Memory Card')]['os'].value_counts()

os
Memory Card Not Supported             6
Memory Card Supported, upto 256 GB    2
Memory Card (Hybrid), upto 2 TB       2
Memory Card (Hybrid), upto 256 GB     2
Memory Card Supported                 1
Memory Card (Hybrid)                  1
Memory Card Supported, upto 128 GB    1
Name: count, dtype: int64

In [ ]:
# hamena jo memory card  not supported
# lakin vo insformation side wala coloumns ma tha .

In [236]:
# just swap the values and assign them 
os_temp_df['os']

159             Memory Card Not Supported
271                 Memory Card Supported
306             Memory Card Not Supported
322    Memory Card Supported, upto 256 GB
365             Memory Card Not Supported
392             Memory Card Not Supported
504             Memory Card Not Supported
570       Memory Card (Hybrid), upto 2 TB
613                  Memory Card (Hybrid)
682       Memory Card (Hybrid), upto 2 TB
721             Memory Card Not Supported
726     Memory Card (Hybrid), upto 256 GB
844    Memory Card Supported, upto 128 GB
894    Memory Card Supported, upto 256 GB
993     Memory Card (Hybrid), upto 256 GB
Name: os, dtype: object

In [ ]:
# ya os ka value apki orignial df ma hona chaya tha

In [ ]:
# before 
df.loc[os_temp_df.index,'card']

159    Memory Card Not Supported
271    Memory Card Not Supported
306    Memory Card Not Supported
322    Memory Card Not Supported
365    Memory Card Not Supported
392    Memory Card Not Supported
504    Memory Card Not Supported
570    Memory Card Not Supported
613    Memory Card Not Supported
682    Memory Card Not Supported
721    Memory Card Not Supported
726    Memory Card Not Supported
844    Memory Card Not Supported
894    Memory Card Not Supported
993    Memory Card Not Supported
Name: card, dtype: object

In [241]:
# assign them apply the operating 
df.loc[os_temp_df.index,'card'] = os_temp_df['os']

In [242]:
# after 
df.loc[os_temp_df.index,'card']

159             Memory Card Not Supported
271                 Memory Card Supported
306             Memory Card Not Supported
322    Memory Card Supported, upto 256 GB
365             Memory Card Not Supported
392             Memory Card Not Supported
504             Memory Card Not Supported
570       Memory Card (Hybrid), upto 2 TB
613                  Memory Card (Hybrid)
682       Memory Card (Hybrid), upto 2 TB
721             Memory Card Not Supported
726     Memory Card (Hybrid), upto 256 GB
844    Memory Card Supported, upto 128 GB
894    Memory Card Supported, upto 256 GB
993     Memory Card (Hybrid), upto 256 GB
Name: card, dtype: object

In [244]:
df.loc[os_temp_df.index,'card'].value_counts()

card
Memory Card Not Supported             6
Memory Card Supported, upto 256 GB    2
Memory Card (Hybrid), upto 2 TB       2
Memory Card (Hybrid), upto 256 GB     2
Memory Card Supported                 1
Memory Card (Hybrid)                  1
Memory Card Supported, upto 128 GB    1
Name: count, dtype: int64

In [ ]:
# now everything is fine

In [245]:
# chalo now back  to our operating system ma ata ha 
df['os'].value_counts()

os
Android v12                           394
Android v11                           273
Android v13                            91
Android v10                            69
Android v9.0 (Pie)                     29
Android v10.0                          23
iOS v16                                15
iOS v15                                12
Android v8.1 (Oreo)                    10
iOS v14                                 6
Memory Card Not Supported               6
Android v11.0                           4
Android v8.0 (Oreo)                     4
iOS v13                                 4
iOS v15.0                               3
Harmony v2.0                            2
Memory Card (Hybrid), upto 2 TB         2
Memory Card (Hybrid), upto 256 GB       2
HarmonyOS v2.0                          2
Android v5.1.1 (Lollipop)               2
EMUI v12                                2
Android v6.0 (Marshmallow)              2
Memory Card Supported, upto 256 GB      2
Android v12.1                           2
iOS v14.0                               2
Memory Card Supported, upto 128 GB      1
HarmonyOS                               1
RTOS (Series 30+)                       1
Android v7.1 (Nougat)                   1
Hongmeng OS v4.0                        1
Android                                 1
Android v5.1 (Lollipop)                 1
Memory Card (Hybrid)                    1
iOS v10                                 1
Pragati OS (Powered by Android)         1
Bluetooth                               1
Hongmeng OS v3.0                        1
Android v4.4.2 (KitKat)                 1
iOS v17                                 1
Memory Card Supported                   1
iOS v12.3                               1
iOS v13.0                               1
HarmonyOS v2                            1
Android v9 (Pie)                        1
Name: count, dtype: int64

In [247]:
df[df['os'] == 'Bluetooth']

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
486,488,Nokia 8000 4G,6899,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon 210, Quad Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth

In [254]:
# replace the bluetooth with np.nan
df[df['os'] == 'Bluetooth']['os']

486    Bluetooth
Name: os, dtype: object

In [269]:
bluetooth_df = df[df['os'] == 'Bluetooth']
bluetooth_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
486,488,Nokia 8000 4G,6899,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon 210, Quad Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth

In [ ]:
# before 
df.loc[bluetooth_df.index,'os']

486    Bluetooth
Name: os, dtype: object

In [273]:
# replace it with nan
df.loc[bluetooth_df.index,'os'] = np.nan

In [ ]:
# after yes we change it
df.loc[bluetooth_df.index,'os']

486    NaN
Name: os, dtype: object

In [ ]:
# jaha par bhi apka memory card mila waha nana

In [249]:
temp_df = df[df['os'].str.contains('Memory Card')]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB","Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB","Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid),Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB","Memory Card (Hybrid), upto 2 TB"
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB","Memory Card (Hybrid), upto 256 GB"
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB","Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB","Memory Card Supported, upto 256 GB"
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB","Memory Card (Hybrid), upto 256 GB"

In [ ]:
# before
df.loc[temp_df.index,'os']

159             Memory Card Not Supported
271                 Memory Card Supported
306             Memory Card Not Supported
322    Memory Card Supported, upto 256 GB
365             Memory Card Not Supported
392             Memory Card Not Supported
504             Memory Card Not Supported
570       Memory Card (Hybrid), upto 2 TB
613                  Memory Card (Hybrid)
682       Memory Card (Hybrid), upto 2 TB
721             Memory Card Not Supported
726     Memory Card (Hybrid), upto 256 GB
844    Memory Card Supported, upto 128 GB
894    Memory Card Supported, upto 256 GB
993     Memory Card (Hybrid), upto 256 GB
Name: os, dtype: object

In [ ]:
# replace with np.nan apply operation
df.loc[temp_df.index,'os'] = np.nan

In [ ]:
# after (operation successful)
df.loc[temp_df.index,'os']

159    NaN
271    NaN
306    NaN
322    NaN
365    NaN
392    NaN
504    NaN
570    NaN
613    NaN
682    NaN
721    NaN
726    NaN
844    NaN
894    NaN
993    NaN
Name: os, dtype: object

In [275]:
df['os'].value_counts()

os
Android v12                        394
Android v11                        273
Android v13                         91
Android v10                         69
Android v9.0 (Pie)                  29
Android v10.0                       23
iOS v16                             15
iOS v15                             12
Android v8.1 (Oreo)                 10
iOS v14                              6
Android v11.0                        4
iOS v13                              4
Android v8.0 (Oreo)                  4
iOS v15.0                            3
HarmonyOS v2.0                       2
Android v5.1.1 (Lollipop)            2
Android v6.0 (Marshmallow)           2
Harmony v2.0                         2
EMUI v12                             2
Android v12.1                        2
iOS v14.0                            2
HarmonyOS                            1
Android                              1
Hongmeng OS v4.0                     1
Android v7.1 (Nougat)                1
Android v4.4.2 (KitKat)              1
RTOS (Series 30+)                    1
iOS v10                              1
Pragati OS (Powered by Android)      1
Hongmeng OS v3.0                     1
Android v5.1 (Lollipop)              1
iOS v17                              1
iOS v12.3                            1
iOS v13.0                            1
HarmonyOS v2                         1
Android v9 (Pie)                     1
Name: count, dtype: int64

## check all coloumns

In [ ]:
# ab aap har ek columns ma jaho aor deko kahi koi alag values tho nahi ha 
# value count karo har kisi par

In [277]:
df.columns

Index(['index', 'model', 'price', 'rating', 'sim', 'processor', 'ram',
       'battery', 'display', 'camera', 'card', 'os'],
      dtype='object')

In [279]:
df['model'].value_counts()

model
OnePlus 11 5G                              1
Vivo V25e                                  1
Realme Narzo 50 5G (4GB RAM + 64GB)        1
itel Vision 3                              1
OPPO A96 4G                                1
                                          ..
Samsung Galaxy A73 5G (8GB RAM + 256GB)    1
Realme 9 5G SE (8GB RAM + 128GB)           1
Poco F4 5G                                 1
Infinix Note 12                            1
Samsung Galaxy M52s 5G                     1
Name: count, Length: 982, dtype: int64

In [276]:
df['sim'].value_counts()

sim
Dual Sim, 3G, 4G, VoLTE, Wi-Fi                               318
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      268
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           155
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster                53
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster           52
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                           46
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster                    46
Dual Sim, 3G, 4G, Wi-Fi                                        7
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                  7
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      7
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster                5
Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                          4
Single Sim, 3G, 4G, VoLTE, Wi-Fi                               3
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi                       3
Dual Sim, 3G, 4G, Wi-Fi, NFC                                   2
Single Sim, 3G, 4G, Wi-Fi, NFC                                 1
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           1
Dual Sim, 3G, 4G, VoLTE                                        1
Dual Sim, 3G, Wi-Fi                                            1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster           1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC, IR Blaster      1
Name: count, dtype: int64

In [280]:
df['processor'].value_counts()

processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor      29
Helio P35, Octa Core, 2.3 GHz Processor             27
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor    26
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor     23
Snapdragon 695, Octa Core, 2.2 GHz Processor        23
                                                    ..
Tiger T310, Quad Core, 2 GHz Processor               1
Snapdragon 835, Octa Core, 2.35 GHz Processor        1
Sanpdragon 680, Octa Core, 2.4 GHz Processor         1
Snapdragon  210, Quad Core, 1.1 GHz Processor        1
Google  Tensor 3, Octa Core Processor                1
Name: count, Length: 276, dtype: int64

In [281]:
df['ram'].value_counts()

ram
8 GB RAM, 128 GB inbuilt     266
6 GB RAM, 128 GB inbuilt     190
4 GB RAM, 64 GB inbuilt      143
12 GB RAM, 256 GB inbuilt     70
8 GB RAM, 256 GB inbuilt      70
4 GB RAM, 128 GB inbuilt      62
3 GB RAM, 32 GB inbuilt       37
6 GB RAM, 64 GB inbuilt       29
2 GB RAM, 32 GB inbuilt       24
3 GB RAM, 64 GB inbuilt       15
12 GB RAM, 512 GB inbuilt     10
6 GB RAM, 256 GB inbuilt       7
16 GB RAM, 256 GB inbuilt      6
4 GB RAM, 32 GB inbuilt        6
1 GB RAM, 16 GB inbuilt        6
2 GB RAM, 16 GB inbuilt        4
6 GB RAM, 1 TB inbuilt         4
6 GB RAM, 512 GB inbuilt       4
12 GB RAM, 128 GB inbuilt      4
2 GB RAM, 64 GB inbuilt        4
4 GB RAM, 256 GB inbuilt       3
16 GB RAM, 512 GB inbuilt      3
3 GB RAM, 16 GB inbuilt        2
8 GB RAM, 512 GB inbuilt       2
512 MB RAM, 4 GB inbuilt       2
64 GB inbuilt                  2
512 GB inbuilt                 1
64 MB RAM, 128 MB inbuilt      1
18 GB RAM, 256 GB inbuilt      1
18 GB RAM, 512 GB inbuilt      1
4 GB RAM, 512 GB inbuilt       1
1 GB RAM, 8 GB inbuilt         1
12 GB RAM, 1 TB inbuilt        1
Name: count, dtype: int64

In [284]:
df['battery'].value_counts()

battery
5000 mAh Battery with 33W Fast Charging      103
5000 mAh Battery with 18W Fast Charging       89
5000 mAh Battery                              74
5000 mAh Battery with 67W Fast Charging       29
5000 mAh Battery with 10W Fast Charging       28
                                            ...
6000 mAh Battery with 120W Fast Charging       1
4700 mAh Battery with Fast Charging            1
21000 mAh Battery with 33W Fast Charging       1
4200 mAh Battery with 66W Fast Charging        1
5000 mAh Battery with 68.2W Fast Charging      1
Name: count, Length: 230, dtype: int64

In [286]:
df['display'].value_counts()

display
6.67 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole    53
6.5 inches, 720 x 1600 px Display with Water Drop Notch        36
6.7 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole     25
6.52 inches, 720 x 1600 px Display with Water Drop Notch       23
6.5 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole      22
                                                               ..
6 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole         1
6.73 inches, 1440 x 3412 px, 144 Hz Display with Punch Hole     1
6.58 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole      1
6.56 inches, 720 x 1612 px, 90 Hz Display with Punch Hole       1
6.8 inches, 1080 x 2400 px Display with Punch Hole              1
Name: count, Length: 347, dtype: int64

In [287]:
df['camera'].value_counts()

camera
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera           40
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera           38
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera           34
13 MP + 2 MP Dual Rear & 5 MP Front Camera                     23
13 MP Rear & 5 MP Front Camera                                 20
                                                               ..
20 MP + 16 MP Dual Rear & 16 MP Front Camera                    1
108 MP + 50 MP + 48 MP Triple Rear & 32 MP Front Camera         1
64 MP + 64 MP + 64 MP Triple Rear & 16 MP Front Camera          1
64 MP + 13 MP Dual Rear & 16 MP Front Camera                    1
48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP Front Camera     1
Name: count, Length: 285, dtype: int64

In [288]:
df['card'].value_counts()

card
Memory Card Not Supported              354
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         90
Memory Card Supported                   90
Memory Card Supported, upto 256 GB      89
Memory Card (Hybrid)                    31
Memory Card (Hybrid), upto 256 GB       15
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       7
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card (Hybrid), upto 2 TB          3
Memory Card Supported, upto 1000 GB      1
Name: count, dtype: int64

In [289]:
df['os'].value_counts()

os
Android v12                        394
Android v11                        273
Android v13                         91
Android v10                         69
Android v9.0 (Pie)                  29
Android v10.0                       23
iOS v16                             15
iOS v15                             12
Android v8.1 (Oreo)                 10
iOS v14                              6
Android v11.0                        4
iOS v13                              4
Android v8.0 (Oreo)                  4
iOS v15.0                            3
HarmonyOS v2.0                       2
Android v5.1.1 (Lollipop)            2
Android v6.0 (Marshmallow)           2
Harmony v2.0                         2
EMUI v12                             2
Android v12.1                        2
iOS v14.0                            2
HarmonyOS                            1
Android                              1
Hongmeng OS v4.0                     1
Android v7.1 (Nougat)                1
Android v4.4.2 (KitKat)              1
RTOS (Series 30+)                    1
iOS v10                              1
Pragati OS (Powered by Android)      1
Hongmeng OS v3.0                     1
Android v5.1 (Lollipop)              1
iOS v17                              1
iOS v12.3                            1
iOS v13.0                            1
HarmonyOS v2                         1
Android v9 (Pie)                     1
Name: count, dtype: int64

In [ ]:
# now har ek column ma uska data ki hi value ha . 
# validity issue completed

# part 2

In [ ]:
# now we start data cleaning part 2 on smartphone dataset
# now we solve the tideness issue (structure)

In [290]:
df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

# model col
we create a new coloumn brand name

In [293]:
df['model'].str.split(' ')

0                              [OnePlus, 11, 5G]
1               [OnePlus, Nord, CE, 2, Lite, 5G]
2                     [Samsung, Galaxy, A14, 5G]
3                      [Motorola, Moto, G62, 5G]
4                        [Realme, 10, Pro, Plus]
                          ...
1015            [Motorola, Moto, Edge, S30, Pro]
1016                             [Honor, X8, 5G]
1017    [POCO, X4, GT, 5G, (8GB, RAM, +, 256GB)]
1018                   [Motorola, Moto, G91, 5G]
1019                 [Samsung, Galaxy, M52s, 5G]
Name: model, Length: 982, dtype: object

In [294]:
df['model'].str.split(' ').str.get(0)

0        OnePlus
1        OnePlus
2        Samsung
3       Motorola
4         Realme
          ...
1015    Motorola
1016       Honor
1017        POCO
1018    Motorola
1019     Samsung
Name: model, Length: 982, dtype: object

In [296]:
# this is our brand coloumn series
brand_names = df['model'].str.split(' ').str.get(0)
brand_names

0        OnePlus
1        OnePlus
2        Samsung
3       Motorola
4         Realme
          ...
1015    Motorola
1016       Honor
1017        POCO
1018    Motorola
1019     Samsung
Name: model, Length: 982, dtype: object

In [297]:
# you can insert column at specific postion 
# waran hum add karta tho ya last postion par jayega
df.insert(
    loc=1,  # postion of column you add
    column= 'brand_names', # name of the oclumn
    value= brand_names
)

In [298]:
df

,index,brand_names,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1016,1018,Honor,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [299]:
# kahi par capital case hoga kahi par small case
# tho different categories bana gi 
# now lets make them in lowecase good stragtey
df['brand_names'].str.lower()

0        oneplus
1        oneplus
2        samsung
3       motorola
4         realme
          ...
1015    motorola
1016       honor
1017        poco
1018    motorola
1019     samsung
Name: brand_names, Length: 982, dtype: object

In [300]:
df['brand_names'] = df['brand_names'].str.lower()

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\63663228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['brand_names'] = df['brand_names'].str.lower()

## price
price hamana phala hi tick kar diya tha

## sim 
- deko sara hi phone lag bad dual sim ha
- 3G,4G bhi sara hi phone ha
- 4G ,5G sa difference aa raha ha (this is good differenaley factor)
- Nfc (it is very expensive phone)
- blaster ( which you control the frige ,ac extra)

So We create the 3 columns from the sim     
1. 5G phone it is or 4G
2. has_ nfc phone yes or no
3. has_irc_baster yes or no

In [ ]:
has_5g = df['sim'].str.contains('5G')
has_5g

0       True
1       True
2       True
3       True
4       True
        ...
1015    True
1016    True
1017    True
1018    True
1019    True
Name: sim, Length: 982, dtype: bool

In [305]:
df['sim'].value_counts()

sim
Dual Sim, 3G, 4G, VoLTE, Wi-Fi                               318
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      268
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           155
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster                53
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster           52
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                           46
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster                    46
Dual Sim, 3G, 4G, Wi-Fi                                        7
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                  7
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      7
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster                5
Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                          4
Single Sim, 3G, 4G, VoLTE, Wi-Fi                               3
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi                       3
Dual Sim, 3G, 4G, Wi-Fi, NFC                                   2
Single Sim, 3G, 4G, Wi-Fi, NFC                                 1
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           1
Dual Sim, 3G, 4G, VoLTE                                        1
Dual Sim, 3G, Wi-Fi                                            1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster           1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC, IR Blaster      1
Name: count, dtype: int64

In [306]:
has_nfc = df['sim'].str.contains('NFC')
has_nfc

0        True
1       False
2       False
3       False
4       False
        ...
1015    False
1016    False
1017     True
1018     True
1019    False
Name: sim, Length: 982, dtype: bool

In [307]:
has_irbaster = df['sim'].str.contains('IR Blaster')
has_irbaster.value_counts()

sim
False    824
True     158
Name: count, dtype: int64

In [308]:
# now insert the coloumns
df.insert(6,'has_5g',has_5g)
df.insert(7,'has_nfc',has_nfc)
df.insert(8,'has_ir_blaster',has_irbaster)

In [309]:
df

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,motorola,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1016,1018,honor,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,poco,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,motorola,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,samsung,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

## processor
it have 3 pieces of information
- processor name 
- processor kitna core ka ha dual,quartar,hex,octo
- processor speed

We create the 4 columns
- processor name 
- processor brand
- number of core in processor
- speed of the processsor

In [310]:
df['processor'].str.split(',')

0       [Snapdragon 8 Gen2,  Octa Core,  3.2 GHz Proce...
1        [Snapdragon 695,  Octa Core,  2.2 GHz Processor]
2           [Exynos 1330,  Octa Core,  2.4 GHz Processor]
3       [Snapdragon  695,  Octa Core,  2.2 GHz Processor]
4        [Dimensity 1080,  Octa Core,  2.6 GHz Processor]
                              ...
1015    [Snapdragon 8 Gen1,  Octa Core,  3 GHz Processor]
1016    [Snapdragon  480+,  Octa Core,  2.2 GHz Proces...
1017    [Dimensity 8100,  Octa Core,  2.85 GHz Processor]
1018     [Snapdragon 695,  Octa Core,  2.2 GHz Processor]
1019                                [Octa Core Processor]
Name: processor, Length: 982, dtype: object

In [312]:
processor_name = df['processor'].str.split(',').str.get(0)
processor_name

0         Snapdragon 8 Gen2
1            Snapdragon 695
2               Exynos 1330
3           Snapdragon  695
4            Dimensity 1080
               ...
1015      Snapdragon 8 Gen1
1016       Snapdragon  480+
1017         Dimensity 8100
1018         Snapdragon 695
1019    Octa Core Processor
Name: processor, Length: 982, dtype: object

In [314]:
num_cores = df['processor'].str.split(',').str.get(1)
num_cores

0        Octa Core
1        Octa Core
2        Octa Core
3        Octa Core
4        Octa Core
           ...
1015     Octa Core
1016     Octa Core
1017     Octa Core
1018     Octa Core
1019           NaN
Name: processor, Length: 982, dtype: object

In [316]:
processor_speed = df['processor'].str.split(',').str.get(2)
processor_speed

0         3.2 GHz Processor
1         2.2 GHz Processor
2         2.4 GHz Processor
3         2.2 GHz Processor
4         2.6 GHz Processor
               ...
1015        3 GHz Processor
1016      2.2 GHz Processor
1017     2.85 GHz Processor
1018      2.2 GHz Processor
1019                    NaN
Name: processor, Length: 982, dtype: object

In [317]:
# now insert this columns
df.insert(10,'processor_name',processor_name)
df.insert(11,'num_cores',num_cores)
df.insert(12,'processor_speed',processor_speed)

In [319]:
df.head()

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,num_cores,processor_speed,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,Octa Core,3.2 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,Octa Core,2.4 GHz Processor,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity 1080,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [320]:
df['processor_name'].value_counts()

processor_name
Dimensity 700 5G        29
Helio P35               28
Snapdragon 8+ Gen1      26
Snapdragon 8 Gen2       23
Snapdragon 695          23
                        ..
Google  Tensor G2        1
Snapdragon  8+ Gen1      1
Snapdragon  720G         1
Snapdragon 888+          1
Google  Tensor 3         1
Name: count, Length: 247, dtype: int64

In [322]:
# we do first strip operation
df['processor_name'] = df['processor_name'].str.strip()

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\1321582111.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processor_name'] = df['processor_name'].str.strip()

In [323]:
df[df['processor_name'].str.contains('Core')]

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,num_cores,processor_speed,ram,battery,display,camera,card,os
118,120,tesla,Tesla Pi Phone,69999,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"16 GB RAM, 512 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,Android v13
143,145,jio,Jio Phone 3,4499,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Quad Core, 1.4 GHz Processor",Quad Core,1.4 GHz Processor,NaN,"2 GB RAM, 64 GB inbuilt",2800 mAh Battery,"5 inches, 720 x 1280 px Display",5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v8.1 (Oreo)
188,190,ikall,iKall Z19 Pro,8099,60.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Quad Core, 1.6 GHz Processor",Quad Core,1.6 GHz Processor,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.5 inches, 720 x 1600 px Display with Water D...",13 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",Android v11.0
201,203,samsung,Samsung Galaxy A13,14450,75.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Octa Core, 2 GHz Processor",Octa Core,2 GHz Processor,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.6 inches, 1080 x 2408 px Display with Water ...",50 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
309,311,samsung,Samsung Galaxy A13 (4GB RAM + 128GB),14999,75.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Octa Core, 2 GHz Processor",Octa Core,2 GHz Processor,NaN,"4 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.6 inches, 1080 x 2408 px Display with Water ...",50 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
315,317,itel,itel S16 Pro,6990,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Quad Core, 1.3 GHz Processor",Quad Core,1.3 GHz Processor,NaN,"2 GB RAM, 32 GB inbuilt",4000 mAh Battery,"6.6 inches, 1600 x 720 px Display with Punch Hole",8 MP + 2 MP + 0.3 MP Triple Rear & 8 MP Front ...,"Memory Card Supported, upto 32 GB",Android v10
496,498,samsung,Samsung Galaxy A15,15990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 64 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 8 MP + 5 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 1 TB",Android v12
529,531,samsung,Samsung Galaxy F14,14990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",False,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.62 inches, 2408 x 1080 px Display with Punch...",50 MP + 5 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
587,589,samsung,Samsung Galaxy A13 (6GB RAM + 128GB),16499,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Octa Core, 2 GHz Processor",Octa Core,2 GHz Processor,NaN,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.6 inches, 1080 x 2408 px Display with Water ...",50 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
758,760,ikall,iKall Z19,7999,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Quad Core, 1.6 GHz Processor",Quad Core,1.6 GHz Processor,NaN,"4 GB RAM, 32 GB inbuilt",5000 mAh Battery,"6.5 inches, 720 x 1600 px Display with Water D...",20 MP Rear & 13 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",Android v11.0
778,780,tecno,Tecno Spark Go 2022,6249,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Octa Core, 2.2 GHz Processor",Octa Core,2.2 GHz Processor,NaN,"2 GB RAM, 32 GB inbuilt",5000 mAh Battery,"6.51 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v11
794,796,itel,itel A56,5490,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Quad Core, 1.3 GHz Processor",Quad Core,1.3 GHz Processor,NaN,"1 GB RAM, 16 GB inbuilt",4000 mAh Battery,"6 inches, 720 x 1600 px Display",8 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Android v9.0 (Pie)
825,827,samsung,Samsung Galaxy S23 FE 5G,54999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",4500 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Punch ...",64 MP Quad Rear & 32 MP Front Camera,Memory Card Not Supported,Android v12
826,828,samsung,Samsung Galaxy M51s 5G,24990,72.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 128 GB inbuilt",6000 mAh Battery with Fast Charging,"6.7 inches, 1080 x 2400 px Display with Punch ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12
875,877,huawei,Huawei Nova Y61,21990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.52 inches, 720 x 1600 px Display with Water ...",50 MP + 2 MP Triple Rear & 5 MP Front Camera,Memory Card (Hybrid),EMUI v12
948,950,samsung,Samsung Galaxy M35,22999,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",False,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",6000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12
949,951,samsung,Samsung Galaxy A05,12990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.5 inches, 720 x 1560 px Display with Water D...",48 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
991,993,samsung,Samsung Galaxy A11,9990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Octa Core, 1.8 GHz Processor",Octa Core,1.8 GHz Processor,NaN,"2 GB RAM, 32 GB inbuilt",4000 mAh Battery with 15W Fast Charging,"6.4 inches, 720 x 1560 px Display with Punch Hole",13 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 512 GB",Android v10
1005,1007,ikall,iKall Z18,6799,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Quad Core, 1.3 GHz Processor",Quad Core,1.3 GHz Processor,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.82 inches, 720 x 1560 px Display with Punch ...",20 MP Rear & 13 MP Front Camera,"Memory Card (Hybrid), upto 64 GB",Android v10.0
1019,1021,samsung,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [ ]:
# we have have to do shifting

In [328]:
df[df['processor_name'].str.contains('Core')][[ 'processor_name', 'num_cores','processor_speed']]

           processor_name           num_cores processor_speed
118   Octa Core Processor                 NaN             NaN
143             Quad Core   1.4 GHz Processor             NaN
188             Quad Core   1.6 GHz Processor             NaN
201             Octa Core     2 GHz Processor             NaN
309             Octa Core     2 GHz Processor             NaN
315             Quad Core   1.3 GHz Processor             NaN
496   Octa Core Processor                 NaN             NaN
529   Octa Core Processor                 NaN             NaN
587             Octa Core     2 GHz Processor             NaN
758             Quad Core   1.6 GHz Processor             NaN
778             Octa Core   2.2 GHz Processor             NaN
794             Quad Core   1.3 GHz Processor             NaN
825   Octa Core Processor                 NaN             NaN
826   Octa Core Processor                 NaN             NaN
875   Octa Core Processor                 NaN             NaN
948   Octa Core Processor                 NaN             NaN
949   Octa Core Processor                 NaN             NaN
991             Octa Core   1.8 GHz Processor             NaN
1005            Quad Core   1.3 GHz Processor             NaN
1019  Octa Core Processor                 NaN             NaN

In [331]:
# lets do shifting 
temp_df = df[df['processor_name'].str.contains('Core')][[ 'processor_name', 'num_cores','processor_speed']].shift(1,axis=1)
temp_df

     processor_name            num_cores     processor_speed
118            None  Octa Core Processor                 NaN
143            None            Quad Core   1.4 GHz Processor
188            None            Quad Core   1.6 GHz Processor
201            None            Octa Core     2 GHz Processor
309            None            Octa Core     2 GHz Processor
315            None            Quad Core   1.3 GHz Processor
496            None  Octa Core Processor                 NaN
529            None  Octa Core Processor                 NaN
587            None            Octa Core     2 GHz Processor
758            None            Quad Core   1.6 GHz Processor
778            None            Octa Core   2.2 GHz Processor
794            None            Quad Core   1.3 GHz Processor
825            None  Octa Core Processor                 NaN
826            None  Octa Core Processor                 NaN
875            None  Octa Core Processor                 NaN
948            None  Octa Core Processor                 NaN
949            None  Octa Core Processor                 NaN
991            None            Octa Core   1.8 GHz Processor
1005           None            Quad Core   1.3 GHz Processor
1019           None  Octa Core Processor                 NaN

In [335]:
temp_df.values

array([[None, 'Octa Core Processor', nan],
       [None, 'Quad Core', ' 1.4\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.6\u2009GHz Processor'],
       [None, 'Octa Core', ' 2\u2009GHz Processor'],
       [None, 'Octa Core', ' 2\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.3\u2009GHz Processor'],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core', ' 2\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.6\u2009GHz Processor'],
       [None, 'Octa Core', ' 2.2\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.3\u2009GHz Processor'],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core', ' 1.8\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.3\u2009GHz Processor'],
       [None, 'Octa Core Processor', nan]], dtype=object)

In [ ]:
# before 
df.loc[temp_df.index,['processor_name', 'num_cores','processor_speed']]

           processor_name           num_cores processor_speed
118   Octa Core Processor                 NaN             NaN
143             Quad Core   1.4 GHz Processor             NaN
188             Quad Core   1.6 GHz Processor             NaN
201             Octa Core     2 GHz Processor             NaN
309             Octa Core     2 GHz Processor             NaN
315             Quad Core   1.3 GHz Processor             NaN
496   Octa Core Processor                 NaN             NaN
529   Octa Core Processor                 NaN             NaN
587             Octa Core     2 GHz Processor             NaN
758             Quad Core   1.6 GHz Processor             NaN
778             Octa Core   2.2 GHz Processor             NaN
794             Quad Core   1.3 GHz Processor             NaN
825   Octa Core Processor                 NaN             NaN
826   Octa Core Processor                 NaN             NaN
875   Octa Core Processor                 NaN             NaN
948   Octa Core Processor                 NaN             NaN
949   Octa Core Processor                 NaN             NaN
991             Octa Core   1.8 GHz Processor             NaN
1005            Quad Core   1.3 GHz Processor             NaN
1019  Octa Core Processor                 NaN             NaN

In [336]:
# apply the operation of assign it 
df.loc[temp_df.index,['processor_name', 'num_cores','processor_speed']] = temp_df.values

In [337]:
# after check your opertion 
df.loc[temp_df.index,['processor_name', 'num_cores','processor_speed']]

     processor_name            num_cores     processor_speed
118            None  Octa Core Processor                 NaN
143            None            Quad Core   1.4 GHz Processor
188            None            Quad Core   1.6 GHz Processor
201            None            Octa Core     2 GHz Processor
309            None            Octa Core     2 GHz Processor
315            None            Quad Core   1.3 GHz Processor
496            None  Octa Core Processor                 NaN
529            None  Octa Core Processor                 NaN
587            None            Octa Core     2 GHz Processor
758            None            Quad Core   1.6 GHz Processor
778            None            Octa Core   2.2 GHz Processor
794            None            Quad Core   1.3 GHz Processor
825            None  Octa Core Processor                 NaN
826            None  Octa Core Processor                 NaN
875            None  Octa Core Processor                 NaN
948            None  Octa Core Processor                 NaN
949            None  Octa Core Processor                 NaN
991            None            Octa Core   1.8 GHz Processor
1005           None            Quad Core   1.3 GHz Processor
1019           None  Octa Core Processor                 NaN

In [339]:
# now check all processor 
df[df['processor_name'] == '(28 nm)']

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,num_cores,processor_speed,ram,battery,display,camera,card,os
856,858,samsung,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"(28 nm), Quad Core, 1.5 GHz Processor",(28 nm),Quad Core,1.5 GHz Processor,"1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10

In [ ]:
# before .
df.loc[856,'processor_name']

'(28 nm)'

In [342]:
# lets apply the assign operation.
df.loc[856,'processor_name'] = 'Mediatek MT6739'

In [343]:
df.loc[856,'processor_name']

'Mediatek MT6739'

now make a new column called processor brand .

In [344]:
df['processor_name'].str.split(' ')

0       [Snapdragon, 8, Gen2]
1           [Snapdragon, 695]
2              [Exynos, 1330]
3         [Snapdragon, , 695]
4           [Dimensity, 1080]
                ...
1015    [Snapdragon, 8, Gen1]
1016     [Snapdragon, , 480+]
1017        [Dimensity, 8100]
1018        [Snapdragon, 695]
1019                     None
Name: processor_name, Length: 982, dtype: object

In [ ]:
df['processor_name'].str.split(' ').str.get(0).str.lower()

0       snapdragon
1       snapdragon
2           exynos
3       snapdragon
4        dimensity
           ...
1015    snapdragon
1016    snapdragon
1017     dimensity
1018    snapdragon
1019          None
Name: processor_name, Length: 982, dtype: object

In [352]:
processor_brand= df['processor_name'].str.split(' ').str.get(0).str.lower()
processor_brand

0       snapdragon
1       snapdragon
2           exynos
3       snapdragon
4        dimensity
           ...
1015    snapdragon
1016    snapdragon
1017     dimensity
1018    snapdragon
1019          None
Name: processor_name, Length: 982, dtype: object

In [353]:
df.insert(11,'processor_brand',processor_brand)

In [354]:
df.head()

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,snapdragon,Octa Core,3.2 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,snapdragon,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,exynos,Octa Core,2.4 GHz Processor,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,snapdragon,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity 1080,dimensity,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [355]:
# lets check the num cores
df['num_cores'].value_counts()

num_cores
 Octa Core              865
 Hexa Core               31
 Quad Core               31
 Octa Core Processor     19
Octa Core Processor       9
 Hexa Core Processor      8
Quad Core                 6
Octa Core                 5
 Dual Core                1
Name: count, dtype: int64

In [358]:
df['num_cores'] = df['num_cores'].str.strip()

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\1868154006.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_cores'] = df['num_cores'].str.strip()

In [359]:
df['num_cores'].value_counts()

num_cores
Octa Core              870
Quad Core               37
Hexa Core               31
Octa Core Processor     28
Hexa Core Processor      8
Dual Core                1
Name: count, dtype: int64

In [ ]:
# replace it  the octo core
df['num_cores'] = df['num_cores'].str.replace('Octa Core Processor','Octa Core')

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\1170573373.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_cores'] = df['num_cores'].str.replace('Octa Core Processor','Octa Core')

In [366]:
# replace it hexa core
df['num_cores'] = df['num_cores'].str.replace('Hexa Core Processor','Hexa Core')

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\1822141873.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_cores'] = df['num_cores'].str.replace('Hexa Core Processor','Hexa Core')

In [367]:
df['num_cores'].value_counts()

num_cores
Octa Core    898
Hexa Core     39
Quad Core     37
Dual Core      1
Name: count, dtype: int64

In [ ]:
# wow full clean table so you can do analysis on it.

In [ ]:
# now lets anlysis the processor speed

In [368]:
df['processor_speed'].value_counts()

processor_speed
2 GHz Processor       146
2.2 GHz Processor     134
2.4 GHz Processor     128
3.2 GHz Processor      94
2.3 GHz Processor      86
3 GHz Processor        53
2.84 GHz Processor     36
2.05 GHz Processor     28
2.5 GHz Processor      23
1.8 GHz Processor      23
1.6 GHz Processor      20
2.85 GHz Processor     19
3.22 GHz Processor     18
3.1 GHz Processor      15
2.6 GHz Processor      14
2.9 GHz Processor      13
1.82 GHz Processor     10
1.3 GHz Processor      10
2.73 GHz Processor      9
2.8 GHz Processor       9
3.05 GHz Processor      8
2.36 GHz Processor      8
2.7 GHz Processor       5
1.4 GHz Processor       5
2.65 GHz Processor      5
1.5 GHz Processor       4
2.96 GHz Processor      3
2.86 GHz Processor      3
1.1 GHz Processor       2
3.13 GHz Processor      2
2.35 GHz Processor      1
2.37 GHz Processor      1
1.99 GHz Processor      1
1.95 GHz Processor      1
2.1 GHz Processor       1
1.2 GHz Processor       1
Name: count, dtype: int64

In [376]:
# now huma gega hertz ya number chaya . 
# word lika hona ki jarruat nahi ha 
df['processor_speed'].str.strip().str.split()

0        [3.2, GHz, Processor]
1        [2.2, GHz, Processor]
2        [2.4, GHz, Processor]
3        [2.2, GHz, Processor]
4        [2.6, GHz, Processor]
                 ...
1015       [3, GHz, Processor]
1016     [2.2, GHz, Processor]
1017    [2.85, GHz, Processor]
1018     [2.2, GHz, Processor]
1019                       NaN
Name: processor_speed, Length: 982, dtype: object

In [ ]:
# isma unicode character ha for split lakin na default unicdoe par hi kar diya

df['processor_speed'].str.strip().str.split().str.get(0)

0        3.2
1        2.2
2        2.4
3        2.2
4        2.6
        ...
1015       3
1016     2.2
1017    2.85
1018     2.2
1019     NaN
Name: processor_speed, Length: 982, dtype: object

In [ ]:
df['processor_speed'].str.strip().str.split().str.get(0).astype(np.float64)

0       3.20
1       2.20
2       2.40
3       2.20
4       2.60
        ...
1015    3.00
1016    2.20
1017    2.85
1018    2.20
1019     NaN
Name: processor_speed, Length: 982, dtype: float64

In [382]:
# before
df['processor_speed']

0         3.2 GHz Processor
1         2.2 GHz Processor
2         2.4 GHz Processor
3         2.2 GHz Processor
4         2.6 GHz Processor
               ...
1015        3 GHz Processor
1016      2.2 GHz Processor
1017     2.85 GHz Processor
1018      2.2 GHz Processor
1019                    NaN
Name: processor_speed, Length: 982, dtype: object

In [383]:
# now assign it to processor 
df['processor_speed'] = df['processor_speed'].str.strip().str.split().str.get(0).astype(np.float64)

C:\Users\sumit\AppData\Local\Temp\ipykernel_14972\632766245.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processor_speed'] = df['processor_speed'].str.strip().str.split().str.get(0).astype(np.float64)

In [384]:
df['processor_speed']

0       3.20
1       2.20
2       2.40
3       2.20
4       2.60
        ...
1015    3.00
1016    2.20
1017    2.85
1018    2.20
1019     NaN
Name: processor_speed, Length: 982, dtype: float64

In [ ]:
# deko abhi na upar ek matrix ki value ko dursa matrix ki value sa replace kiya
# aor hamna ek scaler ko dursa scaler sa replace kiya

## ram
ram have two things 
- ram and internal memory 
- task to to make two new columns

In [385]:
df['ram']

0       12 GB RAM, 256 GB inbuilt
1        6 GB RAM, 128 GB inbuilt
2         4 GB RAM, 64 GB inbuilt
3        6 GB RAM, 128 GB inbuilt
4        6 GB RAM, 128 GB inbuilt
                  ...
1015     8 GB RAM, 128 GB inbuilt
1016     6 GB RAM, 128 GB inbuilt
1017     8 GB RAM, 256 GB inbuilt
1018     6 GB RAM, 128 GB inbuilt
1019     8 GB RAM, 128 GB inbuilt
Name: ram, Length: 982, dtype: object

In [392]:
df['ram'].str.split()

0       [12, GB, RAM,, 256, GB, inbuilt]
1        [6, GB, RAM,, 128, GB, inbuilt]
2         [4, GB, RAM,, 64, GB, inbuilt]
3        [6, GB, RAM,, 128, GB, inbuilt]
4        [6, GB, RAM,, 128, GB, inbuilt]
                      ...
1015     [8, GB, RAM,, 128, GB, inbuilt]
1016     [6, GB, RAM,, 128, GB, inbuilt]
1017     [8, GB, RAM,, 256, GB, inbuilt]
1018     [6, GB, RAM,, 128, GB, inbuilt]
1019     [8, GB, RAM,, 128, GB, inbuilt]
Name: ram, Length: 982, dtype: object

In [402]:
ram_capacity = df['ram'].str.split().str.get(0).astype(np.int32)
ram_capacity

0       12
1        6
2        4
3        6
4        6
        ..
1015     8
1016     6
1017     8
1018     6
1019     8
Name: ram, Length: 982, dtype: int32

In [408]:
# ram ko insert karo
df.insert(15,'ram_capacity',ram_capacity)

In [409]:
df.head()

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,processor_brand,num_cores,processor_speed,ram,ram_capacity,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,snapdragon,Octa Core,3.2,"12 GB RAM, 256 GB inbuilt",12,5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,snapdragon,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",6,5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",...,exynos,Octa Core,2.4,"4 GB RAM, 64 GB inbuilt",4,5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,snapdragon,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",6,5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",...,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6,5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [410]:
internal_memory = df['ram'].str.split().str.get(3).astype(np.float32)
internal_memory

0       256.0
1       128.0
2        64.0
3       128.0
4       128.0
        ...
1015    128.0
1016    128.0
1017    256.0
1018    128.0
1019    128.0
Name: ram, Length: 982, dtype: float32

In [411]:
df.insert(16,'internal_memory',internal_memory)

In [412]:
df.head()

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,Octa Core,3.2,"12 GB RAM, 256 GB inbuilt",12,256.0,5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",6,128.0,5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",...,Octa Core,2.4,"4 GB RAM, 64 GB inbuilt",4,64.0,5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",6,128.0,5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",...,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",6,128.0,5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [413]:
df[df['ram_capacity'] == 1]

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
399,401,itel,itel P36,6490,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Spreadtrum SC7731E, Quad Core, 1.3 GHz Processor",...,Quad Core,1.3,"1 GB RAM, 16 GB inbuilt",1,16.0,5000 mAh Battery,"6.5 inches, 1600 x 720 px Display with Water D...",8 MP + 0.3 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v9.0 (Pie)
477,479,vivo,Vivo Y25,7499,NaN,"Dual Sim, 3G, 4G, Wi-Fi",False,False,False,"Helio MT6580, Quad Core, 1.3 GHz Processor",...,Quad Core,1.3,"1 GB RAM, 16 GB inbuilt",1,16.0,1900 mAh Battery,"4.5 inches, 480 x 854 px Display",5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v5.1 (Lollipop)
735,737,tecno,Tecno Pop 5 Go,6999,NaN,"Dual Sim, 3G, Wi-Fi",False,False,False,"Spreadtrum SC7731, Quad Core, 1.3 GHz Processor",...,Quad Core,1.3,"1 GB RAM, 16 GB inbuilt",1,16.0,4000 mAh Battery,"6.1 inches, 720 x 1520 px Display with Water D...",5 MP + 0.3 MP Dual Rear & 5 MP Front Camera,Memory Card Supported,Android v11
744,746,itel,itel S16,5990,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Unisoc SC7731E, Quad Core, 1.3 GHz Processor",...,Quad Core,1.3,"1 GB RAM, 16 GB inbuilt",1,16.0,4000 mAh Battery,"6.5 inches, 1600 x 720 px Display with Water D...",8 MP + 2 MP + 0.3 MP Triple Rear & 8 MP Front ...,"Memory Card Supported, upto 32 GB",Android v10
794,796,itel,itel A56,5490,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Quad Core, 1.3 GHz Processor",...,Quad Core,1.3,"1 GB RAM, 16 GB inbuilt",1,16.0,4000 mAh Battery,"6 inches, 720 x 1600 px Display",8 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Android v9.0 (Pie)
856,858,samsung,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"(28 nm), Quad Core, 1.5 GHz Processor",...,Quad Core,1.5,"1 GB RAM, 16 GB inbuilt",1,16.0,3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
907,909,itel,Itel A23 Pro,3999,NaN,"Dual Sim, 3G, 4G, Wi-Fi",False,False,False,"Spreadtrum SC9832E , Quad Core, 1.4 GHz Proce...",...,Quad Core,1.4,"1 GB RAM, 8 GB inbuilt",1,8.0,2400 mAh Battery,"5 inches, 854 x 480 px Display",5 MP Rear & 2 MP Front Camera,Memory Card Not Supported,Android v10

In [ ]:
df[df['ram_capacity'] > 16]

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
271,273,nokia,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Snapdragon 205 , Dual Core, 1.1 GHz Processor",...,Dual Core,1.10,"512 MB RAM, 4 GB inbuilt",512,4.0,1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
280,282,asus,Asus ROG Phone 6 Pro 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"18 GB RAM, 512 GB inbuilt",18,512.0,6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Android v12
410,412,asus,Asus ROG Phone 7,75990,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"18 GB RAM, 256 GB inbuilt",18,256.0,6000 mAh Battery with 120W Fast Charging,"6.8 inches, 1080 x 2448 px, 165 Hz Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v13
439,441,apple,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",...,Hexa Core,3.22,64 GB inbuilt,64,NaN,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
483,485,huawei,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster",False,True,True,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,512 GB inbuilt,512,NaN,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
486,488,nokia,Nokia 8000 4G,6899,NaN,"Dual Sim, 3G, 4G, Wi-Fi",False,False,False,"Snapdragon 210, Quad Core, 1.1 GHz Processor",...,Quad Core,1.10,"512 MB RAM, 4 GB inbuilt",512,4.0,1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
627,629,nokia,Nokia 225 4G,3589,NaN,"Dual Sim, 3G, 4G, VoLTE",False,False,False,Unisoc T117,...,NaN,NaN,"64 MB RAM, 128 MB inbuilt",64,128.0,1150 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",RTOS (Series 30+)
762,764,apple,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",...,Hexa Core,3.22,64 GB inbuilt,64,NaN,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16

In [417]:
# 18 wala tik ha tho
df[(df['ram_capacity'] > 16) & (df['ram_capacity'] != 18)]

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
271,273,nokia,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Snapdragon 205 , Dual Core, 1.1 GHz Processor",...,Dual Core,1.10,"512 MB RAM, 4 GB inbuilt",512,4.0,1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
439,441,apple,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",...,Hexa Core,3.22,64 GB inbuilt,64,NaN,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
483,485,huawei,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster",False,True,True,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,512 GB inbuilt,512,NaN,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
486,488,nokia,Nokia 8000 4G,6899,NaN,"Dual Sim, 3G, 4G, Wi-Fi",False,False,False,"Snapdragon 210, Quad Core, 1.1 GHz Processor",...,Quad Core,1.10,"512 MB RAM, 4 GB inbuilt",512,4.0,1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
627,629,nokia,Nokia 225 4G,3589,NaN,"Dual Sim, 3G, 4G, VoLTE",False,False,False,Unisoc T117,...,NaN,NaN,"64 MB RAM, 128 MB inbuilt",64,128.0,1150 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",RTOS (Series 30+)
762,764,apple,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",...,Hexa Core,3.22,64 GB inbuilt,64,NaN,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16

In [ ]:
# before
df.loc[[439,762],['ram_capacity','internal_memory']]

     ram_capacity  internal_memory
439            64              NaN
762            64              NaN

In [ ]:
# assign the matrix
df.loc[[439,762],['ram_capacity','internal_memory']] = [[4,64],[4,64]]

In [ ]:
# after
df.loc[[439,762],['ram_capacity','internal_memory']]

     ram_capacity  internal_memory
439             4             64.0
762             4             64.0

In [423]:
df[df['ram_capacity'] >= 16]

,index,brand_names,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
17,19,oppo,OPPO Reno 9 Pro Plus,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"16 GB RAM, 256 GB inbuilt",16,256.0,4700 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Memory Card Not Supported,Android v13
118,120,tesla,Tesla Pi Phone,69999,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,Octa Core Processor,...,Octa Core,NaN,"16 GB RAM, 512 GB inbuilt",16,512.0,5000 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,Android v13
141,143,oppo,OPPO Reno 9 Pro 5G,39999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Dimensity 8100 Max, Octa Core, 2.85 GHz Processor",...,Octa Core,2.85,"16 GB RAM, 256 GB inbuilt",16,256.0,4500 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v13
271,273,nokia,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",False,False,False,"Snapdragon 205 , Dual Core, 1.1 GHz Processor",...,Dual Core,1.10,"512 MB RAM, 4 GB inbuilt",512,4.0,1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
280,282,asus,Asus ROG Phone 6 Pro 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"18 GB RAM, 512 GB inbuilt",18,512.0,6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Android v12
308,310,oneplus,OnePlus 10T (16GB RAM + 256GB),55999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"16 GB RAM, 256 GB inbuilt",16,256.0,4800 mAh Battery with 150W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
320,322,iqoo,iQOO 11 (16GB RAM + 256GB),64999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"16 GB RAM, 256 GB inbuilt",16,256.0,5000 mAh Battery with 120W Fast Charging,"6.78 inches, 1440 x 3200 px, 144 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
410,412,asus,Asus ROG Phone 7,75990,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"18 GB RAM, 256 GB inbuilt",18,256.0,6000 mAh Battery with 120W Fast Charging,"6.8 inches, 1080 x 2448 px, 165 Hz Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v13
445,447,asus,Asus ROG Phone 6 Batman Edition,72999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"16 GB RAM, 256 GB inbuilt",16,256.0,6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Android v12
463,465,oppo,OPPO Reno 10 Pro,42990,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Dimensity 9000, Octa Core, 3.05 GHz Processor",...,Octa Core,3.05,"16 GB RAM, 256 GB inbuilt",16,256.0,5000 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2412 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Android v13
483,485,huawei,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster",False,True,True,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,512 GB inbuilt,512,NaN,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
486,488,nokia,Nokia 8000 4G,6899,NaN,"Dual Sim, 3G, 4G, Wi-Fi",False,False,False,"Snapdragon 210, Quad Core, 1.1 GHz Processor",...,Quad Core,1.10,"512 MB RAM, 4 GB inbuilt",512,4.0,1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
627,629,nokia,Nokia 225 4G,3589,NaN,"Dual Sim, 3G, 4G, VoLTE",False,False,False,Unisoc T117,...,NaN,NaN,"64 MB RAM, 128 MB inbuilt",64,128.0,1150 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",RTOS (Series 30+)
721,723,asus,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"16 GB RAM, 512 GB inbuilt",16,512.0,6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,NaN
849,851,lenovo,Lenovo Legion Pro 2,59999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 888, Octa Core, 2.84 GHz Processor",...,Octa Core,2.84,"16 GB RAM, 512 GB inbuilt",16,512.0,5000 mAh Battery with 120W Fast Charging,"6.5 inches, 1080 x 2400 px, 144 Hz Display",64 MP + 16 MP Dual Rear & 20 MP Front Camera,Memory Card Not Supported,Android v10