In [66]:
# problem : sir itna sara graph ha samaj hi nahi ata konsa kam use kara.
# solution : aap aor pratice karo pado . 
# matlab 10 dataset par pratice karna ka baad apko samaj ma ana laga ga 
# konsa data par konsa graph use karna ha .

In [67]:
# today we learn about the plotly graph object

# Session Objectives
- introduction to plotly
- scatter plot
- line chart
- Bubble plot
- Bar plot
- Box plot
- Histogram
- Distplots
- heatmaps

Figure Data Structure
At the heart of Plotly is the Figure object, which represents a complete visualization.

A Figure consists of three main parts:

- data: A list of "traces" (graphical objects like scatter plots, bar charts, etc.).

- layout: Configuration of the figure’s appearance (titles, axes, colors, annotations).

- frames: For animations, sequences of frames defining changes over time.

Figures are internally represented as nested dictionaries or JSON-like structures, which are passed to Plotly.js (the underlying JavaScript engine) for rendering

In [68]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objs as go

In [69]:
match = pd.read_csv(r"C:\Users\sumit\My_code_files\Data Science codes\week 7 - advanced pandas\pandas joins\matches.csv")
delivery = pd.read_csv(r"C:\Users\sumit\My_code_files\Data Science codes\week 7 - advanced pandas\pandas joins\deliveries.csv")

ipl = delivery.merge(match , left_on='match_id',right_on='id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

# Scatter plot

In [70]:
# Problem : we are going to draw a scatter plot between 
# Batsman Avg( x axis) and Batsman Strike rate(Y axis )
# of top 50 batsman in ipl(all time )

In [71]:

top50 = ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(50).index.tolist()
new_ipl = ipl[ipl['batsman'].isin(top50)]

new_ipl

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150431,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,2,SR Watson,KL Rahul,BCJ Cutting,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150435,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,6,SR Watson,Sachin Baby,BCJ Cutting,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150436,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,1,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150437,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,2,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150438,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,3,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [72]:
# Calculating SR
# SR = (number of runs scored )/(number of balls played) * 100

runs = new_ipl.groupby('batsman')['batsman_runs'].sum()
balls = new_ipl.groupby('batsman')['batsman_runs'].count()

strike_rate = (runs/balls)*100
strike_rate = strike_rate.reset_index()
strike_rate
# ya col ka name batsman runs nahi strike rate hona chya tha

             batsman  batsman_runs
0     AB de Villiers    145.129059
1       AC Gilchrist    133.054662
2           AJ Finch    126.299213
3          AM Rahane    117.486549
4          AT Rayudu    123.014257
5        BB McCullum    126.318203
6           BJ Hodge    121.422376
7           CH Gayle    144.194313
8          DA Miller    137.709251
9          DA Warner    138.318401
10          DJ Bravo    122.286822
11         DJ Hussey    120.072661
12  DPMD Jayawardene    118.791064
13          DR Smith    132.279534
14      F du Plessis    124.161074
15         G Gambhir    120.361200
16        GJ Maxwell    157.564103
17         JH Kallis    105.936272
18         JP Duminy    121.970624
19        KA Pollard    140.621266
20     KC Sangakkara    118.469101
21        KD Karthik    123.008475
22           KK Nair    124.650161
23           M Vijay    120.028681
24        MEK Hussey    119.963592
25         MK Pandey    116.938453
26         MK Tiwary    114.127424
27          MS Dhoni    132.835821
28           NV Ojha    114.528024
29          PA Patel    112.718447
30          R Dravid    113.347237
31         RA Jadeja    118.792867
32         RG Sharma    128.497251
33        RV Uthappa    127.635135
34       S Badrinath    115.742972
35          S Dhawan    118.502496
36        SC Ganguly    101.734540
37          SE Marsh    130.109775
38          SK Raina    134.995548
39         SPD Smith    128.507127
40      SR Tendulkar    114.187867
41         SR Watson    134.838379
42         SS Tiwary    114.851485
43         SV Samson    122.403433
44        TM Dilshan    110.124164
45           V Kohli    126.588437
46          V Sehwag    148.827059
47           WP Saha    127.727646
48         YK Pathan    140.751445
49      Yuvraj Singh    126.390244

In [73]:
strike_rate.rename( columns= {'batsman_runs': 'strike_rate'},inplace=True)

In [74]:
strike_rate

             batsman  strike_rate
0     AB de Villiers   145.129059
1       AC Gilchrist   133.054662
2           AJ Finch   126.299213
3          AM Rahane   117.486549
4          AT Rayudu   123.014257
5        BB McCullum   126.318203
6           BJ Hodge   121.422376
7           CH Gayle   144.194313
8          DA Miller   137.709251
9          DA Warner   138.318401
10          DJ Bravo   122.286822
11         DJ Hussey   120.072661
12  DPMD Jayawardene   118.791064
13          DR Smith   132.279534
14      F du Plessis   124.161074
15         G Gambhir   120.361200
16        GJ Maxwell   157.564103
17         JH Kallis   105.936272
18         JP Duminy   121.970624
19        KA Pollard   140.621266
20     KC Sangakkara   118.469101
21        KD Karthik   123.008475
22           KK Nair   124.650161
23           M Vijay   120.028681
24        MEK Hussey   119.963592
25         MK Pandey   116.938453
26         MK Tiwary   114.127424
27          MS Dhoni   132.835821
28           NV Ojha   114.528024
29          PA Patel   112.718447
30          R Dravid   113.347237
31         RA Jadeja   118.792867
32         RG Sharma   128.497251
33        RV Uthappa   127.635135
34       S Badrinath   115.742972
35          S Dhawan   118.502496
36        SC Ganguly   101.734540
37          SE Marsh   130.109775
38          SK Raina   134.995548
39         SPD Smith   128.507127
40      SR Tendulkar   114.187867
41         SR Watson   134.838379
42         SS Tiwary   114.851485
43         SV Samson   122.403433
44        TM Dilshan   110.124164
45           V Kohli   126.588437
46          V Sehwag   148.827059
47           WP Saha   127.727646
48         YK Pathan   140.751445
49      Yuvraj Singh   126.390244

In [75]:
# Calculating Avg
# Avg = (Total numbers of runs )/ (number of outs)

# Calculating number of outs for top 50 batsman

out = ipl[ipl['player_dismissed'].isin(top50)]

nouts = out['player_dismissed'].value_counts()

avg = runs/nouts

avg = avg.reset_index()
avg

               index          0
0     AB de Villiers  38.307692
1       AC Gilchrist  27.223684
2           AJ Finch  27.186441
3          AM Rahane  33.593407
4          AT Rayudu  27.146067
5        BB McCullum  28.112245
6           BJ Hodge  33.333333
7           CH Gayle  41.022472
8          DA Miller  34.733333
9          DA Warner  40.140000
10          DJ Bravo  22.945455
11         DJ Hussey  26.979592
12  DPMD Jayawardene  28.250000
13          DR Smith  28.392857
14      F du Plessis  30.116279
15         G Gambhir  31.541985
16        GJ Maxwell  25.081633
17         JH Kallis  28.552941
18         JP Duminy  39.860000
19        KA Pollard  28.707317
20     KC Sangakkara  25.953846
21        KD Karthik  24.811966
22           KK Nair  25.173913
23           M Vijay  26.431579
24        MEK Hussey  38.764706
25         MK Pandey  28.500000
26         MK Tiwary  29.428571
27          MS Dhoni  37.872340
28           NV Ojha  20.986486
29          PA Patel  21.700935
30          R Dravid  28.233766
31         RA Jadeja  24.055556
32         RG Sharma  32.612403
33        RV Uthappa  29.515625
34       S Badrinath  30.659574
35          S Dhawan  32.669725
36        SC Ganguly  25.452830
37          SE Marsh  39.507937
38          SK Raina  33.940299
39         SPD Smith  37.239130
40      SR Tendulkar  33.826087
41         SR Watson  30.917647
42         SS Tiwary  28.355556
43         SV Samson  25.464286
44        TM Dilshan  26.813953
45           V Kohli  37.483051
46          V Sehwag  27.555556
47           WP Saha  25.524590
48         YK Pathan  29.816327
49      Yuvraj Singh  25.653465

In [76]:
avg.rename(columns={'index':'batsman',0: 'avg'},inplace = True)

In [77]:
avg

             batsman        avg
0     AB de Villiers  38.307692
1       AC Gilchrist  27.223684
2           AJ Finch  27.186441
3          AM Rahane  33.593407
4          AT Rayudu  27.146067
5        BB McCullum  28.112245
6           BJ Hodge  33.333333
7           CH Gayle  41.022472
8          DA Miller  34.733333
9          DA Warner  40.140000
10          DJ Bravo  22.945455
11         DJ Hussey  26.979592
12  DPMD Jayawardene  28.250000
13          DR Smith  28.392857
14      F du Plessis  30.116279
15         G Gambhir  31.541985
16        GJ Maxwell  25.081633
17         JH Kallis  28.552941
18         JP Duminy  39.860000
19        KA Pollard  28.707317
20     KC Sangakkara  25.953846
21        KD Karthik  24.811966
22           KK Nair  25.173913
23           M Vijay  26.431579
24        MEK Hussey  38.764706
25         MK Pandey  28.500000
26         MK Tiwary  29.428571
27          MS Dhoni  37.872340
28           NV Ojha  20.986486
29          PA Patel  21.700935
30          R Dravid  28.233766
31         RA Jadeja  24.055556
32         RG Sharma  32.612403
33        RV Uthappa  29.515625
34       S Badrinath  30.659574
35          S Dhawan  32.669725
36        SC Ganguly  25.452830
37          SE Marsh  39.507937
38          SK Raina  33.940299
39         SPD Smith  37.239130
40      SR Tendulkar  33.826087
41         SR Watson  30.917647
42         SS Tiwary  28.355556
43         SV Samson  25.464286
44        TM Dilshan  26.813953
45           V Kohli  37.483051
46          V Sehwag  27.555556
47           WP Saha  25.524590
48         YK Pathan  29.816327
49      Yuvraj Singh  25.653465

In [78]:
# merge the boths 

batsman_df = avg.merge(strike_rate,on='batsman')
batsman_df

             batsman        avg  strike_rate
0     AB de Villiers  38.307692   145.129059
1       AC Gilchrist  27.223684   133.054662
2           AJ Finch  27.186441   126.299213
3          AM Rahane  33.593407   117.486549
4          AT Rayudu  27.146067   123.014257
5        BB McCullum  28.112245   126.318203
6           BJ Hodge  33.333333   121.422376
7           CH Gayle  41.022472   144.194313
8          DA Miller  34.733333   137.709251
9          DA Warner  40.140000   138.318401
10          DJ Bravo  22.945455   122.286822
11         DJ Hussey  26.979592   120.072661
12  DPMD Jayawardene  28.250000   118.791064
13          DR Smith  28.392857   132.279534
14      F du Plessis  30.116279   124.161074
15         G Gambhir  31.541985   120.361200
16        GJ Maxwell  25.081633   157.564103
17         JH Kallis  28.552941   105.936272
18         JP Duminy  39.860000   121.970624
19        KA Pollard  28.707317   140.621266
20     KC Sangakkara  25.953846   118.469101
21        KD Karthik  24.811966   123.008475
22           KK Nair  25.173913   124.650161
23           M Vijay  26.431579   120.028681
24        MEK Hussey  38.764706   119.963592
25         MK Pandey  28.500000   116.938453
26         MK Tiwary  29.428571   114.127424
27          MS Dhoni  37.872340   132.835821
28           NV Ojha  20.986486   114.528024
29          PA Patel  21.700935   112.718447
30          R Dravid  28.233766   113.347237
31         RA Jadeja  24.055556   118.792867
32         RG Sharma  32.612403   128.497251
33        RV Uthappa  29.515625   127.635135
34       S Badrinath  30.659574   115.742972
35          S Dhawan  32.669725   118.502496
36        SC Ganguly  25.452830   101.734540
37          SE Marsh  39.507937   130.109775
38          SK Raina  33.940299   134.995548
39         SPD Smith  37.239130   128.507127
40      SR Tendulkar  33.826087   114.187867
41         SR Watson  30.917647   134.838379
42         SS Tiwary  28.355556   114.851485
43         SV Samson  25.464286   122.403433
44        TM Dilshan  26.813953   110.124164
45           V Kohli  37.483051   126.588437
46          V Sehwag  27.555556   148.827059
47           WP Saha  25.524590   127.727646
48         YK Pathan  29.816327   140.751445
49      Yuvraj Singh  25.653465   126.390244

In [79]:
import plotly.express as px
px.scatter(data_frame=batsman_df, x = 'avg',y = 'strike_rate',hover_name='batsman')

## plot scatter here

In [80]:
# figure data strcture is  
# graph object library ha  usma figure class ka call kara usa show kiya 
fig = go.Figure()
fig.show()

In [81]:
# har ek figure data stcture ka pass 3 things
# data = konsa graphical object ha scatter plot,line plot,bar chart
# layout = vo figure (graphical object ) deka ga kasa apprearance configuration 
# like  title , lables,( x and y ), colour ,text ,size  etc 


# fig = go.Figure(data , layout)
# fig.show()

In [82]:
# Now data is a list of traces .  
# trace ko bolta ha hamra ek particular graphs
# 1 trace matlab ek graph plot hoga ( line scatter bar  )  
# 2 trace  matlab matlab two graphs show on screen ( two line graphs ,two bar chart or any combinaiton of  two)
# same in general ... 
# fir trace ma graphical object ma scatter function  ( x axis ,y axis ,mode)
# or layout ma title,xlable ,ylabel

In [83]:

#                    x coloumn(variable)   y coloumn (variable )       # mode konsa ha
trace1 = go.Scatter(x= batsman_df['avg'], y = batsman_df['strike_rate'],mode='markers')
data = [trace1]
layout = go.Layout(
    title= 'Batsman Avg vs Strike rate ',
    xaxis={'title': 'avg'},         # xlabel (x axis ) name 
    yaxis={'title': 'strike rate'}   # y label(y axis ) name 
    )
fig = go.Figure(data = data ,layout= layout)
fig.show()

In [84]:
# en dots ko hi hum market bol raha

In [85]:

#                    x coloumn(variable)   y coloumn (variable )       # mode konsa ha
trace1 = go.Scatter(x= batsman_df['avg'], y = batsman_df['strike_rate'],mode='markers')
data = [trace1]
layout = go.Layout(
    title= 'Batsman Avg vs Strike rate ',
    xaxis={'title': 'avg'},         # xlabel (x axis ) name 
    yaxis={'title': 'strike rate'}   # y label(y axis ) name 
    )
fig = go.Figure(data = data ,layout= layout)
#pyo.plot(fig)
# ya apka brwoser ma open ho jaya ga 
# default name temp-plot.html
#pyo.plot(fig,filename='myfile.html')

In [86]:
# deko huma batsman ka bara ma pata nahi chal
# ki ya kons batsman ka avg and strike rate ha 
# pa raha so we add the batsman name

In [87]:

#                    x coloumn(variable)   y coloumn (variable )       # mode konsa ha # name of the batsman show 
trace1 = go.Scatter(x= batsman_df['avg'], y = batsman_df['strike_rate'],
                    mode='markers', text=batsman_df['batsman'] )
data = [trace1]
layout = go.Layout(
    title= 'Batsman Avg vs Strike rate ',
    xaxis={'title': 'avg'},         # xlabel (x axis ) name 
    yaxis={'title': 'strike rate'}   # y label(y axis ) name 
    )
fig = go.Figure(data = data ,layout= layout)
fig.show()

### color

In [88]:

#       
trace1 = go.Scatter(x= batsman_df['avg'], y = batsman_df['strike_rate'],
                    mode='markers', text=batsman_df['batsman'],
                    marker={'color': "#00a558"} # colour of the plots
                    )
data = [trace1]
layout = go.Layout(
    title= 'Batsman Avg vs Strike rate ',
    xaxis={'title': 'avg'},         # xlabel (x axis ) name 
    yaxis={'title': 'strike rate'}   # y label(y axis ) name 
    )
fig = go.Figure(data = data ,layout= layout)
fig.show()

### size

In [89]:

#       
trace1 = go.Scatter(x= batsman_df['avg'], y = batsman_df['strike_rate'],
                    mode='markers', text=batsman_df['batsman'],
                    marker={'color': "#00a558", 'size': 14} # default size 10 hota ha 
                    )
data = [trace1]
layout = go.Layout(
    title= 'Batsman Avg vs Strike rate ',
    xaxis={'title': 'avg'},         
    yaxis={'title': 'strike rate'}  
    )
fig = go.Figure(data = data ,layout= layout)
fig.show()

# Line Chart 
It is a just extension of scatter plot. used to show time-series data( day , month,year wise )

In [90]:
# year by year batsman performance 
single = ipl[ipl['batsman'] == 'V Kohli']
performance = single.groupby('season')['batsman_runs'].sum().reset_index()
performance

   season  batsman_runs
0    2008           165
1    2009           246
2    2010           307
3    2011           557
4    2012           364
5    2013           639
6    2014           359
7    2015           505
8    2016           973
9    2017           308

In [91]:
# ya batsman run ha hum yaha total run ko rename kar sakta ha 
performance.rename(columns={'batsman_runs': 'total_runs'}, inplace=True)

In [92]:
performance

   season  total_runs
0    2008         165
1    2009         246
2    2010         307
3    2011         557
4    2012         364
5    2013         639
6    2014         359
7    2015         505
8    2016         973
9    2017         308

In [93]:
## plot the line chart 
trace1 = go.Scatter( x = performance['season'],y=performance['total_runs'],
                    mode = 'lines')


data = [trace1]
layout = go.Layout(
    title = 'Year by Year performance',
    xaxis = {'title': 'year'},
    yaxis = {'title': 'Total runs'},
    )
fig = go.Figure(data= data,layout=layout)
fig.show()

In [94]:
# now do line + marker(dot)
## plot the line chart 
trace1 = go.Scatter( x = performance['season'],y=performance['total_runs'],
                    mode = 'lines + markers',
                    marker={'color': '#00a65a'})


data = [trace1]
layout = go.Layout(
    title = 'Year by Year performance',
    xaxis = {'title': 'year'},
    yaxis = {'title': 'Total runs'},
    )
fig = go.Figure(data= data,layout=layout)
fig.show()

### multiple line chart 
used for comparative studies .

In [95]:
#year by year batsman performance 
single = ipl[ipl['batsman'] == 'V Kohli']
performance_1 = single.groupby('season')['batsman_runs'].sum().reset_index()
performance_1

single = ipl[ipl['batsman'] == 'MS Dhoni']
performance_2 = single.groupby('season')['batsman_runs'].sum().reset_index()
performance_2

   season  batsman_runs
0    2008           414
1    2009           332
2    2010           287
3    2011           392
4    2012           357
5    2013           461
6    2014           371
7    2015           372
8    2016           284
9    2017           290

In [96]:
## plot the line chart 
trace0= go.Scatter( x = performance_1['season'],y=performance_1['batsman_runs'],
                    mode = 'lines',)
trace1= go.Scatter( x = performance_2['season'],y=performance_2['batsman_runs'],
                    mode = 'lines')

data = [trace0,trace1]
layout = go.Layout(
    title = 'Year by Year performance',
    xaxis = {'title': 'year'},
    yaxis = {'title': 'Total runs'},
    )
fig = go.Figure(data= data,layout=layout)
fig.show()

#### name

In [97]:
## plot the line chart 
trace0= go.Scatter( x = performance_1['season'],y=performance_1['batsman_runs'],
                    mode = 'lines',name = 'virat kohli')
trace1= go.Scatter( x = performance_2['season'],y=performance_2['batsman_runs'],
                    mode = 'lines', name = 'MS Dhoni')

data = [trace0,trace1]
layout = go.Layout(
    title = 'Year by Year performance',
    xaxis = {'title': 'year'},
    yaxis = {'title': 'Total runs'},
    )
fig = go.Figure(data= data,layout=layout)
fig.show()

In [98]:
# power of it . 
def batsman_comparsion(*name):
    data = []
    for i in name:
        single = ipl[ipl['batsman']== i]
        performance = single.groupby('season')['batsman_runs'].sum().reset_index()
        
        trace= go.Scatter( x = performance['season'],y=performance['batsman_runs'],
                    mode = 'lines+markers', name = i)
        
        data.append(trace)
    
    layout = go.Layout(
        title= 'Batsman Record Comparion',
        xaxis={'title': 'Season'},
        yaxis={'title': 'Runs'}
    )
    
    fig = go.Figure(data= data  , layout= layout)
    fig.show()

batsman_comparsion('AB de Villiers','V Kohli','CH Gayle')

In [99]:
batsman_df['batsman'].values

array(['AB de Villiers', 'AC Gilchrist', 'AJ Finch', 'AM Rahane',
       'AT Rayudu', 'BB McCullum', 'BJ Hodge', 'CH Gayle', 'DA Miller',
       'DA Warner', 'DJ Bravo', 'DJ Hussey', 'DPMD Jayawardene',
       'DR Smith', 'F du Plessis', 'G Gambhir', 'GJ Maxwell', 'JH Kallis',
       'JP Duminy', 'KA Pollard', 'KC Sangakkara', 'KD Karthik',
       'KK Nair', 'M Vijay', 'MEK Hussey', 'MK Pandey', 'MK Tiwary',
       'MS Dhoni', 'NV Ojha', 'PA Patel', 'R Dravid', 'RA Jadeja',
       'RG Sharma', 'RV Uthappa', 'S Badrinath', 'S Dhawan', 'SC Ganguly',
       'SE Marsh', 'SK Raina', 'SPD Smith', 'SR Tendulkar', 'SR Watson',
       'SS Tiwary', 'SV Samson', 'TM Dilshan', 'V Kohli', 'V Sehwag',
       'WP Saha', 'YK Pathan', 'Yuvraj Singh'], dtype=object)

In [100]:
import plotly.graph_objects as go

def batsman_comparsion(*name):
    data = []
    for i in name:
        single = ipl[ipl['batsman'] == i]  # Corrected filter here
        performance = single.groupby('season')['batsman_runs'].sum().reset_index()
        
        trace = go.Scatter(
            x=performance['season'],
            y=performance['batsman_runs'],
            mode='lines+markers',  # No spaces around '+'
            name=i
        )
        data.append(trace)
    
    layout = go.Layout(
        title='Batsman Record Comparison',
        xaxis={'title': 'Season'},
        yaxis={'title': 'Runs'}
    )
    
    fig = go.Figure(data=data, layout=layout)
    fig.show()

# Example call
batsman_comparsion('AB de Villiers', 'V Kohli', 'CH Gayle')

# Bar plot 
x axis par hum category rakna ha aor y axis par uska frequency count

There are 3 Types of Bar chart 
- Nested Bar graph
- stacked Bar graph
- overlap Bar graph

In [101]:
top10 = ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10).index.to_list()
top10_df = ipl[ipl['batsman'].isin(top10)]
top10_df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150414,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,3,V Kohli,AB de Villiers,BB Sran,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150415,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,4,V Kohli,AB de Villiers,BB Sran,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150416,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,V Kohli,AB de Villiers,BB Sran,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150420,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,3,AB de Villiers,KL Rahul,Bipul Sharma,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150422,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,5,AB de Villiers,KL Rahul,Bipul Sharma,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [102]:
top10_score = top10_df.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).reset_index()
top10_score

          batsman  batsman_runs
0        SK Raina          4548
1         V Kohli          4423
2       RG Sharma          4207
3       G Gambhir          4132
4       DA Warner          4014
5      RV Uthappa          3778
6        CH Gayle          3651
7        S Dhawan          3561
8        MS Dhoni          3560
9  AB de Villiers          3486

In [103]:
# plot the bar
trace = go.Bar(
    x = top10_score['batsman'],
    y = top10_score['batsman_runs']
)
data = [trace]
layout = go.Layout(
    title='Top 10 batsman runs ',
    xaxis={'title': 'batsman'},
    yaxis={'title': 'batsman_runs'}
)

go.Figure(data ,layout )

In [104]:

# figure is automaticaly show by jupyter notebook

In [105]:
iw = top10_df.groupby(by = ['batsman','inning'])['batsman_runs'].sum().reset_index()
mask1 = iw['inning'] == 1
mask2 = iw['inning'] == 2

one = iw[mask1]
two = iw[mask2]

one.rename(columns = {'batsman_runs': '1st_innings'},inplace=True)
two.rename(columns = {'batsman_runs': '2nd_innings'},inplace=True)

one

C:\Users\sumit\AppData\Local\Temp\ipykernel_16200\1893635227.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sumit\AppData\Local\Temp\ipykernel_16200\1893635227.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

           batsman  inning  1st_innings
0   AB de Villiers       1         2128
3         CH Gayle       1         2003
7        DA Warner       1         2118
10       G Gambhir       1         1699
12        MS Dhoni       1         2232
14       RG Sharma       1         2344
16      RV Uthappa       1         1516
18        S Dhawan       1         2262
20        SK Raina       1         2647
23         V Kohli       1         2391

In [106]:
# merge the 1st and 2nd iningg 
final = one.merge(two , on = 'batsman')[['batsman','1st_innings','2nd_innings']]
final

          batsman  1st_innings  2nd_innings
0  AB de Villiers         2128         1345
1        CH Gayle         2003         1623
2       DA Warner         2118         1896
3       G Gambhir         1699         2433
4        MS Dhoni         2232         1328
5       RG Sharma         2344         1863
6      RV Uthappa         1516         2262
7        S Dhawan         2262         1299
8        SK Raina         2647         1893
9         V Kohli         2391         2027

In [107]:
trace1 = go.Bar(
    x = final['batsman'],
    y = final['1st_innings'],
    name = '1st Innings',
    marker= { 'color' :'#00a55f'}
)

trace2 = go.Bar(
    x = final['batsman'],
    y = final['2nd_innings'],
    name = '2nd Innings',
    marker= { 'color' :"#a50087"}
)

data = [trace1,trace2]

layout = go.Layout(
    title= 'Inning Wise score',
    xaxis= {'title': 'Batsman'},
    yaxis= {'title': 'Runs'},
    barmode='overlay'
)

go.Figure(data,layout)

In [108]:
# now draw the stacked

In [109]:
trace1 = go.Bar(
    x = final['batsman'],
    y = final['1st_innings'],
    name = '1st Innings',
    marker= { 'color' :'#00a55f'}
)

trace2 = go.Bar(
    x = final['batsman'],
    y = final['2nd_innings'],
    name = '2nd Innings',
    marker= { 'color' :"#a50087"}
)

data = [trace1,trace2]

layout = go.Layout(
    title= 'Inning Wise score',
    xaxis= {'title': 'Batsman'},
    yaxis= {'title': 'Runs'},
    barmode='stack'
)

go.Figure(data,layout)

In [110]:
# four types are 
['stack', 'group', 'overlay', 'relative']

['stack', 'group', 'overlay', 'relative']

In [111]:
trace1 = go.Bar(
    x = final['batsman'],
    y = final['1st_innings'],
    name = '1st Innings',
    marker= { 'color' :'#00a55f'}
)

trace2 = go.Bar(
    x = final['batsman'],
    y = final['2nd_innings'],
    name = '2nd Innings',
    marker= { 'color' :"#a50087"}
)

data = [trace1,trace2]

layout = go.Layout(
    title= 'Inning Wise score',
    xaxis= {'title': 'Batsman'},
    yaxis= {'title': 'Runs'},
    barmode='relative'
)

go.Figure(data,layout)

In [112]:
trace1 = go.Bar(
    x = final['batsman'],
    y = final['1st_innings'],
    name = '1st Innings',
    marker= { 'color' :'#00a55f'}
)

trace2 = go.Bar(
    x = final['batsman'],
    y = final['2nd_innings'],
    name = '2nd Innings',
    marker= { 'color' :"#a50087"}
)

data = [trace1,trace2]

layout = go.Layout(
    title= 'Inning Wise score',
    xaxis= {'title': 'Batsman'},
    yaxis= {'title': 'Runs'},
    barmode='group'
)

go.Figure(data,layout)

# Bubble plot
again an extension of scatter plot with additional information 
- we use the 3 numerical coloumns and 4 catergorical coloumn
- 2 coloumns ko tho hum axes par draw kar dega (x and y)
- lakin  3 coloumn ko lakra hum dot ka size (circle ka diameter bana dega )
- 4 variable sa hum colour deka sakta ha

avg and strike rate in x and y axis now . plot scatter plot . example size decide hoga ki batsman na kitna 6's lagaya ha ipl mathces ma

also you can see the 4 dimesnion information by colour ki wo batsman konsi team sa khelta ha .

In [113]:
# now humna avg and strike rate nikal liya tha ab huma isma two coloumns or add karni ha 
# numbers of sixes and teams of the player

In [114]:
batsman_df

             batsman        avg  strike_rate
0     AB de Villiers  38.307692   145.129059
1       AC Gilchrist  27.223684   133.054662
2           AJ Finch  27.186441   126.299213
3          AM Rahane  33.593407   117.486549
4          AT Rayudu  27.146067   123.014257
5        BB McCullum  28.112245   126.318203
6           BJ Hodge  33.333333   121.422376
7           CH Gayle  41.022472   144.194313
8          DA Miller  34.733333   137.709251
9          DA Warner  40.140000   138.318401
10          DJ Bravo  22.945455   122.286822
11         DJ Hussey  26.979592   120.072661
12  DPMD Jayawardene  28.250000   118.791064
13          DR Smith  28.392857   132.279534
14      F du Plessis  30.116279   124.161074
15         G Gambhir  31.541985   120.361200
16        GJ Maxwell  25.081633   157.564103
17         JH Kallis  28.552941   105.936272
18         JP Duminy  39.860000   121.970624
19        KA Pollard  28.707317   140.621266
20     KC Sangakkara  25.953846   118.469101
21        KD Karthik  24.811966   123.008475
22           KK Nair  25.173913   124.650161
23           M Vijay  26.431579   120.028681
24        MEK Hussey  38.764706   119.963592
25         MK Pandey  28.500000   116.938453
26         MK Tiwary  29.428571   114.127424
27          MS Dhoni  37.872340   132.835821
28           NV Ojha  20.986486   114.528024
29          PA Patel  21.700935   112.718447
30          R Dravid  28.233766   113.347237
31         RA Jadeja  24.055556   118.792867
32         RG Sharma  32.612403   128.497251
33        RV Uthappa  29.515625   127.635135
34       S Badrinath  30.659574   115.742972
35          S Dhawan  32.669725   118.502496
36        SC Ganguly  25.452830   101.734540
37          SE Marsh  39.507937   130.109775
38          SK Raina  33.940299   134.995548
39         SPD Smith  37.239130   128.507127
40      SR Tendulkar  33.826087   114.187867
41         SR Watson  30.917647   134.838379
42         SS Tiwary  28.355556   114.851485
43         SV Samson  25.464286   122.403433
44        TM Dilshan  26.813953   110.124164
45           V Kohli  37.483051   126.588437
46          V Sehwag  27.555556   148.827059
47           WP Saha  25.524590   127.727646
48         YK Pathan  29.816327   140.751445
49      Yuvraj Singh  25.653465   126.390244

In [115]:
sixes_score = new_ipl[new_ipl['batsman_runs'] == 6]
num_of_sixes = sixes_score.groupby('batsman')['batsman_runs'].count().reset_index()
num_of_sixes.rename(columns={'batsman_runs': 'six'},inplace=True)

In [116]:
num_of_sixes

             batsman  six
0     AB de Villiers  158
1       AC Gilchrist   92
2           AJ Finch   59
3          AM Rahane   60
4          AT Rayudu   79
5        BB McCullum  124
6           BJ Hodge   43
7           CH Gayle  266
8          DA Miller   78
9          DA Warner  160
10          DJ Bravo   48
11         DJ Hussey   60
12  DPMD Jayawardene   40
13          DR Smith  117
14      F du Plessis   38
15         G Gambhir   58
16        GJ Maxwell   82
17         JH Kallis   44
18         JP Duminy   78
19        KA Pollard  148
20     KC Sangakkara   27
21        KD Karthik   71
22           KK Nair   26
23           M Vijay   89
24        MEK Hussey   52
25         MK Pandey   65
26         MK Tiwary   39
27          MS Dhoni  156
28           NV Ojha   79
29          PA Patel   35
30          R Dravid   28
31         RA Jadeja   57
32         RG Sharma  173
33        RV Uthappa  125
34       S Badrinath   28
35          S Dhawan   71
36        SC Ganguly   42
37          SE Marsh   78
38          SK Raina  174
39         SPD Smith   45
40      SR Tendulkar   29
41         SR Watson  122
42         SS Tiwary   45
43         SV Samson   57
44        TM Dilshan   24
45           V Kohli  160
46          V Sehwag  106
47           WP Saha   57
48         YK Pathan  149
49      Yuvraj Singh  141

In [117]:
batsman_df = batsman_df.merge(num_of_sixes, on='batsman')

In [118]:
batsman_df

             batsman        avg  strike_rate  six
0     AB de Villiers  38.307692   145.129059  158
1       AC Gilchrist  27.223684   133.054662   92
2           AJ Finch  27.186441   126.299213   59
3          AM Rahane  33.593407   117.486549   60
4          AT Rayudu  27.146067   123.014257   79
5        BB McCullum  28.112245   126.318203  124
6           BJ Hodge  33.333333   121.422376   43
7           CH Gayle  41.022472   144.194313  266
8          DA Miller  34.733333   137.709251   78
9          DA Warner  40.140000   138.318401  160
10          DJ Bravo  22.945455   122.286822   48
11         DJ Hussey  26.979592   120.072661   60
12  DPMD Jayawardene  28.250000   118.791064   40
13          DR Smith  28.392857   132.279534  117
14      F du Plessis  30.116279   124.161074   38
15         G Gambhir  31.541985   120.361200   58
16        GJ Maxwell  25.081633   157.564103   82
17         JH Kallis  28.552941   105.936272   44
18         JP Duminy  39.860000   121.970624   78
19        KA Pollard  28.707317   140.621266  148
20     KC Sangakkara  25.953846   118.469101   27
21        KD Karthik  24.811966   123.008475   71
22           KK Nair  25.173913   124.650161   26
23           M Vijay  26.431579   120.028681   89
24        MEK Hussey  38.764706   119.963592   52
25         MK Pandey  28.500000   116.938453   65
26         MK Tiwary  29.428571   114.127424   39
27          MS Dhoni  37.872340   132.835821  156
28           NV Ojha  20.986486   114.528024   79
29          PA Patel  21.700935   112.718447   35
30          R Dravid  28.233766   113.347237   28
31         RA Jadeja  24.055556   118.792867   57
32         RG Sharma  32.612403   128.497251  173
33        RV Uthappa  29.515625   127.635135  125
34       S Badrinath  30.659574   115.742972   28
35          S Dhawan  32.669725   118.502496   71
36        SC Ganguly  25.452830   101.734540   42
37          SE Marsh  39.507937   130.109775   78
38          SK Raina  33.940299   134.995548  174
39         SPD Smith  37.239130   128.507127   45
40      SR Tendulkar  33.826087   114.187867   29
41         SR Watson  30.917647   134.838379  122
42         SS Tiwary  28.355556   114.851485   45
43         SV Samson  25.464286   122.403433   57
44        TM Dilshan  26.813953   110.124164   24
45           V Kohli  37.483051   126.588437  160
46          V Sehwag  27.555556   148.827059  106
47           WP Saha  25.524590   127.727646   57
48         YK Pathan  29.816327   140.751445  149
49      Yuvraj Singh  25.653465   126.390244  141

In [119]:
# simple just eeact the two coloumns you need batsman name and team name and 
# repeat ho rha simple sol = just drop duplicates thorught batsamna 
# then unique 50 batsnam name and its team

In [120]:
teams_df = new_ipl[['batsman','batting_team']].drop_duplicates(subset='batsman')
teams_df

                batsman                 batting_team
0             DA Warner          Sunrisers Hyderabad
5              S Dhawan          Sunrisers Hyderabad
66         Yuvraj Singh          Sunrisers Hyderabad
125            CH Gayle  Royal Challengers Bangalore
200           SR Watson  Royal Challengers Bangalore
248            PA Patel               Mumbai Indians
275           RG Sharma               Mumbai Indians
290           AT Rayudu               Mumbai Indians
332          KA Pollard               Mumbai Indians
373           AM Rahane       Rising Pune Supergiant
393           SPD Smith       Rising Pune Supergiant
469            MS Dhoni       Rising Pune Supergiant
501         BB McCullum                Gujarat Lions
515            SK Raina                Gujarat Lions
545            AJ Finch                Gujarat Lions
559          KD Karthik                Gujarat Lions
617           G Gambhir        Kolkata Knight Riders
784           MK Tiwary       Rising Pune Supergiant
858             WP Saha              Kings XI Punjab
910          GJ Maxwell              Kings XI Punjab
911           DA Miller              Kings XI Punjab
1113            KK Nair             Delhi Daredevils
1118          SV Samson             Delhi Daredevils
1264           DR Smith                Gujarat Lions
1454         RV Uthappa        Kolkata Knight Riders
1458          MK Pandey        Kolkata Knight Riders
1475          YK Pathan        Kolkata Knight Riders
1688     AB de Villiers  Royal Challengers Bangalore
2035       F du Plessis       Rising Pune Supergiant
2213            NV Ojha          Sunrisers Hyderabad
2590            V Kohli  Royal Challengers Bangalore
4757          RA Jadeja                Gujarat Lions
5056           SE Marsh              Kings XI Punjab
12328         SS Tiwary               Mumbai Indians
13862        SC Ganguly        Kolkata Knight Riders
13944         DJ Hussey        Kolkata Knight Riders
13986          R Dravid  Royal Challengers Bangalore
14001         JH Kallis  Royal Challengers Bangalore
14105        MEK Hussey          Chennai Super Kings
14184       S Badrinath          Chennai Super Kings
14249     KC Sangakkara              Kings XI Punjab
14463          V Sehwag             Delhi Daredevils
14800      AC Gilchrist              Deccan Chargers
15079  DPMD Jayawardene              Kings XI Punjab
15674          DJ Bravo               Mumbai Indians
18283          BJ Hodge        Kolkata Knight Riders
21015      SR Tendulkar               Mumbai Indians
21704        TM Dilshan             Delhi Daredevils
27423         JP Duminy               Mumbai Indians
32724           M Vijay          Chennai Super Kings

In [121]:
# now do merge them based on batsman name

In [122]:
batsman_df = batsman_df.merge(teams_df,on='batsman')

In [123]:
batsman_df

             batsman        avg  strike_rate  six                 batting_team
0     AB de Villiers  38.307692   145.129059  158  Royal Challengers Bangalore
1       AC Gilchrist  27.223684   133.054662   92              Deccan Chargers
2           AJ Finch  27.186441   126.299213   59                Gujarat Lions
3          AM Rahane  33.593407   117.486549   60       Rising Pune Supergiant
4          AT Rayudu  27.146067   123.014257   79               Mumbai Indians
5        BB McCullum  28.112245   126.318203  124                Gujarat Lions
6           BJ Hodge  33.333333   121.422376   43        Kolkata Knight Riders
7           CH Gayle  41.022472   144.194313  266  Royal Challengers Bangalore
8          DA Miller  34.733333   137.709251   78              Kings XI Punjab
9          DA Warner  40.140000   138.318401  160          Sunrisers Hyderabad
10          DJ Bravo  22.945455   122.286822   48               Mumbai Indians
11         DJ Hussey  26.979592   120.072661   60        Kolkata Knight Riders
12  DPMD Jayawardene  28.250000   118.791064   40              Kings XI Punjab
13          DR Smith  28.392857   132.279534  117                Gujarat Lions
14      F du Plessis  30.116279   124.161074   38       Rising Pune Supergiant
15         G Gambhir  31.541985   120.361200   58        Kolkata Knight Riders
16        GJ Maxwell  25.081633   157.564103   82              Kings XI Punjab
17         JH Kallis  28.552941   105.936272   44  Royal Challengers Bangalore
18         JP Duminy  39.860000   121.970624   78               Mumbai Indians
19        KA Pollard  28.707317   140.621266  148               Mumbai Indians
20     KC Sangakkara  25.953846   118.469101   27              Kings XI Punjab
21        KD Karthik  24.811966   123.008475   71                Gujarat Lions
22           KK Nair  25.173913   124.650161   26             Delhi Daredevils
23           M Vijay  26.431579   120.028681   89          Chennai Super Kings
24        MEK Hussey  38.764706   119.963592   52          Chennai Super Kings
25         MK Pandey  28.500000   116.938453   65        Kolkata Knight Riders
26         MK Tiwary  29.428571   114.127424   39       Rising Pune Supergiant
27          MS Dhoni  37.872340   132.835821  156       Rising Pune Supergiant
28           NV Ojha  20.986486   114.528024   79          Sunrisers Hyderabad
29          PA Patel  21.700935   112.718447   35               Mumbai Indians
30          R Dravid  28.233766   113.347237   28  Royal Challengers Bangalore
31         RA Jadeja  24.055556   118.792867   57                Gujarat Lions
32         RG Sharma  32.612403   128.497251  173               Mumbai Indians
33        RV Uthappa  29.515625   127.635135  125        Kolkata Knight Riders
34       S Badrinath  30.659574   115.742972   28          Chennai Super Kings
35          S Dhawan  32.669725   118.502496   71          Sunrisers Hyderabad
36        SC Ganguly  25.452830   101.734540   42        Kolkata Knight Riders
37          SE Marsh  39.507937   130.109775   78              Kings XI Punjab
38          SK Raina  33.940299   134.995548  174                Gujarat Lions
39         SPD Smith  37.239130   128.507127   45       Rising Pune Supergiant
40      SR Tendulkar  33.826087   114.187867   29               Mumbai Indians
41         SR Watson  30.917647   134.838379  122  Royal Challengers Bangalore
42         SS Tiwary  28.355556   114.851485   45               Mumbai Indians
43         SV Samson  25.464286   122.403433   57             Delhi Daredevils
44        TM Dilshan  26.813953   110.124164   24             Delhi Daredevils
45           V Kohli  37.483051   126.588437  160  Royal Challengers Bangalore
46          V Sehwag  27.555556   148.827059  106             Delhi Daredevils
47           WP Saha  25.524590   127.727646   57              Kings XI Punjab
48         YK Pathan  29.816327   140.751445  149        Kolkata Knight Riders
49      Yuvraj Singh  25.653465   126.390244  141          Sunrisers Hyderabad

In [124]:
batsman_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   batsman       50 non-null     object
 1   avg           50 non-null     float64
 2   strike_rate   50 non-null     float64
 3   six           50 non-null     int64
 4   batting_team  50 non-null     object
dtypes: float64(2), int64(1), object(2)
memory usage: 2.1+ KB

In [125]:
batsman_df['batsman'].astype(str)

0       AB de Villiers
1         AC Gilchrist
2             AJ Finch
3            AM Rahane
4            AT Rayudu
5          BB McCullum
6             BJ Hodge
7             CH Gayle
8            DA Miller
9            DA Warner
10            DJ Bravo
11           DJ Hussey
12    DPMD Jayawardene
13            DR Smith
14        F du Plessis
15           G Gambhir
16          GJ Maxwell
17           JH Kallis
18           JP Duminy
19          KA Pollard
20       KC Sangakkara
21          KD Karthik
22             KK Nair
23             M Vijay
24          MEK Hussey
25           MK Pandey
26           MK Tiwary
27            MS Dhoni
28             NV Ojha
29            PA Patel
30            R Dravid
31           RA Jadeja
32           RG Sharma
33          RV Uthappa
34         S Badrinath
35            S Dhawan
36          SC Ganguly
37            SE Marsh
38            SK Raina
39           SPD Smith
40        SR Tendulkar
41           SR Watson
42           SS Tiwary
43           SV Samson
44          TM Dilshan
45             V Kohli
46            V Sehwag
47             WP Saha
48           YK Pathan
49        Yuvraj Singh
Name: batsman, dtype: object

In [126]:
# huma object ko string ma convert karna hoga tabhi kuch hoga

In [127]:
trace = go.Scatter(
    x = batsman_df['avg'],
    y = batsman_df['strike_rate'],
    mode = 'markers',
    #marker={'color': batsman_df['batting_team']}
    marker= {'size': batsman_df['six']}
)
data = [trace]

layout = go.Layout(
    title='Bubble Chart',
    xaxis = {'title': 'avg'},
    yaxis={'title': 'strike_rate',}
)

go.Figure(data,layout)

In [128]:
import plotly.graph_objects as go

# Calculate sizeref to scale bubble sizes appropriately
sizeref = 2. * max(batsman_df['six']) / (40. ** 2)  # 40 is the max bubble size in pixels you want

trace = go.Scatter(
    x=batsman_df['avg'],
    y=batsman_df['strike_rate'],
    mode='markers',
    marker=dict(
        size=batsman_df['six'],
        sizemode='area',
        sizeref=sizeref,
        # Optional: add color mapping here if needed
        # name = batsman_df['batsman']
        # color=batsman_df['batting_team'],  # See note below about color
        showscale=True
    )
)

layout = go.Layout(
    title='Bubble Chart with Adjusted Size',
    xaxis={'title': 'avg'},
    yaxis={'title': 'strike_rate'}
)

fig = go.Figure(data=[trace], layout=layout)
fig.show()

In [129]:
# convert into string 
batsman_df['batsman'] = batsman_df['batsman'].astype(str)
batsman_df['batting_team'] = batsman_df['batting_team'].astype(str)

In [130]:
import plotly.graph_objects as go

# Convert to string if not already
batsman_df['batsman'] = batsman_df['batsman'].astype(str)
batsman_df['batting_team'] = batsman_df['batting_team'].astype(str)

# Calculate sizeref for bubble size scaling
sizeref = 2. * max(batsman_df['six']) / (40. ** 2)

trace = go.Scatter(
    x=batsman_df['avg'],
    y=batsman_df['strike_rate'],
    mode='markers',
    marker=dict(
        size=batsman_df['six'],
        sizemode='area',
        sizeref=sizeref,
        color=batsman_df['batting_team'].astype('category').cat.codes,  # Map categories to numbers
        colorscale='Viridis',
        showscale=True,
        line=dict(width=1, color='DarkSlateGrey')
    ),
    customdata=batsman_df[['batsman', 'batting_team']],  # Pass extra info for hover
    hovertemplate=(
        "<b>Batsman:</b> %{customdata[0]}<br>" +
        "<b>Team:</b> %{customdata[1]}<br>" +
        "<b>Avg:</b> %{x}<br>" +
        "<b>Strike Rate:</b> %{y}<br>" +
        "<extra></extra>"  # Hide trace info box
    )
)

layout = go.Layout(
    title='Bubble Chart with Hover Info',
    xaxis={'title': 'Average'},
    yaxis={'title': 'Strike Rate'}
)

fig = go.Figure(data=[trace], layout=layout)
fig.show()

# Box plot 
displays the five-number summary of a set of data

In [ ]:
# example hamara paas two coloumns ha 
# ek ma salray ha ek ma gender ha rather than ploting one charts 
# we can plot two box plot charts 
# one for male  and one for female

In [136]:
match_agg = delivery.groupby(['match_id'])['total_runs'].sum().reset_index()
season_wise = match_agg.merge(match , left_on='match_id',right_on='id')[['match_id','total_runs','season']]
season_wise

     match_id  total_runs  season
0           1         379    2017
1           2         371    2017
2           3         367    2017
3           4         327    2017
4           5         299    2017
..        ...         ...     ...
631       632         277    2016
632       633         317    2016
633       634         302    2016
634       635         325    2016
635       636         408    2016

[636 rows x 3 columns]

In [ ]:
# tho match_id ha total runs by team 1 and team 2 combine and season 
# huma season 2008 first and last 2017 ko compare karega runs ma

In [137]:
trace = go.Box(
    x = season_wise['total_runs'],
    name = 'All Seasons',
)
data = [trace]

layout = go.Layout(
    title='Total Score analyais ',
    xaxis= {'title': 'Total Score'}
)
go.Figure(data,layout)

In [ ]:
# filter out the data then extract the total_runs coloumns 
season_wise['season'] == 2017
season_2017 = season_wise[season_wise['season'] == 2017]['total_runs']
season_2017

0     379
1     371
2     367
3     327
4     299
5     275
6     358
7     298
8     313
9     317
10    341
11    287
12    343
13    327
14    325
15    353
16    295
17    337
18    313
19    405
20    367
21    397
22    375
23    270
24    355
25    350
26    180
27    317
28    366
29    269
30    321
31    388
32    253
33    323
34    135
35    370
36    327
37    328
38    374
39    313
40    422
41    257
42    284
43    278
44    317
45    381
46    278
47    320
48    392
49    453
50    329
51    312
52    337
53    151
54    312
55    304
56    176
57    218
58    257
Name: total_runs, dtype: int64

In [142]:
season_wise['season'] == 2008
season_2008 = season_wise[season_wise['season'] == 2008]['total_runs']
season_2008

59     304
60     447
61     261
62     331
63     222
64     334
65     285
66     410
67     431
68     298
69     273
70     299
71     309
72     320
73     343
74     275
75     372
76     331
77     347
78     341
79     336
80     347
81     295
82     219
83     253
84     292
85     207
86     375
87     253
88     281
89     248
90     344
91     385
92     315
93     287
94     243
95     314
96     401
97     376
98     135
99     212
100    329
101    331
102    204
103    312
104    297
105    377
106    238
107    353
108    355
109    412
110    309
111    349
112    291
113    295
114    279
115    228
116    327
Name: total_runs, dtype: int64

In [143]:
trace1 = go.Box(
    x = season_2017,
    name = '2017',
)
trace2 = go.Box(
    x = season_2008,
    name = '2008',
)
data = [trace1,trace2]

layout = go.Layout(
    title='Total Score analyais ',
    xaxis= {'title': 'Total Score'}
)
go.Figure(data,layout)

In [ ]:
# on average  ab jada runs score ho raha ha ipl mathces .
# you can draw various conculion lakin wo abhi hamra kam nahi ha

# Distplots
Distribution plots . 
    it is univarite . plot on single varaible but it is combination of three plots .
1. histogram
2. kde  plot
3. rug plot

rug plot = values ko repsective bins ma dalta ja raha ha. density jada matlab waha jada values ha . density kam ha matlab waha kam values ha. ek aor cheez jo rug plot acha bata pata ha in comparison to histogram plot . histogram ma apko ya samaj nahi ata ki bin ka andr distribution kasa ha . example rug plot apko btaya gi -1 sa 0 sa bitch ma more data towards -1 . 
example 2 . their are 4 points between -2 and -1 but points are more closer to -1

so we get an additonal information by the rug plot.

In [ ]:


batsman_df

             batsman        avg  strike_rate  six                 batting_team
0     AB de Villiers  38.307692   145.129059  158  Royal Challengers Bangalore
1       AC Gilchrist  27.223684   133.054662   92              Deccan Chargers
2           AJ Finch  27.186441   126.299213   59                Gujarat Lions
3          AM Rahane  33.593407   117.486549   60       Rising Pune Supergiant
4          AT Rayudu  27.146067   123.014257   79               Mumbai Indians
5        BB McCullum  28.112245   126.318203  124                Gujarat Lions
6           BJ Hodge  33.333333   121.422376   43        Kolkata Knight Riders
7           CH Gayle  41.022472   144.194313  266  Royal Challengers Bangalore
8          DA Miller  34.733333   137.709251   78              Kings XI Punjab
9          DA Warner  40.140000   138.318401  160          Sunrisers Hyderabad
10          DJ Bravo  22.945455   122.286822   48               Mumbai Indians
11         DJ Hussey  26.979592   120.072661   60        Kolkata Knight Riders
12  DPMD Jayawardene  28.250000   118.791064   40              Kings XI Punjab
13          DR Smith  28.392857   132.279534  117                Gujarat Lions
14      F du Plessis  30.116279   124.161074   38       Rising Pune Supergiant
15         G Gambhir  31.541985   120.361200   58        Kolkata Knight Riders
16        GJ Maxwell  25.081633   157.564103   82              Kings XI Punjab
17         JH Kallis  28.552941   105.936272   44  Royal Challengers Bangalore
18         JP Duminy  39.860000   121.970624   78               Mumbai Indians
19        KA Pollard  28.707317   140.621266  148               Mumbai Indians
20     KC Sangakkara  25.953846   118.469101   27              Kings XI Punjab
21        KD Karthik  24.811966   123.008475   71                Gujarat Lions
22           KK Nair  25.173913   124.650161   26             Delhi Daredevils
23           M Vijay  26.431579   120.028681   89          Chennai Super Kings
24        MEK Hussey  38.764706   119.963592   52          Chennai Super Kings
25         MK Pandey  28.500000   116.938453   65        Kolkata Knight Riders
26         MK Tiwary  29.428571   114.127424   39       Rising Pune Supergiant
27          MS Dhoni  37.872340   132.835821  156       Rising Pune Supergiant
28           NV Ojha  20.986486   114.528024   79          Sunrisers Hyderabad
29          PA Patel  21.700935   112.718447   35               Mumbai Indians
30          R Dravid  28.233766   113.347237   28  Royal Challengers Bangalore
31         RA Jadeja  24.055556   118.792867   57                Gujarat Lions
32         RG Sharma  32.612403   128.497251  173               Mumbai Indians
33        RV Uthappa  29.515625   127.635135  125        Kolkata Knight Riders
34       S Badrinath  30.659574   115.742972   28          Chennai Super Kings
35          S Dhawan  32.669725   118.502496   71          Sunrisers Hyderabad
36        SC Ganguly  25.452830   101.734540   42        Kolkata Knight Riders
37          SE Marsh  39.507937   130.109775   78              Kings XI Punjab
38          SK Raina  33.940299   134.995548  174                Gujarat Lions
39         SPD Smith  37.239130   128.507127   45       Rising Pune Supergiant
40      SR Tendulkar  33.826087   114.187867   29               Mumbai Indians
41         SR Watson  30.917647   134.838379  122  Royal Challengers Bangalore
42         SS Tiwary  28.355556   114.851485   45               Mumbai Indians
43         SV Samson  25.464286   122.403433   57             Delhi Daredevils
44        TM Dilshan  26.813953   110.124164   24             Delhi Daredevils
45           V Kohli  37.483051   126.588437  160  Royal Challengers Bangalore
46          V Sehwag  27.555556   148.827059  106             Delhi Daredevils
47           WP Saha  25.524590   127.727646   57              Kings XI Punjab
48         YK Pathan  29.816327   140.751445  149        Kolkata Knight Riders
49      Yuvraj Singh  25.653465   126.390244  141          Sunrisers Hyderabad

In [ ]:
# so in batsman dataframe ma avg and strike rate ha

In [145]:
import plotly.figure_factory as ff

hist_data = [batsman_df['avg']]
group_lables = ['Average']

fig = ff.create_distplot(hist_data = hist_data , group_labels= group_lables)
fig.show()

In [146]:


hist_data = [batsman_df['avg'], batsman_df['strike_rate']]
group_lables = ['Average', 'strike_rate']

fig = ff.create_distplot(hist_data = hist_data , group_labels= group_lables)
fig.show()

In [147]:
# change the bin size of histogram 

hist_data = [batsman_df['avg'], batsman_df['strike_rate']]
group_lables = ['Average', 'strike_rate']

fig = ff.create_distplot(hist_data = hist_data , group_labels= group_lables, bin_size=[10,20])
fig.show()

# Histogram
- x axis par class interval bins size and y axis frequency count

In [ ]:
# humna vo batsman liya  jinhno minimum 150 balls ko khela 
good_batsman = delivery.groupby('batsman')['batsman_runs'].count() > 150
good_batsman = good_batsman[good_batsman].index.to_list()



new = delivery[delivery['batsman'].isin(good_batsman)]
runs = new.groupby('batsman')['batsman_runs'].sum()
balls = new.groupby('batsman')['batsman_runs'].count()

strike_rate = (runs/balls)* 100
ipl_batsman = strike_rate.reset_index()
ipl_batsman
# actully ya stikete rate hona chay hum abhi ya rename nahi kar raha

             batsman  batsman_runs
0     A Ashish Reddy    142.857143
1           A Mishra     89.005236
2          A Symonds    124.711908
3    AA Jhunjhunwala     99.541284
4         AB Agarkar    111.875000
..               ...           ...
157          Y Nagar    105.166052
158  Y Venugopal Rao    113.872832
159        YK Pathan    140.751445
160      YV Takawale    104.918033
161     Yuvraj Singh    126.390244

[162 rows x 2 columns]

In [168]:
# plot hisogram 
trace = go.Histogram(
    x = ipl_batsman['batsman_runs'], # strike rate
    #name = 'Strike Rate Variation'
)
data = [trace]
layout = go.Layout(
    title= 'Strike Rate Analysis',
    xaxis={'title':'Strike Rate'}
)

go.Figure(data,layout)

In [ ]:
# most of strike rate of person is 120 to 125 their are 29 batsman  
# it looks like normal distribution 
# most of the strike rate is 110 to 120 
# abhi esna bin size 5 liya ha aap chaho tha isko bada aor khata skata ho .

In [ ]:
# you can increase or decrease the bin size you know 
# or aap ek custome range bhi bata sakta ha start and end

# Heatmaps
A heat map is a grpahical reprsenation of data where the individual values contained in a matrix are represented as colors.
you can work on 3 variables simulatneloy . 
- first 2 varaible are on x and ya axis this are cateogrical or numericals
- 3 varabile  in the form of colour and it should be numerical so we show in the  color gradient

In [177]:
# hum dekna chata ha har over ki ball par kitni 6 laga ha

six = delivery[delivery['batsman_runs'] == 6]
sixes_df = six.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()
sixes_df

            batting_team  over  batsman_runs
0    Chennai Super Kings     1             5
1    Chennai Super Kings     2            17
2    Chennai Super Kings     3            37
3    Chennai Super Kings     4            34
4    Chennai Super Kings     5            41
..                   ...   ...           ...
271  Sunrisers Hyderabad    16            22
272  Sunrisers Hyderabad    17            18
273  Sunrisers Hyderabad    18            37
274  Sunrisers Hyderabad    19            42
275  Sunrisers Hyderabad    20            28

[276 rows x 3 columns]

In [182]:
sixes_df.rename(columns={'batsman_runs': 'six'},inplace = True)

In [183]:
sixes_df

            batting_team  over  six
0    Chennai Super Kings     1    5
1    Chennai Super Kings     2   17
2    Chennai Super Kings     3   37
3    Chennai Super Kings     4   34
4    Chennai Super Kings     5   41
..                   ...   ...  ...
271  Sunrisers Hyderabad    16   22
272  Sunrisers Hyderabad    17   18
273  Sunrisers Hyderabad    18   37
274  Sunrisers Hyderabad    19   42
275  Sunrisers Hyderabad    20   28

[276 rows x 3 columns]

In [184]:
trace = go.Heatmap(
    x = sixes_df['batting_team'],
    y = sixes_df['over'],
    z= sixes_df['six'] # number of sixes
)
data = [trace]
layout = go.Layout(
    title= 'six heatmap'
)

go.Figure(data,layout)

In [ ]:
# side by side heatmap