In [ ]:
import numpy as np
import pandas as pd

generator = np.random.default_rng(123)
df = pd.DataFrame({
    'john': generator.choice([True, False], size=10, replace=True),
    'judy': generator.choice([True, False], size=10, replace=True)
})
display(df)
party = df.copy()

In [ ]:
party.replace([True,False],[0,1],inplace=True)
union = (party['john']==0) & (party['judy']==0)
party.loc[union]

In [ ]:
party.loc[~union]

In [ ]:
#party['days']= 1
party['days'][0]= 0
party['days'][5]= 0
party

In [134]:
#party['days'].cumsum()
df['party_till_days']= party['days'].cumsum()
display(df)

    john   judy  party_till_days
0   True   True                0
1  False  False                1
2  False   True                2
3   True  False                3
4  False   True                4
5   True   True                4
6   True  False                5
7   True  False                6
8   True  False                7
9   True  False                8

In [139]:
machine_products = pd.DataFrame({
    'machine': ['abc', 'abc', 'def', 'def', 'def', 'ghi'],
    'product': ['skittles', 'soap', 'soap', 'm&ms', 'skittles', 'm&ms'],
    'stock': [10, 0, 15, 2, 0, 3]
})
display(machine_products)

  machine   product  stock
0     abc  skittles     10
1     abc      soap      0
2     def      soap     15
3     def      m&ms      2
4     def  skittles      0
5     ghi      m&ms      3

In [146]:
x = machine_products.groupby(by='product').agg(
    n_machine= 
)
x.size()

product
m&ms        2
skittles    2
soap        2
dtype: int64

In [149]:
couples = pd.DataFrame({
    'person1': ['Cody', 'Dustin', 'Peter', 'Adam', 'Ryan', 'Brian', 'Jordan', 'Gregory'],
    'person2': ['Sarah', 'Amber', 'Brianna', 'Caitlin', 'Rachel', 'Kristen', 'Alyssa', 'Morgan']
}).convert_dtypes()

ages = pd.DataFrame({
    'person': ['Adam', 'Alyssa', 'Amber', 'Brian', 'Brianna', 'Caitlin', 'Cody', 'Dustin', 'Gregory', 'Jordan',
            'Kristen', 'Rachel', 'Morgan', 'Peter', 'Ryan', 'Sarah'],
    'age': [62, 40, 41, 50, 65, 29, 27, 39, 42, 39, 33, 61, 43, 55, 28, 36]
}).convert_dtypes()

display(couples)
display(ages)

   person1  person2
0     Cody    Sarah
1   Dustin    Amber
2    Peter  Brianna
3     Adam  Caitlin
4     Ryan   Rachel
5    Brian  Kristen
6   Jordan   Alyssa
7  Gregory   Morgan

     person  age
0      Adam   62
1    Alyssa   40
2     Amber   41
3     Brian   50
4   Brianna   65
5   Caitlin   29
6      Cody   27
7    Dustin   39
8   Gregory   42
9    Jordan   39
10  Kristen   33
11   Rachel   61
12   Morgan   43
13    Peter   55
14     Ryan   28
15    Sarah   36

In [152]:
couples.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   person1  8 non-null      string
 1   person2  8 non-null      string
dtypes: string(2)
memory usage: 256.0 bytes

In [170]:
table1 = pd.merge(
    left=couples,
    right= ages,
    how='inner',
    left_on='person1',
    right_on= 'person'
    
)
table1

   person1  person2   person  age
0     Cody    Sarah     Cody   27
1   Dustin    Amber   Dustin   39
2    Peter  Brianna    Peter   55
3     Adam  Caitlin     Adam   62
4     Ryan   Rachel     Ryan   28
5    Brian  Kristen    Brian   50
6   Jordan   Alyssa   Jordan   39
7  Gregory   Morgan  Gregory   42

In [171]:
table2 = pd.merge(
    left=couples,
    right= ages,
    how='inner',
    left_on='person2',
    right_on= 'person'
    
)
table2

   person1  person2   person  age
0     Cody    Sarah    Sarah   36
1   Dustin    Amber    Amber   41
2    Peter  Brianna  Brianna   65
3     Adam  Caitlin  Caitlin   29
4     Ryan   Rachel   Rachel   61
5    Brian  Kristen  Kristen   33
6   Jordan   Alyssa   Alyssa   40
7  Gregory   Morgan   Morgan   43

In [ ]:
final= pd.merge(
    left=table1,
    right= table2,
    how='inner',
    left_index=True,
    
    
)
final

In [178]:
pd.concat([table1,table2],axis=1)

   person1  person2   person  age  person1  person2   person  age
0     Cody    Sarah     Cody   27     Cody    Sarah    Sarah   36
1   Dustin    Amber   Dustin   39   Dustin    Amber    Amber   41
2    Peter  Brianna    Peter   55    Peter  Brianna  Brianna   65
3     Adam  Caitlin     Adam   62     Adam  Caitlin  Caitlin   29
4     Ryan   Rachel     Ryan   28     Ryan   Rachel   Rachel   61
5    Brian  Kristen    Brian   50    Brian  Kristen  Kristen   33
6   Jordan   Alyssa   Jordan   39   Jordan   Alyssa   Alyssa   40
7  Gregory   Morgan  Gregory   42  Gregory   Morgan   Morgan   43