In [3]:
import pandas as pd 
import numpy as np
df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar', 'bar', 'foo', 'foo'],
    'B': [False, True, False, True, True, True, True],
    'C': [2.1, 1.9, 3.6, 4.0, 1.9, 7.8, 2.8],
    'D': [50, np.nan, 30, 90, 10, np.nan, 10]
}).convert_dtypes()  
#convert_dtypes is a handy way to make sure we're using pandas' modern String and Integer datatypes
# which allow for NaN values. Without it, A would be type 'object', and D would be type 'float64'.
display(df)

     A      B    C     D
0  foo  False  2.1    50
1  bar   True  1.9  <NA>
2  foo  False  3.6    30
3  bar   True  4.0    90
4  bar   True  1.9    10
5  foo   True  7.8  <NA>
6  foo   True  2.8    10

In [39]:
df.groupby(by='A').first(4)

         B    C   D
A
bar   True  1.9  90
foo  False  2.1  50

In [20]:
var = df.groupby(by='A')
var

In [21]:
print(id(var))

3024703645872

In [22]:
print(id(df))

3024704369952

In [ ]:
#like this 
        # |     |  A  |   B   |  C  |   D  |
        # |:---:|:---:|:-----:|:---:|:----:|
        # |   1 | bar | True  | 1.9 | <NA> |
        # |   3 | bar | True  |   4 | 90   |
        # |   4 | bar | True  | 1.9 | 10   |
        # |-----|-----|-------|-----|------|
        # |   0 | foo | False | 2.1 | 50   |
        # |   2 | foo | False | 3.6 | 30   |
        # |   5 | foo | True  | 7.8 | <NA> |
        # |   6 | foo | True  | 2.8 | 10   |

In [23]:
var.__iter__()

In [24]:
var.groups

{'bar': [1, 3, 4], 'foo': [0, 2, 5, 6]}

In [25]:
var.indices

{'bar': array([1, 3, 4], dtype=int64), 'foo': array([0, 2, 5, 6], dtype=int64)}

In [ ]:
var.get_group(var)

In [29]:
var.nunique()

     B  C  D
A
bar  1  2  2
foo  2  4  3

how many groups are made

In [30]:
var.ngroups

2

number of  rows in  each groups

In [31]:
var.size()

A
bar    3
foo    4
dtype: int64

indexing in group

In [44]:
var.nth(0)

         B    C     D
A
bar   True  1.9  <NA>
foo  False  2.1    50

groups keys and value

In [54]:
var.groups

{'bar': [1, 3, 4], 'foo': [0, 2, 5, 6]}

In [56]:
x = {'bar': [1, 3, 4], 'foo': [0, 2, 5, 6]}
for k,v in x.items():
    print(k,v)

bar [1, 3, 4]
foo [0, 2, 5, 6]

using get you can extract one group

In [46]:
var.get_group('foo')

     A      B    C     D
0  foo  False  2.1    50
2  foo  False  3.6    30
5  foo   True  7.8  <NA>
6  foo   True  2.8    10

In [47]:
var.get_group('bar')

     A     B    C     D
1  bar  True  1.9  <NA>
3  bar  True  4.0    90
4  bar  True  1.9    10

In [53]:
var.groups

{'bar': [1, 3, 4], 'foo': [0, 2, 5, 6]}