In [1]:
import pandas as pd

data1 = {
    "name": ["Sally", "Mary", "John"],
    "age": [50, 40, 30]
}

data2 = {
    "name": ["Sally", "Peter", "Micky"],
    "age": [77, 44, 22]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [2]:
display(df1)

    name  age
0  Sally   50
1   Mary   40
2   John   30

In [3]:
display(df2)

    name  age
0  Sally   77
1  Peter   44
2  Micky   22

In [8]:
df1.merge(df2,how='inner',on='name',left_index=False,right_index=False)

    name  age_x  age_y
0  Sally     50     77