# Create DataFrame

From dictionary

In [1]:
import numpy as np
import pandas as pd

In [2]:
# dict stores column wise
df1 = pd.DataFrame({
    'Name':['bob','Sue','Mary'],
    'age' :[12,15,18]
})
display(df1)

   Name  age
0   bob   12
1   Sue   15
2  Mary   18

From list

In [3]:
#list store rows wise
#list of list or 2d arry
df2 = pd.DataFrame([
    ['bob',12],
    ['sue',15],
    ['mary',18]
],columns=['Name','age'])
df2

   Name  age
0   bob   12
1   sue   15
2  mary   18

# Dataframe inpection

info

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

shape

In [5]:
#How many rows and columns
df1.shape

(3, 2)

axes

In [6]:
df1.axes

[RangeIndex(start=0, stop=3, step=1), Index(['Name', 'age'], dtype='object')]

size

In [7]:
#total elements
df1.size

6

rename

In [8]:
#inplace means permanent changes 
df2.rename(columns={'age':'years'},inplace=True)
df2

   Name  years
0   bob     12
1   sue     15
2  mary     18

# Read files

In [9]:
pets= pd.DataFrame({
    'id': np.random.randint(100),
    'food': np.random.normal(100),
    'animal':pd.Series(np.random.choice(['cat','dog', 'rat'], size= 100,replace = True))
})
display(pets)

    id       food animal
0    5  99.768972    rat
1    5  99.768972    rat
2    5  99.768972    rat
3    5  99.768972    cat
4    5  99.768972    rat
..  ..        ...    ...
95   5  99.768972    dog
96   5  99.768972    dog
97   5  99.768972    cat
98   5  99.768972    rat
99   5  99.768972    dog

[100 rows x 3 columns]

In [10]:
#read docs and book of read_csv

# DataFrame indexeing

In [11]:
df3 = pd.DataFrame({
    'shrimp': [10, 20, 30, 40, 50, 60],
    'crab': [5, 10, 15, 20, 25, 30],
    'red fish': [2, 3, 5, 7, 11, 13]
})
display(df3)

   shrimp  crab  red fish
0      10     5         2
1      20    10         3
2      30    15         5
3      40    20         7
4      50    25        11
5      60    30        13

In [12]:
df3[['shrimp']]

   shrimp
0      10
1      20
2      30
3      40
4      50
5      60

Acess columns by name

In [13]:
#it is a copy  of original datframe
df3[['shrimp','crab',]]

   shrimp  crab
0      10     5
1      20    10
2      30    15
3      40    20
4      50    25
5      60    30

Slicing

In [14]:
# now you takes subset from a Dataframe
df3.iloc[[0,2,5],[1,2]]

   crab  red fish
0     5         2
2    15         5
5    30        13

In [15]:
#when you slicing not pass the list 
df3.iloc[0:5:2,[1,2]]

   crab  red fish
0     5         2
2    15         5
4    25        11

In [16]:
#lets change the index
df3.index = ['a','b','c','d','e','f']
df3

   shrimp  crab  red fish
a      10     5         2
b      20    10         3
c      30    15         5
d      40    20         7
e      50    25        11
f      60    30        13

In [17]:
df3.loc[['a','c'],['shrimp']]

   shrimp
a      10
c      30

do slicing

In [18]:
df3.loc[:'d',['red fish']]

   red fish
a         2
b         3
c         5
d         7

In [19]:
#df3.loc[:3,['red fish']]
#type error
#if you use iloc then it not identify string value

Better way

In [20]:
df3.iloc[:3,[df3.columns.get_loc(c)for c in ['shrimp','red fish']]]
# list combrehenstions

   shrimp  red fish
a      10         2
b      20         3
c      30         5

boolean indexing

In [21]:
mask= df3['shrimp'] <40
mask

a     True
b     True
c     True
d    False
e    False
f    False
Name: shrimp, dtype: bool

In [22]:
#now we use this value to find out values
df3.loc[mask]

   shrimp  crab  red fish
a      10     5         2
b      20    10         3
c      30    15         5

In [23]:
#(df3['shrimp']< 50)& ~(df3['crab' % 2 ])

df3.loc[(df3.shrimp< 50) & ~(df3.crab % 2== 0 )]

   shrimp  crab  red fish
a      10     5         2
c      30    15         5

In [24]:
(df3['shrimp']< 50)  & ~(df3['red fish']< 1)

a     True
b     True
c     True
d     True
e    False
f    False
dtype: bool

# Basic operation

In [25]:
df4 = pd.DataFrame({
    'a': [2,3,11,13],
    'b':['fox','rabbit','hound','rabbit']
})
display(df4)

    a       b
0   2     fox
1   3  rabbit
2  11   hound
3  13  rabbit

add column to datframe

In [26]:
df4['c']= [1,0,1,2]
df4

    a       b  c
0   2     fox  1
1   3  rabbit  0
2  11   hound  1
3  13  rabbit  2

In [27]:
df4['d']= df4['a']+ df4['c']
df4

    a       b  c   d
0   2     fox  1   3
1   3  rabbit  0   3
2  11   hound  1  12
3  13  rabbit  2  15

update values

In [28]:
df4.loc[df4['b']=='rabbit','a']=  0
df4

    a       b  c   d
0   2     fox  1   3
1   0  rabbit  0   3
2  11   hound  1  12
3   0  rabbit  2  15

# Apply method

In [29]:
df5= pd.DataFrame({
    'A': [5.2, 1.7, 9.4],
    'B': [3.9, 4.0, 7.8]
})
print(df5)

     A    B
0  5.2  3.9
1  1.7  4.0
2  9.4  7.8

In [30]:
df5.apply(func=np.sum, axis=0)
#apply each column of df5
#one more example kids

A    16.3
B    15.7
dtype: float64

# Merge

## table preview

In [31]:
pets = pd.DataFrame(
    data={
        'name': ['Mr. Snuggles', 'Honey Chew Chew', 'Professor', 'Chairman Meow', 'Neighbelline'],
        'type': ['cat', 'dog', 'dog', 'cat', 'horse']
    },
    index=[71, 42, 11, 98, 42]
)

visits = pd.DataFrame(
    data={
        'pet_id': [42, 31, 71, 42, 98, 42],
        'date': ['2019-03-15', '2019-03-15', '2019-04-05', '2019-04-06', '2019-04-12', '2019-04-12']
    }
)
display(pets)
display(visits)

               name   type
71     Mr. Snuggles    cat
42  Honey Chew Chew    dog
11        Professor    dog
98    Chairman Meow    cat
42     Neighbelline  horse

   pet_id        date
0      42  2019-03-15
1      31  2019-03-15
2      71  2019-04-05
3      42  2019-04-06
4      98  2019-04-12
5      42  2019-04-12

In [32]:
pd.merge( left=pets,
        right=visits,
        how='inner',
        left_index=True,
        right_on='pet_id'
        )

              name   type  pet_id        date
2     Mr. Snuggles    cat      71  2019-04-05
0  Honey Chew Chew    dog      42  2019-03-15
3  Honey Chew Chew    dog      42  2019-04-06
5  Honey Chew Chew    dog      42  2019-04-12
0     Neighbelline  horse      42  2019-03-15
3     Neighbelline  horse      42  2019-04-06
5     Neighbelline  horse      42  2019-04-12
4    Chairman Meow    cat      98  2019-04-12

## inner join
always  do good names before join table it will make structed data
we reanme the indexes so the indexes are in sequence

In [33]:
pets.index.rename('pet_id',inplace= True)
display(pets)

                   name   type
pet_id
71         Mr. Snuggles    cat
42      Honey Chew Chew    dog
11            Professor    dog
98        Chairman Meow    cat
42         Neighbelline  horse

In [34]:
visits.index.rename('visits_id',inplace= True)
display(visits)

           pet_id        date
visits_id
0              42  2019-03-15
1              31  2019-03-15
2              71  2019-04-05
3              42  2019-04-06
4              98  2019-04-12
5              42  2019-04-12

In [35]:
pd.merge(
    left= pets,
    right= visits,
    how= 'inner',
    on= 'pet_id'
)
#benefit we have a sequence of indexes
#now more readable
#inner intersection b/w two sets

   pet_id             name   type        date
0      71     Mr. Snuggles    cat  2019-04-05
1      42  Honey Chew Chew    dog  2019-03-15
2      42  Honey Chew Chew    dog  2019-04-06
3      42  Honey Chew Chew    dog  2019-04-12
4      42     Neighbelline  horse  2019-03-15
5      42     Neighbelline  horse  2019-04-06
6      42     Neighbelline  horse  2019-04-12
7      98    Chairman Meow    cat  2019-04-12

## left join

In [36]:
pd.merge(
    left= pets,
    right= visits,
    how= 'inner',
    on= 'pet_id'
)
#notice we have nan value beacuse pandas didn't find date value in right table

   pet_id             name   type        date
0      71     Mr. Snuggles    cat  2019-04-05
1      42  Honey Chew Chew    dog  2019-03-15
2      42  Honey Chew Chew    dog  2019-04-06
3      42  Honey Chew Chew    dog  2019-04-12
4      42     Neighbelline  horse  2019-03-15
5      42     Neighbelline  horse  2019-04-06
6      42     Neighbelline  horse  2019-04-12
7      98    Chairman Meow    cat  2019-04-12

## Right join

In [37]:
pd.merge(
    left=pets,
    right= visits,
    how = 'right',
    on = 'pet_id'
)
#right table + intersection(common)in left table
#nan in name and type

   pet_id             name   type        date
0      42  Honey Chew Chew    dog  2019-03-15
1      42     Neighbelline  horse  2019-03-15
2      31              NaN    NaN  2019-03-15
3      71     Mr. Snuggles    cat  2019-04-05
4      42  Honey Chew Chew    dog  2019-04-06
5      42     Neighbelline  horse  2019-04-06
6      98    Chairman Meow    cat  2019-04-12
7      42  Honey Chew Chew    dog  2019-04-12
8      42     Neighbelline  horse  2019-04-12

## Outer join

In [38]:
pd.merge(
    left=pets,
    right= visits,
    how = 'outer',
    on = 'pet_id'
)
#includes all keys in both table
#union of all sets

   pet_id             name   type        date
0      71     Mr. Snuggles    cat  2019-04-05
1      42  Honey Chew Chew    dog  2019-03-15
2      42  Honey Chew Chew    dog  2019-04-06
3      42  Honey Chew Chew    dog  2019-04-12
4      42     Neighbelline  horse  2019-03-15
5      42     Neighbelline  horse  2019-04-06
6      42     Neighbelline  horse  2019-04-12
7      11        Professor    dog         NaN
8      98    Chairman Meow    cat  2019-04-12
9      31              NaN    NaN  2019-03-15

## Anti join
results includes only keys from the left table not the right table

### method one

In [39]:
#results includes only from the one table not others (inverse of one and another)
#Which records from table A don't match any records from table B
outer =pd.merge(
    left= pets,
    right= visits,
    how= 'outer',
    on= 'pet_id',
    indicator= True,
    
)
display(outer)

   pet_id             name   type        date      _merge
0      71     Mr. Snuggles    cat  2019-04-05        both
1      42  Honey Chew Chew    dog  2019-03-15        both
2      42  Honey Chew Chew    dog  2019-04-06        both
3      42  Honey Chew Chew    dog  2019-04-12        both
4      42     Neighbelline  horse  2019-03-15        both
5      42     Neighbelline  horse  2019-04-06        both
6      42     Neighbelline  horse  2019-04-12        both
7      11        Professor    dog         NaN   left_only
8      98    Chairman Meow    cat  2019-04-12        both
9      31              NaN    NaN  2019-03-15  right_only

In [40]:
outer._merge == 'left_only'
#find left only with boolean

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: _merge, dtype: bool

In [41]:
a_not_in_b = outer.loc[outer._merge == 'left_only']
display(a_not_in_b)
#wow this is good you find it but sometimes it memory effiecient 
# to create a big table in intermediate step

   pet_id       name type date     _merge
7      11  Professor  dog  NaN  left_only

### mehod 2
The basic idea is, for each pet_id in the pets table, we check if it exists in the visits table using the isin() method. Then we negate the result and use that to subset the pets table.

In [42]:
pets.index.isin(visits.pet_id)
pets.index.isin(visits['pet_id'])
#both are same you use .  operator or [] 
#bollean array means -> kon kon shi value exists karti means(ha same dona ma comman ha )

array([ True,  True, False,  True,  True])

In [43]:
#we do neagtiation it because array display karta samha true values print hoti ha false nhi 
~(pets.index.isin(visits.pet_id))

array([False, False,  True, False, False])

In [44]:
# we put indexes using loc 
pets.loc
print(pets.loc[~(pets.index.isin(visits.pet_id))])

             name type
pet_id
11      Professor  dog

In [45]:
#if it have duplicate values so we use unique method 
print(pets.loc[~(pets.index.isin(visits.pet_id.unique()))])

             name type
pet_id
11      Professor  dog

### notes
- if you want join Datframe using multiple colums you can do just passing out the list of columns names  to  Dataframe
- if you join two tables a and b using 
a's index and b's column from b the resulting dataframe inherit its index from  b
- if you join on columns from both tables the resulting datfrme will create
a brand new row index
- if you join table a and b  a is the left table b is the right table that can be ordered by first they occured in a second b

# Agrreation
it is used for summmary statistics for datframe

In [46]:
df6 = pd.DataFrame({
    'x': [3.1, 5.5, 9.2, 1.7, 1.2, 8.3, 2.6],
    'y': [1.4, np.nan, 5.0, 5.8, 9.0, np.nan, 9.2]
})
display(df6)

     x    y
0  3.1  1.4
1  5.5  NaN
2  9.2  5.0
3  1.7  5.8
4  1.2  9.0
5  8.3  NaN
6  2.6  9.2

In [47]:
df6.aggregate('sum')
df6.aggregate('mean')

x    4.514286
y    6.080000
dtype: float64

In [48]:
#don't call the function or don't use brackets ins
df6.aggregate(np.median)
#this is a series you make make dataframe by passing in list

x    3.1
y    5.8
dtype: float64

In [49]:
df6.aggregate([np.median])

          x    y
median  3.1  5.8

In [50]:
# you can also use your own custom function 
def myfunc(z):
    return z[1]

In [51]:
#when you use don't use bracket
df6.aggregate(myfunc)

x    5.5
y    NaN
dtype: float64

In [52]:
df6.agg(['mean','median'])

               x     y
mean    4.514286  6.08
median  3.100000  5.80

In [53]:
df6.agg({
    'x' :['mean','sum'],
    'y' :['min', 'max']  
})

              x    y
mean   4.514286  NaN
sum   31.600000  NaN
min         NaN  1.4
max         NaN  9.2

In [54]:
#by default axis = 0 means column wise you also do rows wise axis = 1
df6.agg(['median'], axis=1)

   median
0    2.25
1    5.50
2    7.10
3    3.75
4    5.10
5    8.30
6    5.90

# group by
you can use groupby to parition your dataframe or series and subsequentialy you can aggerate or tranform to it 
- parition(dividing a space into two or many parts)
- aggerate(do statistics & use functions o rows and columns as your choice)

In [55]:
df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar', 'bar', 'foo', 'foo'],
    'B': [False, True, False, True, True, True, True],
    'C': [2.1, 1.9, 3.6, 4.0, 1.9, 7.8, 2.8],
    'D': [50, np.nan, 30, 90, 10, np.nan, 10]
}).convert_dtypes()  
#convert_dtypes is a handy way to make sure we're using pandas' modern String and Integer datatypes
# which allow for NaN values. Without it, A would be type 'object', and D would be type 'float64'.
display(df)

     A      B    C     D
0  foo  False  2.1    50
1  bar   True  1.9  <NA>
2  foo  False  3.6    30
3  bar   True  4.0    90
4  bar   True  1.9    10
5  foo   True  7.8  <NA>
6  foo   True  2.8    10

In [ ]:
df.groupby(by="A")
#df.groupby(by='A') tells pandas to partition the data based on unique values in column A.

In [ ]:
#like this 
        # |     |  A  |   B   |  C  |   D  |
        # |:---:|:---:|:-----:|:---:|:----:|
        # |   1 | bar | True  | 1.9 | <NA> |
        # |   3 | bar | True  |   4 | 90   |
        # |   4 | bar | True  | 1.9 | 10   |
        # |-----|-----|-------|-----|------|
        # |   0 | foo | False | 2.1 | 50   |
        # |   2 | foo | False | 3.6 | 30   |
        # |   5 | foo | True  | 7.8 | <NA> |
        # |   6 | foo | True  | 2.8 | 10   |

In [94]:
group_ab = df.groupby(by=['A',"B"])
group_ab.groups
#it tells you that ('bar',True)
#at 1,3,4 index

             C   D
A   B
bar True   1.9  10
foo False  3.6  30
    True   2.8  10

In [68]:
group_ab.ngroup()
#ngroup() tells us how many partions occurs
#this are indexes that divides in groups
#  row_index  = groups A
# [1,3,4]-> group 0
# [0,2] -> group 1
# [5,6] -> group 2

0    1
1    0
2    1
3    0
4    0
5    2
6    2
dtype: int64

In [70]:
wholes = df.C.apply(np.floor)
display(wholes)

0    2.0
1    1.0
2    3.0
3    4.0
4    1.0
5    7.0
6    2.0
Name: C, dtype: Float64

make dataframe into  groups is useful but you aggreate or transform

In [71]:
df.groupby('A')['C'].agg('sum')

A
bar     7.8
foo    16.3
Name: C, dtype: Float64

In [72]:
#if you pass C into list
df.groupby('A')[['C']].agg('sum')

        C
A
bar   7.8
foo  16.3

In [73]:
df.groupby('A')[['C','D']].agg('sum')

        C    D
A
bar   7.8  100
foo  16.3   90

multiindex column

In [75]:
df.groupby('A').agg({"C": np.sum,"D": ['mean','var']})
#multiindex column

        C     D
      sum  mean     var
A
bar   7.8  50.0  3200.0
foo  16.3  30.0   400.0

multirow index

In [76]:
df.groupby(by=['A','B'])[['D']].mean()

              D
A   B
bar True   50.0
foo False  40.0
    True   10.0

Aggreate with groub by

In [ ]:
df.groupby(by=['B','D']).agg({'C':['min','max']})
#notice it drop nan value you can include null value by

            C
          min  max
B     D
False 30  3.6  3.6
      50  2.1  2.1
True  10  1.9  2.8
      90  4.0  4.0

In [80]:
df.groupby(by=['B','D'],dropna=False).agg({'C':['min','max']})

             C
           min  max
B     D
False 30   3.6  3.6
      50   2.1  2.1
True  10   1.9  2.8
      90   4.0  4.0
      NaN  1.9  7.8

In [83]:
#if you want custom names the you do
df.groupby(by=['B','D'],dropna=False).agg(
    C_min = ('C','min'),
    C_max = ('C','max')
)

           C_min  C_max
B     D
False 30     3.6    3.6
      50     2.1    2.1
True  10     1.9    2.8
      90     4.0    4.0
      NaN    1.9    7.8

transform

In [97]:
df.groupby('A')['C'].transform(lambda x: x.sort_values())
#transform takes one func that you want to appy

0    2.1
1    1.9
2    2.8
3    1.9
4    4.0
5    3.6
6    7.8
Name: C, dtype: Float64

In [101]:
df.groupby('A')['C'].transform(pd.Series.sort_values)

0    2.1
1    1.9
2    2.8
3    1.9
4    4.0
5    3.6
6    7.8
Name: C, dtype: Float64

In [102]:
df['C_sorted_value '] = df.groupby('A')['C'].transform(pd.Series.sort_values)
display(df)
#now you chek and compare it

     A      B    C     D  C_sorted_value
0  foo  False  2.1    50              2.1
1  bar   True  1.9  <NA>              1.9
2  foo  False  3.6    30              2.8
3  bar   True  4.0    90              1.9
4  bar   True  1.9    10              4.0
5  foo   True  7.8  <NA>              3.6
6  foo   True  2.8    10              7.8