In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://gist.githubusercontent.com/DiogoRibeiro7/c6590d0cf119e87c39e31c21a9c0f3a8/raw/4a8e3da267a0c1f0d650901d8295a5153bde8b21/PlayTennis.csv')
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [8]:
pd.crosstab(df['Outlook'], df['Play Tennis'])

Play Tennis  No  Yes
Outlook
Overcast      0    4
Rain          2    3
Sunny         3    2

In [ ]:
# how to find all joint porability 
# normialise = all
pd.crosstab(df['Outlook'], df['Play Tennis'],normalize='all')

Play Tennis        No       Yes
Outlook
Overcast     0.000000  0.285714
Rain         0.142857  0.214286
Sunny        0.214286  0.142857

In [12]:
# how to find all marignal porability 
# normialise = all , margine = True
pd.crosstab(df['Outlook'], df['Play Tennis'],normalize='all',margins=True)

Play Tennis        No       Yes       All
Outlook
Overcast     0.000000  0.285714  0.285714
Rain         0.142857  0.214286  0.357143
Sunny        0.214286  0.142857  0.357143
All          0.357143  0.642857  1.000000

In [ ]:
# yadi apko condiotnal proabblity nikalin

Conditional probability and joint probability are closely related but fundamentally distinct concepts.          
Joint probability measures the likelihood of two events happening together, while conditional probability measures the likelihood of an event occurring given that another event has already occurred.               
They are connected, but conditional probability is the joint probability divided by the probability of the known event

In [13]:
# find the conditoanl proability by normalise = columns
pd.crosstab(df['Outlook'], df['Play Tennis'],normalize='columns')

Play Tennis   No       Yes
Outlook
Overcast     0.0  0.444444
Rain         0.4  0.333333
Sunny        0.6  0.222222

In [5]:
pd.crosstab(df['Outlook'], df['Play Tennis'],normalize='columns').stack().to_dict()

{('Overcast', 'No'): 0.0,
 ('Overcast', 'Yes'): 0.4444444444444444,
 ('Rain', 'No'): 0.4,
 ('Rain', 'Yes'): 0.3333333333333333,
 ('Sunny', 'No'): 0.6,
 ('Sunny', 'Yes'): 0.2222222222222222}

Joint probability is the probability of two events occurring simultaneously.
Marginal probability is the probability of an event irrespective of the outcome of another variable.
Conditional probability is the probability of one event occurring in the presence of a second event.

In [14]:
probability_dict = {}
for i in ['Outlook','Temperature',	'Humidity',	'Wind']:
    probability_dict.update(pd.crosstab(df[i], df['Play Tennis'],normalize='columns').stack().to_dict())

probability_dict

{('Overcast', 'No'): 0.0,
 ('Overcast', 'Yes'): 0.4444444444444444,
 ('Rain', 'No'): 0.4,
 ('Rain', 'Yes'): 0.3333333333333333,
 ('Sunny', 'No'): 0.6,
 ('Sunny', 'Yes'): 0.2222222222222222,
 ('Cool', 'No'): 0.2,
 ('Cool', 'Yes'): 0.3333333333333333,
 ('Hot', 'No'): 0.4,
 ('Hot', 'Yes'): 0.2222222222222222,
 ('Mild', 'No'): 0.4,
 ('Mild', 'Yes'): 0.4444444444444444,
 ('High', 'No'): 0.8,
 ('High', 'Yes'): 0.3333333333333333,
 ('Normal', 'No'): 0.2,
 ('Normal', 'Yes'): 0.6666666666666666,
 ('Strong', 'No'): 0.6,
 ('Strong', 'Yes'): 0.3333333333333333,
 ('Weak', 'No'): 0.4,
 ('Weak', 'Yes'): 0.6666666666666666}

In [18]:
pd.Series(probability_dict)

Overcast  No     0.000000
          Yes    0.444444
Rain      No     0.400000
          Yes    0.333333
Sunny     No     0.600000
          Yes    0.222222
Cool      No     0.200000
          Yes    0.333333
Hot       No     0.400000
          Yes    0.222222
Mild      No     0.400000
          Yes    0.444444
High      No     0.800000
          Yes    0.333333
Normal    No     0.200000
          Yes    0.666667
Strong    No     0.600000
          Yes    0.333333
Weak      No     0.400000
          Yes    0.666667
dtype: float64

In [21]:
pd.Series(probability_dict).unstack(level=0)

,Cool,High,Hot,Mild,Normal,Overcast,Rain,Strong,Sunny,Weak
No,0.200000,0.800000,0.400000,0.400000,0.200000,0.000000,0.400000,0.600000,0.600000,0.400000
Yes,0.333333,0.333333,0.222222,0.444444,0.666667,0.444444,0.333333,0.333333,0.222222,0.666667

In [10]:
from sklearn.model_selection import train_test_split

X = df.drop(columns='Play Tennis')
y = df['Play Tennis']

from sklearn.naive_bayes import CategoricalNB
our_naive_bayes_model = CategoricalNB()
our_naive_bayes_model.fit(X,y)

ValueError: invalid literal for int() with base 10: 'Sunny'

In [11]:
df.columns

Index(['Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis'], dtype='object')

In [16]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

X = df.drop(columns='Play Tennis')
y = df['Play Tennis']
X_train = label_encoder.fit(X)
y_train = label_encoder.fit_transform(y)

ValueError: y should be a 1d array, got an array of shape (14, 4) instead.